const word_type_short_form = {
	"noun": "n.",
	"adjective": "adj.",
	"adverb": "adv.",
	"verb": "v.",
	"conjunction": "c.",
	"phrase": "phr.",
	"onomatopeia": "on.",
	"expression": "exp.",
	"expression adverb": "expadv.",
	"interjection": "int.",
	"suffix": "suff.",
	"preposition": "pre.",
	"prefix": "pref.",
	"pronoun": "pron.",
	"auxiliary": "aux.",
	"numeral": "num."
};

const entry_words = [
	"agelovor",
	"aglen",
	"agralamk",
	"ahakat",
	"ahandat",
	"ahekerol",
	"ahorst",
	"ahorstat",
	"ahorstniy",
	"ajam",
	"akivat",
	"akivelov",
	"akūlan",
	"aleyv",
	"alkor",
	"alskeym",
	"alun",
	"an",
	"an-yitevat",
	"Angleskiy",
	"anglokish",
	"antul",
	"arad",
	"arik",
	"arl",
	"armank",
	"arsenk",
	"artom",
	"avtitiy",
	"azlyeza",
	"azlyeziy",
	"azorik",
	"babūshka",
	"baka",
	"bakov",
	"balfat",
	"bazand",
	"beldat",
	"belekiyvat",
	"belmol",
	"belok",
	"belor",
	"bivat",
	"biy",
	"biyt",
	"bizagat",
	"blavotoyat",
	"bleniy",
	"bleyshom",
	"blyiva",
	"blūshor",
	"bolom",
	"boreyv",
	"boroda",
	"borog",
	"borots-seyrin",
	"borotsat",
	"borotsorfak",
	"bosenk",
	"boshat",
	"boska",
	"boslat",
	"bramat",
	"branzak",
	"brasliyvat",
	"bratsa",
	"braykat",
	"brega",
	"brelen",
	"breshat",
	"breyk",
	"breytat",
	"briy",
	"brogadaskat",
	"brosyat",
	"broylev",
	"broylev-seyrin",
	"byejat",
	"byolm",
	"byortomat",
	"būkat",
	"chag",
	"chaja",
	"chanenk",
	"chanenk-rlova",
	"chantol",
	"chats",
	"chatyat",
	"cheklid",
	"chem",
	"chemikol",
	"chemikolniy porsk",
	"chemikolniy",
	"chenk",
	"chenkat",
	"chesk",
	"chevakat",
	"chevelda",
	"chindat",
	"chochiy",
	"choloskos",
	"chozniyka",
	"chyakat",
	"chyakivat",
	"daglan",
	"dakast",
	"dame",
	"damerat",
	"damero",
	"dan",
	"daneygem",
	"dargol",
	"dasha",
	"dasin",
	"dasinarl",
	"daskon",
	"davektsam",
	"dedūshka",
	"defitsniy",
	"dekat",
	"delat",
	"dergatsyat",
	"disk",
	"distinkish",
	"diyvot",
	"dob",
	"dojaposka",
	"dom",
	"donar",
	"doriya",
	"dorolm",
	"dorolmatsol",
	"dovat",
	"dovinat",
	"doyna",
	"doyna-seyrin",
	"doynaro",
	"drasa",
	"drasom",
	"drikenig",
	"drin",
	"drosel",
	"dyatsat",
	"dyonomat",
	"dyu",
	"dūj",
	"dūtska",
	"eje",
	"ekemiv",
	"eksat",
	"elev",
	"eleytav",
	"elino",
	"elmej",
	"emertat",
	"enlūtar",
	"erat",
	"erentekat",
	"eron",
	"etsa",
	"evnen",
	"eyrin",
	"eyshem",
	"fakat",
	"farsk",
	"fedat",
	"felgniy",
	"felpat",
	"femel",
	"femkyat",
	"fernuska",
	"feto",
	"fetra",
	"feykol",
	"filma",
	"firtat",
	"fishat",
	"fistiyn",
	"flaba",
	"flar",
	"flezat",
	"foden",
	"fogor",
	"foka",
	"folinat",
	"folp",
	"ford",
	"forkach",
	"forl",
	"formikat",
	"fornul",
	"forokosh",
	"forokoshyat",
	"foron",
	"fortul",
	"frastat",
	"fresenk",
	"freyn",
	"freynom",
	"freyshyat",
	"furkeyl",
	"fyada",
	"fyadkaziy",
	"fyerda (1)",
	"fyerda (2)",
	"fyesha",
	"fyetsat",
	"fyij",
	"fū",
	"fūmat",
	"fūshor",
	"fūskol",
	"gadren",
	"gadska",
	"galavat",
	"galon",
	"gardorn",
	"garel",
	"geld",
	"gelnat",
	"gidolm",
	"gis",
	"gitara",
	"glaz",
	"glaziy-gofal",
	"gledol",
	"glomat",
	"gofal",
	"gojest",
	"golfat",
	"golochas",
	"golpar",
	"goreym",
	"gorin",
	"gorovolm",
	"gorst",
	"gosin",
	"goskom",
	"gosteyn",
	"goveyn",
	"gozam",
	"gralatin",
	"gramat",
	"grold",
	"gulva",
	"gunon",
	"gurk",
	"gyelat",
	"gyoch",
	"hakin narin",
	"hakin",
	"hakin-solerat",
	"hamiya",
	"hanakin",
	"harskat",
	"harskivolm",
	"havandat",
	"hazak",
	"hazakniy porsk",
	"hazakniy",
	"heka",
	"hemreviyta",
	"heton",
	"hev",
	"heveskaniy",
	"heveskat",
	"heviy",
	"heyjok",
	"hilim",
	"hiska",
	"hiv",
	"hiynak",
	"hobrat",
	"hoja",
	"holmat",
	"holova",
	"holvat",
	"honva",
	"horold",
	"horosho",
	"hosat",
	"hosom",
	"hosor",
	"hotyat",
	"hovya",
	"hurk",
	"hūgnavol",
	"hūva",
	"igej",
	"ijek",
	"ijyat",
	"ilgrin",
	"illisin",
	"imenak",
	"iretem",
	"ishav",
	"isheym",
	"isik",
	"isnik",
	"isobramej",
	"istat",
	"itam",
	"itevat",
	"iteviyan",
	"itevya-nosen",
	"jaken",
	"jakot",
	"jalat",
	"jalga",
	"janholva",
	"janholvat",
	"jebat",
	"jelb",
	"jem",
	"jem-prozas",
	"jem-soleras",
	"jemniy ūtro",
	"jenerev",
	"jenrūk",
	"jentorom",
	"jerat",
	"jesat",
	"jevanat",
	"jireyk",
	"jiysniy",
	"jogladya",
	"joglod",
	"joklun",
	"joklun-seyrin",
	"jolon",
	"jolvun, -mūt",
	"jonosk",
	"jorol",
	"jovoma",
	"jrenat",
	"jromalar",
	"jūkat",
	"jūkol",
	"kacholnakin",
	"kaf",
	"Kagalar",
	"Kagalarskiy",
	"kagrav",
	"kanek",
	"karjen",
	"kastarkish",
	"katalizator",
	"katoj",
	"katokol",
	"kejat",
	"kelink",
	"kelm",
	"kelomat",
	"keravat",
	"kerem",
	"ketsat",
	"keyda",
	"keymo",
	"keynka",
	"keyrin",
	"khadiyatiy",
	"khamiy-gofal",
	"khamojan",
	"khamyat",
	"khan",
	"khaviko",
	"khnaba",
	"khnabsiy",
	"khneskiya",
	"khnolot",
	"khnorota",
	"khnūla",
	"khnūlavat",
	"khomat",
	"khtiysniy",
	"kishem",
	"kiyna",
	"kiynat",
	"klabanat",
	"klavom",
	"klest",
	"kliyj",
	"kliyjbosenk",
	"klobol",
	"klod",
	"klom",
	"klosis",
	"klov",
	"kniyga",
	"kniyga-dom",
	"knizyo",
	"knopka",
	"knoto",
	"koda",
	"kodosh",
	"kodyat",
	"kofregad",
	"kohel",
	"kojnok",
	"kol",
	"kolminar, kolm",
	"koloshem",
	"komnata",
	"korab",
	"korin",
	"korobka",
	"korust",
	"korustiyn",
	"koshan",
	"koshana",
	"koslama",
	"kosma",
	"kosoril",
	"kot",
	"krasenk",
	"krat",
	"kray",
	"krelitsa",
	"krepkiy",
	"krisnat",
	"kriysa",
	"krold",
	"kvartira",
	"lamk",
	"lanakon",
	"lanikyat",
	"lano",
	"latas",
	"lazoprak",
	"lemat",
	"lemeynat",
	"lenharsav",
	"leselat",
	"lesjo",
	"lesjoniy",
	"leyn",
	"leyrk",
	"leyrkat",
	"lij",
	"lin",
	"linikav",
	"linya",
	"lis",
	"liynkum",
	"lodska",
	"logok",
	"loloska",
	"loma",
	"lomisk",
	"lomiyn",
	"lons",
	"lopelat",
	"lornin",
	"lornul",
	"loron",
	"lorosil",
	"lorvet",
	"losik",
	"lot",
	"lovmor",
	"lovo",
	"loykat",
	"lyakasin",
	"lyan",
	"lyoj",
	"lyom",
	"lyosabyo",
	"lyosibat",
	"lūmenat",
	"lūmenekas",
	"lūnst",
	"lūsniy",
	"lūsom",
	"lūsomniy",
	"lūtsat",
	"maglonak",
	"maglonakin",
	"maglopel",
	"makiv",
	"manakon",
	"manaktaro",
	"manaskev",
	"mank",
	"manomovol",
	"manyerta",
	"marfreno",
	"markav",
	"marnin",
	"maskara",
	"mejeli",
	"melokara",
	"melskenat",
	"merit",
	"metonreyk",
	"mevol",
	"mevron",
	"meya",
	"meynat",
	"meyrn",
	"miln narin",
	"miln",
	"minim",
	"mishanat",
	"miy joglod",
	"miy",
	"miyko",
	"miyneyn",
	"miysh",
	"mlada",
	"mliyr",
	"mloko",
	"mlonor ordelg",
	"mlonor",
	"mlonor-nok",
	"mlordat",
	"mlyetso",
	"mol",
	"mola",
	"moljat",
	"molosin",
	"moltun",
	"molumba",
	"monot",
	"morigot",
	"morston",
	"mralyat",
	"mrel",
	"mreynat",
	"mrokek",
	"mroken",
	"mrolmat",
	"mrotiys",
	"mrotiysniy",
	"myal",
	"myalkat",
	"myano",
	"myerost",
	"myolomat",
	"myuto",
	"mūlenat",
	"mūva",
	"na",
	"nachkol",
	"nafrav itam",
	"nafrav",
	"nakin",
	"nalakish",
	"nalon",
	"nalto",
	"nalv",
	"nalvat",
	"nalvom",
	"napyacho",
	"napyat",
	"narin",
	"nasheta",
	"navek",
	"nebra",
	"nebradyu",
	"netye",
	"neviysk",
	"neygem",
	"neyka",
	"nina",
	"niskagram",
	"niskamra",
	"nodoya",
	"nogen",
	"nogiy",
	"nok",
	"nokarish",
	"noklavin",
	"noko",
	"nolma",
	"noreyg",
	"norom",
	"nos",
	"nosen yofeln seyrin",
	"nosen",
	"nosenus strakol",
	"nov",
	"nyaganork",
	"nyak",
	"nyakat",
	"nyetim",
	"nyezlat",
	"nyoski",
	"nūla",
	"ob",
	"obetsa",
	"oborsk",
	"odak",
	"ofitsya",
	"oglaba",
	"ojan",
	"ojiy",
	"ojog",
	"oklenat",
	"oleym",
	"olezat",
	"olv",
	"omenorst",
	"ona",
	"onayi",
	"onya",
	"ordelg",
	"oret",
	"orfak",
	"orgin",
	"oriy",
	"ork",
	"orkel",
	"oroskiyna",
	"oroskiyniyo",
	"ot-",
	"ot-ūvimachat",
	"ots",
	"otvetat",
	"otveto yadro",
	"otveto",
	"ov",
	"ovig",
	"padat",
	"pakosel",
	"pakyab",
	"pan",
	"panovka",
	"paskenteyl",
	"pastakriy",
	"pelik",
	"pelnorom",
	"peltivenyat",
	"peshkediya",
	"peshkediyo",
	"petika",
	"pil",
	"pivol",
	"plachatun",
	"pliznat",
	"plobskat",
	"plomeysel",
	"ploviyatsol",
	"plyenk",
	"plūmatyat",
	"pochka",
	"pod",
	"poden",
	"pogladat",
	"pojalūsta",
	"pojamits",
	"pojiy",
	"pojno",
	"poka",
	"pokaniy",
	"pold-gofal",
	"poldat",
	"poleym",
	"polom",
	"pomelov",
	"pomit",
	"porsk",
	"posim",
	"poslin",
	"posnek",
	"pot",
	"pranat",
	"priskat",
	"priygat",
	"provikat",
	"prozat",
	"psakar",
	"pyeklo",
	"pyestat",
	"pyetsyo",
	"pyotsa",
	"pyotskiy",
	"pūkat",
	"rabotat",
	"ralinefeyv",
	"redojan",
	"remo",
	"remohilm",
	"reviyetat",
	"reya",
	"reyn",
	"reynk",
	"rimar",
	"rinol",
	"rish",
	"rishdyu",
	"riy",
	"riyschat",
	"riyscho",
	"rlem",
	"rleyka",
	"rleykon",
	"rleyton",
	"rliykor",
	"rlobovat",
	"rlort",
	"rlotiva",
	"rlova",
	"rlovaniy",
	"rlovano",
	"rlūmik",
	"rogevik",
	"roka",
	"roltat",
	"romat",
	"ronk",
	"roskyat",
	"roteyn",
	"rovat",
	"rovinlosik",
	"rozkūdat",
	"rūkan",
	"rūkivta",
	"rūvek",
	"saf",
	"sag",
	"salf",
	"salfniy",
	"sanva",
	"sart",
	"savadorn",
	"saveykat",
	"savlat",
	"sayron",
	"sbyaska",
	"sbyejat",
	"sdama",
	"sdemat",
	"sdivat",
	"sdoba",
	"sdojagiy",
	"sdovalat",
	"sefat",
	"sejrem",
	"seleyk",
	"selin ahorstniy",
	"selin",
	"selkat",
	"sen",
	"seniy",
	"senjakat",
	"senva",
	"sert",
	"sevel",
	"sevenak",
	"seviyntikor",
	"seyna",
	"seyrin",
	"seyshim",
	"seyta",
	"shanokat",
	"shara",
	"sharaniy",
	"sharn",
	"shast",
	"shelm",
	"shelnat",
	"shem",
	"shemo",
	"sheynata",
	"sheynatahilm",
	"sheyvat",
	"shoglyo",
	"sholosmat",
	"shovikin",
	"sidat",
	"sifmūjat",
	"sikol",
	"silarkish",
	"sinya",
	"sisak",
	"siskaka",
	"siyma",
	"skafniy",
	"skahem",
	"skan",
	"skaton",
	"skazosat",
	"skojyat",
	"skomyat",
	"skorozat",
	"slava",
	"slavinaskiy",
	"sliykyat",
	"slyak",
	"slyenyat",
	"smegat",
	"smidat",
	"smoterat",
	"snova",
	"sojiy",
	"sokovat",
	"soldat",
	"soler-seyrin",
	"solerat",
	"solmun",
	"solun",
	"somrol",
	"somt",
	"somyenat",
	"sonin",
	"soreym",
	"sorkul",
	"sorn",
	"spaykat",
	"spaykol",
	"sperkat",
	"spistat",
	"spoklam",
	"sproskat",
	"srim",
	"sriyk",
	"srokor",
	"sroviriy",
	"stachevat",
	"stamiy",
	"statach",
	"stivol",
	"stodon",
	"stolm",
	"stonat",
	"stoyat",
	"strakat",
	"strakol",
	"styoza",
	"sveyzachoy",
	"sveyzat",
	"svinyak",
	"svinyakniy",
	"svoloch",
	"svūsat",
	"syero",
	"ta",
	"talgat",
	"tam",
	"tamok",
	"tanakin",
	"tanzavat",
	"tasmot",
	"tasnakin",
	"taspil",
	"tastanak",
	"tatsyat",
	"temen",
	"terolmat",
	"teshem",
	"teviysat",
	"teviysla",
	"teviyslaniy",
	"teyn",
	"teynkat",
	"teysol",
	"tiglom",
	"tinsha",
	"tirt",
	"tiv",
	"tivesel",
	"to",
	"tof",
	"tokin",
	"tolos",
	"ton",
	"tona",
	"tonasikol",
	"tovat",
	"treyvost",
	"trovakat",
	"tsajyo",
	"tsakiyn",
	"tsembiy",
	"tsiyja",
	"tsogniy",
	"tsūk",
	"tumron",
	"tyeja",
	"tyevelm",
	"tyevesat",
	"tūshemol",
	"tūvigen",
	"ulsinan",
	"uu",
	"va joklun joglod",
	"va",
	"vakaj",
	"vampir",
	"vanav",
	"variyn",
	"vark",
	"vark-senva",
	"vashem",
	"vat",
	"vatas",
	"vatsavat",
	"vedon",
	"vekin",
	"velin",
	"vemejat",
	"venkel",
	"verat",
	"vereta",
	"vernzat",
	"vidniy",
	"viltav",
	"vinov",
	"virikojan",
	"viskol",
	"vit",
	"vitas",
	"vlachya",
	"vladat",
	"vladetiyo",
	"vlan",
	"vlebiyn",
	"vleyshat",
	"vleysho",
	"vlik",
	"vlind",
	"vliyn",
	"vlo va fyadkaziy",
	"vlo",
	"vlom",
	"vlonorik",
	"vlorniy",
	"vlot",
	"vlunst",
	"vlunstsikol",
	"vlyevlir",
	"vnyertiyak",
	"vodrin",
	"voldat",
	"volfak",
	"volfakniy",
	"volikor",
	"voljun",
	"volnok",
	"vomeygerat",
	"vorgatsyat",
	"vosha",
	"vost",
	"votyokat",
	"votyoko",
	"vovik",
	"vralat",
	"vriynat",
	"vrolo",
	"vtir",
	"vtyesh",
	"vtūsh",
	"vyela",
	"vyen",
	"vyo",
	"vūk",
	"vūtat",
	"yad",
	"yadro",
	"yaglunt",
	"yameyga",
	"yanom",
	"yasha",
	"yeda",
	"yegol",
	"yegtan",
	"yej",
	"yekya",
	"yela",
	"yelen",
	"yeletyoz",
	"yendam",
	"yerikomat",
	"yetol",
	"yetosat",
	"yev",
	"yibik",
	"yigala",
	"yikin",
	"yin",
	"yinforn",
	"yirk",
	"yisiy-gofal",
	"yiska",
	"yiskeva",
	"yiterator",
	"yiv",
	"yofeln",
	"yolen",
	"yom",
	"yonom",
	"yotat",
	"zamorozat",
	"zamsel",
	"zast",
	"zikren",
	"zima",
	"zin",
	"ziynak",
	"zlamkat",
	"zlobra",
	"zlomat",
	"zloy",
	"zlyatold",
	"znagevyat",
	"znomo",
	"zoloto",
	"zombiy",
	"zyej",
	"zyejat",
	"zyejniy",
	"zyetoda",
	"zyob",
	"zyovola",
	"zūl",
	"zūlat",
	"ūkdunat",
	"ūkelin",
	"ūmerat",
	"ūnū-",
	"ūnū-mrotiysniy",
	"ūskeyd",
	"ūtro",
	"ūvimachat",
	"ūvimachniy",
];

const entries = {
	"agelovor": ["noun", "factory"],
	"aglen": ["noun", "tree"],
	"agralamk": ["noun", "science"],
	"ahakat": ["verb", "to impale, to penetrate, to pierce"],
	"ahandat": ["verb", "to surprise"],
	"ahekerol": ["noun", "humanoid"],
	"ahorst": ["noun", "lust"],
	"ahorstat": ["verb", "to lust after, to have an intense sexual desire for"],
	"ahorstniy": ["adjective", "horny (adjective)"],
	"ajam": ["noun", "age"],
	"akivat": ["verb", "to secure, to make safe"],
	"akivelov": ["noun", "security, defense"],
	"akūlan": ["adjective", "aqua, green + blue"],
	"aleyv": ["adjective", "early (adjective)"],
	"alkor": ["noun", "alchoholic drink; wine, beer, ale, mead, gin, vodka, whiskey, etc"],
	"alskeym": ["noun", "capsule"],
	"alun": ["adverb", "up, upwards"],
	"an": ["preposition", "on (preposition)"],
	"an-yitevat": ["verb", "to beware, to watch out, to raise guard, to be careful"],
	"Angleskiy": ["noun", "English, english"],
	"anglokish": ["noun", "anglothite"],
	"antul": ["noun", "armor"],
	"arad": ["adjective", "red"],
	"arik": ["adjective", "possible"],
	"arl": ["noun", "year"],
	"armank": ["noun", "armanite"],
	"arsenk": ["noun", "arsenium"],
	"artom": ["noun", "bullet, bolt of energy/material"],
	"avtitiy": ["adjective", "automatic (adjective)"],
	"azlyeza": ["noun", "fame, reputation, renown"],
	"azlyeziy": ["adjective", "popular, famous"],
	"azorik": ["noun", "asteroid"],
	"babūshka": ["noun", "grandmother, grandma"],
	"baka": ["noun", "pie, pastry"],
	"bakov": ["noun", "trunk of vehicle"],
	"balfat": ["verb", "to die to, to succumb to"],
	"bazand": ["noun", "train"],
	"beldat": ["verb", "to relax, to rest"],
	"belekiyvat": ["verb", "to marry someone"],
	"belmol": ["noun", "target"],
	"belok": ["noun", "rabbit"],
	"belor": ["noun", "thigh"],
	"bivat": ["verb", "to be at a place"],
	"biy": ["verb", "to be; is, am, are, be (past tense: biyt)"],
	"biyt": ["verb", "was, were"],
	"bizagat": ["verb", "to zap, to electrocute, to induce with lightning"],
	"blavotoyat": ["verb", "to behave well"],
	"bleniy": ["adjective", "nice, kind, friendly (adjective)"],
	"bleyshom": ["noun", "town"],
	"blyiva": ["adjective", "hot (adjective)"],
	"blūshor": ["noun", "robe, robes"],
	"bolom": ["noun", "pain"],
	"boreyv": ["noun", "friend"],
	"boroda": ["noun", "beard"],
	"borog": ["adjective", "bitter (adjective)"],
	"borots-seyrin": ["noun", "spacefighter, jet fighter, starfighter (ship)"],
	"borotsat": ["verb", "to fight"],
	"borotsorfak": ["noun", "martial art"],
	"bosenk": ["noun", "ladder"],
	"boshat": ["verb", "to sneak, to creep, to lurk"],
	"boska": ["noun", "boy"],
	"boslat": ["verb", "to let, to allow, to permit"],
	"bramat": ["verb", "to open"],
	"branzak": ["noun", "billion"],
	"brasliyvat": ["verb", "to curse, to put a curse on"],
	"bratsa": ["noun", "bone"],
	"braykat": ["verb", "to control, to manipulate"],
	"brega": ["noun", "crow, raven"],
	"brelen": ["noun", "glass"],
	"breshat": ["verb", "to smile, to grin"],
	"breyk": ["noun", "gate"],
	"breytat": ["verb", "to pull"],
	"briy": ["noun", "village"],
	"brogadaskat": ["verb", "to become fermented, to undergo fermentation"],
	"brosyat": ["verb", "to help, to assist"],
	"broylev": ["noun", "battle"],
	"broylev-seyrin": ["noun", "destroyer"],
	"byejat": ["verb", "to run, to sprint"],
	"byolm": ["noun", "bottle, jar"],
	"byortomat": ["verb", "to barricade, to block a pathway"],
	"būkat": ["verb", "to make"],
	"chag": ["noun", "shit, crap"],
	"chaja": ["noun", "hour"],
	"chanenk": ["noun", "human"],
	"chanenk-rlova": ["noun", "mankind, humans"],
	"chantol": ["noun", "battery, energy cell, energy weapon battery"],
	"chats": ["noun", "spice"],
	"chatyat": ["verb", "to talk, to chat, to have a conversation with"],
	"cheklid": ["noun", "chainmail, maille"],
	"chem": ["conjunction", "than, compared to (conjunction)"],
	"chemikol": ["noun", "chemical"],
	"chemikolniy porsk": ["noun", "chemsuit, chemical suit; a full-body suit designed to protect the wearer from chemicals"],
	"chemikolniy": ["adjective", "chemical (adjective)"],
	"chenk": ["noun", "chain"],
	"chenkat": ["verb", "to bind with chains, to chain; to repeat one after another; to repeat after, to follow after"],
	"chesk": ["noun", "ink"],
	"chevakat": ["verb", "to cleave, to sever, to cut, to chop"],
	"chevelda": ["noun", "honor, honour"],
	"chindat": ["verb", "to be really fond of, to crush on, to be infatuated with"],
	"chochiy": ["noun", "derogatory insult directed to women; slut, thot"],
	"choloskos": ["noun", "chlorine"],
	"chozniyka": ["noun", "school, academy"],
	"chyakat": ["verb", "to hurry, to quicken"],
	"chyakivat": ["verb", "to shake"],
	"daglan": ["noun", "weather"],
	"dakast": ["noun", "dakasti, dakastus (monster, undead)"],
	"dame": ["noun", "lady"],
	"damerat": ["verb", "to cook"],
	"damero": ["noun", "a cook"],
	"dan": ["noun", "hand"],
	"daneygem": ["noun", "flashlight, torch"],
	"dargol": ["adjective", "black"],
	"dasha": ["noun", "spear"],
	"dasin": ["numeral", "ten"],
	"dasinarl": ["noun", "decade, 10 years"],
	"daskon": ["noun", "harbor, docking bay"],
	"davektsam": ["adjective", "different (adjective)"],
	"dedūshka": ["noun", "grandfather, grandpa"],
	"defitsniy": ["adjective", "rare, scarce (adjective)"],
	"dekat": ["verb", "to wear, to don"],
	"delat": ["verb", "to do, act"],
	"dergatsyat": ["verb", "to masturbate"],
	"disk": ["noun", "piece, fragment, part"],
	"distinkish": ["noun", "distinite"],
	"diyvot": ["adjective", "bad (adjective)"],
	"dob": ["noun", "bar of metal"],
	"dojaposka": ["noun", "chart, diagram"],
	"dom": ["noun", "house, home"],
	"donar": ["noun", "father"],
	"doriya": ["noun", "north"],
	"dorolm": ["noun", "radio"],
	"dorolmatsol": ["noun", "radiation"],
	"dovat": ["verb", "to stop"],
	"dovinat": ["verb", "to remove, to take off"],
	"doyna": ["noun", "war"],
	"doyna-seyrin": ["noun", "warship, any ship used for war"],
	"doynaro": ["noun", "warrior, fighter"],
	"drasa": ["adjective", "wide (adjective)"],
	"drasom": ["noun", "width"],
	"drikenig": ["adjective", "nasty, disgusting (adjective)"],
	"drin": ["adjective", "left (noun, adjective)"],
	"drosel": ["noun", "reactor, generator"],
	"dyatsat": ["verb", "to hope"],
	"dyonomat": ["verb", "to disintegrate, to turn into dust"],
	"dyu": ["noun", "day, day cycle"],
	"dūj": ["noun", "word"],
	"dūtska": ["noun", "feces, poop"],
	"eje": ["conjunction", "or (conjunction)"],
	"ekemiv": ["noun", "grenade"],
	"eksat": ["verb", "to exite"],
	"elev": ["adjective", "all, every"],
	"eleytav": ["noun", "amethyst"],
	"elino": ["noun", "elinar"],
	"elmej": ["noun", "ice"],
	"emertat": ["verb", "to like"],
	"enlūtar": ["noun", "information"],
	"erat": ["verb", "to hurt"],
	"erentekat": ["verb", "to enter, to go inside"],
	"eron": ["noun", "pipe"],
	"etsa": ["adjective", "else, other, different (adjective)"],
	"evnen": ["interjection", "a greeting; hello, hi"],
	"eyrin": ["noun", "east"],
	"eyshem": ["noun", "shield"],
	"fakat": ["verb", "to kill, to slay"],
	"farsk": ["noun", "patrol"],
	"fedat": ["verb", "to receive, to collect, to get, to gain"],
	"felgniy": ["adjective", "real (adjective)"],
	"felpat": ["verb", "to put, to place"],
	"femel": ["noun", "enchantom, elf"],
	"femkyat": ["verb", "to close"],
	"fernuska": ["noun", "energy, plasma"],
	"feto": ["adjective", "dry (adjective)"],
	"fetra": ["adjective", "pink"],
	"feykol": ["noun", "death"],
	"filma": ["adjective", "tall (adjective)"],
	"firtat": ["verb", "to tear, to rip apart"],
	"fishat": ["verb", "to feel, to touch"],
	"fistiyn": ["noun", "phystine"],
	"flaba": ["adverb", "away (adverb)"],
	"flar": ["adverb", "there"],
	"flezat": ["verb", "to be fond of"],
	"foden": ["adverb", "present, now (adverb)"],
	"fogor": ["noun", "base, root"],
	"foka": ["adjective", "false (adjective)"],
	"folinat": ["verb", "to will (future tense)"],
	"folp": ["noun", "hood"],
	"ford": ["adjective", "blue"],
	"forkach": ["noun", "storm, tempest"],
	"forl": ["noun", "wire"],
	"formikat": ["verb", "to generate, to make from nothing"],
	"fornul": ["adverb", "forward (adverb)"],
	"forokosh": ["noun", "a warp, a long distance jump"],
	"forokoshyat": ["verb", "to warp"],
	"foron": ["noun", "front (noun)"],
	"fortul": ["noun", "finger"],
	"frastat": ["verb", "to prepare, to ready"],
	"fresenk": ["noun", "fresenite"],
	"freyn": ["adjective", "long (adjective)"],
	"freynom": ["noun", "length"],
	"freyshyat": ["verb", "to kick"],
	"furkeyl": ["noun", "symbol, icon, logo"],
	"fyada": ["noun", "fire"],
	"fyadkaziy": ["noun", "bullshit"],
	"fyerda (1)": ["adverb", "first (adverb)"],
	"fyerda (2)": ["adjective", "first (adjective)"],
	"fyesha": ["noun", "peace, quiet, still, calm"],
	"fyetsat": ["verb", "to throw"],
	"fyij": ["noun", "fish"],
	"fū": ["interjection", "ew, disgusted interjection (interjection)"],
	"fūmat": ["verb", "to smell"],
	"fūshor": ["noun", "oven"],
	"fūskol": ["noun", "cheese"],
	"gadren": ["noun", "apple"],
	"gadska": ["numeral", "five"],
	"galavat": ["verb", "to sing"],
	"galon": ["noun", "rubber"],
	"gardorn": ["noun", "decoration, jewelry, jewellery, ornament, cosmetic, makeup"],
	"garel": ["noun", "daughter"],
	"geld": ["noun", "letter, rune, glyph"],
	"gelnat": ["verb", "to shout, to yell"],
	"gidolm": ["noun", "shadow"],
	"gis": ["numeral", "six"],
	"gitara": ["noun", "guitar"],
	"glaz": ["noun", "eye"],
	"glaziy-gofal": ["noun", "camera"],
	"gledol": ["noun", "job, occupication, work"],
	"glomat": ["verb", "to boil"],
	"gofal": ["noun", "machine"],
	"gojest": ["noun", "us fl oz, fluid ounce"],
	"golfat": ["verb", "to glow"],
	"golochas": ["noun", "intestines, bowel"],
	"golpar": ["noun", "crowd, throng"],
	"goreym": ["noun", "engine"],
	"gorin": ["noun", "month"],
	"gorovolm": ["noun", "furnace"],
	"gorst": ["noun", "liquid"],
	"gosin": ["noun", "a coat"],
	"goskom": ["noun", "soup"],
	"gosteyn": ["noun", "minute"],
	"goveyn": ["noun", "hill"],
	"gozam": ["noun", "ball, sphere"],
	"gralatin": ["noun", "graltite"],
	"gramat": ["verb", "to move"],
	"grold": ["noun", "mace, club"],
	"gulva": ["noun", "cave"],
	"gunon": ["noun", "linen"],
	"gurk": ["noun", "natural oil"],
	"gyelat": ["verb", "to steal"],
	"gyoch": ["noun", "wood"],
	"hakin narin": ["noun", "long range"],
	"hakin": ["adjective", "far (adverb)"],
	"hakin-solerat": ["noun", "teleport"],
	"hamiya": ["noun", "music"],
	"hanakin": ["noun", "airlock"],
	"harskat": ["verb", "to explode"],
	"harskivolm": ["noun", "explosion"],
	"havandat": ["verb", "to cover"],
	"hazak": ["noun", "hazard"],
	"hazakniy porsk": ["noun", "hazmat suit, hazardous materials suit; a full-body suit designed to protect the wearer from chemicals, biohazards, radiation, and other things"],
	"hazakniy": ["adjective", "hazardous (adjective)"],
	"heka": ["adjective", "dirty, unclean, not clean (adjective)"],
	"hemreviyta": ["adjective", "attractive, sexy (adjective)"],
	"heton": ["noun", "group, type, kind, sort"],
	"hev": ["pronoun", "we, us (nominative)"],
	"heveskaniy": ["adjective", "effective, good, influencial (adjective)"],
	"heveskat": ["verb", "to affect, to change, to influence"],
	"heviy": ["pronoun", "we, us, our (possessive)"],
	"heyjok": ["noun", "cannon"],
	"hilim": ["noun", "room"],
	"hiska": ["noun", "wall"],
	"hiv": ["noun", "light"],
	"hiynak": ["noun", "heart"],
	"hobrat": ["verb", "to hug"],
	"hoja": ["noun", "pig, boar, hog"],
	"holmat": ["verb", "to support"],
	"holova": ["noun", "void, space"],
	"holvat": ["verb", "to shake, to shudder, to shiver"],
	"honva": ["noun", "woman, female"],
	"horold": ["noun", "mage, wizard, sorcerer, magic user"],
	"horosho": ["adjective", "safe, secure, okay (adjective)"],
	"hosat": ["verb", "to hold, to have"],
	"hosom": ["noun", "the truth, correct"],
	"hosor": ["noun", "glove"],
	"hotyat": ["verb", "to lift"],
	"hovya": ["pronoun", "we, us (accusative)"],
	"hurk": ["noun", "arm"],
	"hūgnavol": ["noun", "lava, magma"],
	"hūva": ["adjective", "visible (adjective)"],
	"igej": ["adjective", "immune, unaffected (adjective)"],
	"ijek": ["noun", "skill"],
	"ijyat": ["verb", "to turn on"],
	"ilgrin": ["noun", "yellow"],
	"illisin": ["noun", "illisinion"],
	"imenak": ["noun", "a clone"],
	"iretem": ["noun", "tundra, snowy plains"],
	"ishav": ["preposition", "anti, against, versus (preposition)"],
	"isheym": ["noun", "mean, meaning of"],
	"isik": ["noun", "smart, intelligent"],
	"isnik": ["noun", "building"],
	"isobramej": ["noun", "image, picture"],
	"istat": ["verb", "to appear like, to seem"],
	"itam": ["noun", "tip, top, ending"],
	"itevat": ["verb", "to see, to look"],
	"iteviyan": ["noun", "scenery, sight"],
	"itevya-nosen": ["noun", "a guard"],
	"jaken": ["noun", "taiga, snowy forest"],
	"jakot": ["noun", "electricity"],
	"jalat": ["verb", "to hail, to bow"],
	"jalga": ["noun", "sign"],
	"janholva": ["noun", "victory"],
	"janholvat": ["verb", "to win"],
	"jebat": ["verb", "to wait, to stay, to remain"],
	"jelb": ["noun", "dirt"],
	"jem": ["adjective", "good (adjective)"],
	"jem-prozas": ["phrase", "welcome"],
	"jem-soleras": ["phrase", "goodbye"],
	"jemniy ūtro": ["phrase", "good morning"],
	"jenerev": ["noun", "money"],
	"jenrūk": ["noun", "truck"],
	"jentorom": ["noun", "assignment, essay, article"],
	"jerat": ["verb", "to listen, to hear"],
	"jesat": ["verb", "to clean"],
	"jevanat": ["verb", "to drive"],
	"jireyk": ["noun", "laser (weapon), thin hot beam of light"],
	"jiysniy": ["adjective", "happy (adjective)"],
	"jogladya": ["noun", "goddess"],
	"joglod": ["noun", "god, deity"],
	"joklun": ["adjective", "great, mighty (adjective)"],
	"joklun-seyrin": ["noun", "battleship, capital ship"],
	"jolon": ["noun", "territory"],
	"jolvun, -mūt": ["noun", "city"],
	"jonosk": ["noun", "road, street"],
	"jorol": ["noun", "wheel"],
	"jovoma": ["noun", "south"],
	"jrenat": ["verb", "to buy, to purchase"],
	"jromalar": ["noun", "earth"],
	"jūkat": ["verb", "to play"],
	"jūkol": ["noun", "play (the act of playing); a play, opera, or performance"],
	"kacholnakin": ["noun", "a trillion meters, 1,000,000 kilometers"],
	"kaf": ["noun", "woof, bark (interjection)"],
	"Kagalar": ["noun", "Kagalar, kagalar"],
	"Kagalarskiy": ["noun", "Kagalarian language, kagalarian language"],
	"kagrav": ["adjective", "spicy (adjective)"],
	"kanek": ["noun", "virus"],
	"karjen": ["noun", "gadget, trinket, unknown thing"],
	"kastarkish": ["noun", "quastarine"],
	"katalizator": ["noun", "potion base, brewing base, catalyst"],
	"katoj": ["noun", "turret, mounted gun"],
	"katokol": ["noun", "staff, stick, pole"],
	"kejat": ["verb", "to crouch, to sneak"],
	"kelink": ["noun", "container"],
	"kelm": ["noun", "crown, helmet"],
	"kelomat": ["verb", "to need, to require"],
	"keravat": ["verb", "to kiss"],
	"kerem": ["noun", "surcoat, tabard"],
	"ketsat": ["verb", "to wait"],
	"keyda": ["adjective", "being fat (adjective)"],
	"keymo": ["noun", "king, emperor"],
	"keynka": ["noun", "excuse"],
	"keyrin": ["noun", "galaxy"],
	"khadiyatiy": ["noun", "solar system"],
	"khamiy-gofal": ["noun", "detector"],
	"khamojan": ["noun", "purpose, usage, use"],
	"khamyat": ["verb", "to detect"],
	"khan": ["noun", "student, apprentice, learner"],
	"khaviko": ["noun", "empire, kingdom, nation, country, realm, reign"],
	"khnaba": ["noun", "sandwich, burger"],
	"khnabsiy": ["noun", "bread"],
	"khneskiya": ["noun", "mission, quest, assignment, job"],
	"khnolot": ["adjective", "cold (adjective)"],
	"khnorota": ["noun", "corporation, company"],
	"khnūla": ["noun", "mud, dirt, grime, slop"],
	"khnūlavat": ["verb", "to defile, to make dirty, to violate"],
	"khomat": ["verb", "to use"],
	"khtiysniy": ["noun", "penis, male reproductive organs"],
	"kishem": ["noun", "crystal, gem"],
	"kiyna": ["adjective", "brave, bold, courageous (adjective)"],
	"kiynat": ["verb", "to add, to join"],
	"klabanat": ["verb", "to call, to summon"],
	"klavom": ["noun", "concrete"],
	"klest": ["noun", "fang"],
	"kliyj": ["noun", "cell (biology)"],
	"kliyjbosenk": ["noun", "dna"],
	"klobol": ["noun", "table"],
	"klod": ["noun", "speed"],
	"klom": ["adjective", "weird (adjective)"],
	"klosis": ["noun", "golem"],
	"klov": ["adjective", "hard (adjective, not for verbs)"],
	"kniyga": ["noun", "book"],
	"kniyga-dom": ["noun", "library"],
	"knizyo": ["adjective", "sharp (adjective)"],
	"knopka": ["noun", "button"],
	"knoto": ["noun", "someone"],
	"koda": ["adjective", "some, unknown amount"],
	"kodosh": ["noun", "bug, insect"],
	"kodyat": ["verb", "to turn off"],
	"kofregad": ["noun", "an elemental"],
	"kohel": ["noun", "kohl (black makeup thing)"],
	"kojnok": ["noun", "bettle"],
	"kol": ["noun", "coal"],
	"kolminar, kolm": ["noun", "hand radio, walkie talkie, handheld transceiver"],
	"koloshem": ["noun", "lightning"],
	"komnata": ["noun", "room, chamber, lodgings, dwelling, apartment"],
	"korab": ["noun", "ship, vessel"],
	"korin": ["noun", "korin"],
	"korobka": ["noun", "chest, box, kist"],
	"korust": ["noun", "paper"],
	"korustiyn": ["noun", "document"],
	"koshan": ["noun", "horse"],
	"koshana": ["adjective", "interesting (adjective)"],
	"koslama": ["verb", "to cuss, to swear"],
	"kosma": ["noun", "neshozic orc"],
	"kosoril": ["noun", "world"],
	"kot": ["noun", "cat"],
	"krasenk": ["noun", "thunder, sound of lightning"],
	"krat": ["noun", "place, location"],
	"kray": ["noun", "edge"],
	"krelitsa": ["noun", "the cyrillic script"],
	"krepkiy": ["adjective", "sturdy, strong (adjective)"],
	"krisnat": ["verb", "to blush, fluster"],
	"kriysa": ["noun", "rat"],
	"krold": ["noun", "lawn, garden"],
	"kvartira": ["noun", "an apartment"],
	"lamk": ["noun", "reason, cause of"],
	"lanakon": ["noun", "ally, teammate"],
	"lanikyat": ["verb", "to shine, to direct a light towards"],
	"lano": ["conjunction", "then (conjunction)"],
	"latas": ["noun", "beam, bolt of lightning, laser (general term)"],
	"lazoprak": ["noun", "laboratory, room where scientific experiments are performed"],
	"lemat": ["verb", "to read"],
	"lemeynat": ["verb", "to build"],
	"lenharsav": ["noun", "fortification"],
	"leselat": ["verb", "to cry, to weep"],
	"lesjo": ["adjective", "soft (adjective, not for verbs)"],
	"lesjoniy": ["adverb", "softly (adverb)"],
	"leyn": ["preposition", "with (preposition)"],
	"leyrk": ["noun", "a link, connection, or something attached at two ends"],
	"leyrkat": ["verb", "to connect, to link together, to attach"],
	"lij": ["noun", "a lie"],
	"lin": ["noun", "rice"],
	"linikav": ["noun", "shop, store"],
	"linya": ["noun", "line"],
	"lis": ["adjective", "small (adjective)"],
	"liynkum": ["noun", "portal, wormhole"],
	"lodska": ["noun", "boat, rowboat, dinghy"],
	"logok": ["noun", "drink, beverage"],
	"loloska": ["noun", "chest, breast"],
	"loma": ["noun", "bed"],
	"lomisk": ["noun", "air tank, gas tank"],
	"lomiyn": ["noun", "hall, hallway"],
	"lons": ["adjective", "sour (adjective)"],
	"lopelat": ["verb", "to circle, to surround, to go around, to loop"],
	"lornin": ["adverb", "past (adverb); the past (noun)"],
	"lornul": ["adverb", "backward (adverb)"],
	"loron": ["noun", "back (noun)"],
	"lorosil": ["noun", "circlet, crown"],
	"lorvet": ["noun", "land, ground"],
	"losik": ["noun", "station, outpost"],
	"lot": ["adverb", "just, only, merely (adverb)"],
	"lovmor": ["noun", "leader"],
	"lovo": ["noun", "operator, driver, crewmember"],
	"loykat": ["verb", "to drink"],
	"lyakasin": ["noun", "language"],
	"lyan": ["adjective", "bright, shining (adjective)"],
	"lyoj": ["noun", "0.1 fluid ounces, 0.1 fl oz"],
	"lyom": ["noun", "snow"],
	"lyosabyo": ["noun", "lover, significant other"],
	"lyosibat": ["verb", "to love"],
	"lūmenat": ["verb", "to learn"],
	"lūmenekas": ["noun", "knowledge"],
	"lūnst": ["noun", "garbage, trash"],
	"lūsniy": ["adjective", "sad (adjective)"],
	"lūsom": ["noun", "sorrow"],
	"lūsomniy": ["adjective", "sorry"],
	"lūtsat": ["verb", "to talk, to speak, to say"],
	"maglonak": ["noun", "million"],
	"maglonakin": ["noun", "a million meters, 1000 kilometers, standard unit of mesurement in space, especially with warships"],
	"maglopel": ["noun", "ton, 1000 kilograms, 1000000 grams"],
	"makiv": ["adjective", "magenta"],
	"manakon": ["noun", "enemy"],
	"manaktaro": ["noun", "villain"],
	"manaskev": ["adverb", "in front, ahead (adverb)"],
	"mank": ["noun", "gear, equipment"],
	"manomovol": ["noun", "hotel, inn"],
	"manyerta": ["noun", "manners, behaviour"],
	"marfreno": ["noun", "marfrenic people"],
	"markav": ["noun", "command"],
	"marnin": ["noun", "marnine"],
	"maskara": ["noun", "mascara"],
	"mejeli": ["noun", "female reproductive organ"],
	"melokara": ["adjective", "gorgeous, beautiful (adjective)"],
	"melskenat": ["verb", "to approach, to arrive, to enter location"],
	"merit": ["noun", "meat, flesh"],
	"metonreyk": ["noun", "poison"],
	"mevol": ["noun", "head"],
	"mevron": ["noun", "module, addon, extension"],
	"meya": ["pronoun", "i, me (accusative)"],
	"meynat": ["verb", "to can, to able"],
	"meyrn": ["noun", "weapon"],
	"miln narin": ["noun", "short/close range"],
	"miln": ["adverb", "close, near (adverb)"],
	"minim": ["noun", "lamp"],
	"mishanat": ["verb", "to appear"],
	"miy joglod": ["interjection", "surprise interjection, meaning \"oh my god\", \"my god\", and other variants"],
	"miy": ["pronoun", "i, me, my (genitive, possessive)"],
	"miyko": ["adjective", "many, much, a lot (adjective)"],
	"miyneyn": ["noun", "story"],
	"miysh": ["noun", "mouse"],
	"mlada": ["noun", "blood"],
	"mliyr": ["noun", "glue"],
	"mloko": ["noun", "milk"],
	"mlonor ordelg": ["noun", "meteoroid; a small piece of space rock from the original asteroid/meteor; space debris"],
	"mlonor": ["noun", "meteor; the visible streak when an asteroid/meteoroid falls"],
	"mlonor-nok": ["noun", "meteorite; space rock that landed"],
	"mlordat": ["verb", "to destroy, to crumble"],
	"mlyetso": ["adverb", "might, maybe"],
	"mol": ["preposition", "from (preposition)"],
	"mola": ["noun", "mother"],
	"moljat": ["verb", "to carry"],
	"molosin": ["noun", "cow, cattle"],
	"moltun": ["noun", "power, strength"],
	"molumba": ["noun", "nanopus (monster)"],
	"monot": ["noun", "floor"],
	"morigot": ["noun", "morigalt"],
	"morston": ["noun", "planet"],
	"mralyat": ["verb", "to give, to grant"],
	"mrel": ["noun", "energy, power"],
	"mreynat": ["verb", "to burn"],
	"mrokek": ["noun", "mrokek"],
	"mroken": ["noun", "mroken"],
	"mrolmat": ["verb", "to rub"],
	"mrotiys": ["noun", "comfort"],
	"mrotiysniy": ["adjective", "comfortable (adjective)"],
	"myal": ["noun", "meow (noun, interjection)"],
	"myalkat": ["verb", "to meow"],
	"myano": ["adjective", "very, really (adjective)"],
	"myerost": ["adjective", "common (adjective)"],
	"myolomat": ["verb", "to moan"],
	"myuto": ["noun", "shy, timid"],
	"mūlenat": ["verb", "to teach"],
	"mūva": ["noun", "leg"],
	"na": ["pronoun", "i, me, my (nominative)"],
	"nachkol": ["noun", "evil (noun)"],
	"nafrav itam": ["noun", "warhead"],
	"nafrav": ["noun", "missile"],
	"nakin": ["noun", "meter"],
	"nalakish": ["noun", "nalastite"],
	"nalon": ["noun", "animal"],
	"nalto": ["adjective", "inferior, lesser, worse (adjective)"],
	"nalv": ["adjective", "high (adjective)"],
	"nalvat": ["verb", "to raise, to increase"],
	"nalvom": ["noun", "height"],
	"napyacho": ["adjective", "filled, full (adjective)"],
	"napyat": ["verb", "to fill"],
	"narin": ["noun", "distance, range"],
	"nasheta": ["noun", "cloth"],
	"navek": ["noun", "name"],
	"nebra": ["adjective", "next (adjective)"],
	"nebradyu": ["noun", "tomorrow"],
	"netye": ["noun", "lever, switch"],
	"neviysk": ["noun", "star"],
	"neygem": ["noun", "lightbulb, led, light"],
	"neyka": ["noun", "brother"],
	"nina": ["adjective", "dark (adjective)"],
	"niskagram": ["noun", "telekinesis"],
	"niskamra": ["noun", "magic, superhuman power"],
	"nodoya": ["noun", "belly, stomach, bowel"],
	"nogen": ["noun", "pistol (gun)"],
	"nogiy": ["noun", "foot, feet"],
	"nok": ["noun", "stone, rock"],
	"nokarish": ["noun", "controller, driving wheel, joystick"],
	"noklavin": ["noun", "fortress, castle, military base"],
	"noko": ["numeral", "zero, no"],
	"nolma": ["noun", "mineral, metal, crystal"],
	"noreyg": ["noun", "mountain"],
	"norom": ["noun", "number, count, amount"],
	"nos": ["noun", "nose"],
	"nosen yofeln seyrin": ["noun", "carrier ship"],
	"nosen": ["noun", "soldier, troop, infantry"],
	"nosenus strakol": ["noun", "ptsd, post-traumatic stress disorder"],
	"nov": ["adverb", "not"],
	"nyaganork": ["noun", "dragon, wyvern"],
	"nyak": ["interjection", "a cuss word"],
	"nyakat": ["verb", "to hate"],
	"nyetim": ["adjective", "desolate, empty, dry (adjective)"],
	"nyezlat": ["verb", "to lick"],
	"nyoski": ["adjective", "lost, missing (adjective)"],
	"nūla": ["adjective", "beautiful, pretty (adjective)"],
	"ob": ["numeral", "a, an, one"],
	"obetsa": ["adjective", "another (adjective)"],
	"oborsk": ["noun", "potato"],
	"odak": ["adjective", "blunt, not sharp (adjective)"],
	"ofitsya": ["adjective", "official, formal (adjective)"],
	"oglaba": ["noun", "trouble, problem"],
	"ojan": ["preposition", "of"],
	"ojiy": ["conjunction", "and (conjunction)"],
	"ojog": ["adjective", "ugly (adjective)"],
	"oklenat": ["verb", "to fix, to repair"],
	"oleym": ["noun", "circle"],
	"olezat": ["verb", "to enjoy, to take pleasure in"],
	"olv": ["adjective", "old (adjective)"],
	"omenorst": ["noun", "divination, future sight"],
	"ona": ["pronoun", "she, her (nominative)"],
	"onayi": ["pronoun", "she, her (genitive, possessive)"],
	"onya": ["pronoun", "she, her (accusative)"],
	"ordelg": ["noun", "pebble, small rock"],
	"oret": ["adverb", "out, outside (adverb)"],
	"orfak": ["noun", "art"],
	"orgin": ["noun", "mouth"],
	"oriy": ["noun", "cooking oil"],
	"ork": ["noun", "ogre, orc, monster (monster)"],
	"orkel": ["noun", "axe"],
	"oroskiyna": ["verb", "to warn"],
	"oroskiyniyo": ["noun", "warning"],
	"ot-": ["prefix", "opposite for verbs"],
	"ot-ūvimachat": ["verb", "to deactivate, to turn off, to switch off"],
	"ots": ["preposition", "off (preposition)"],
	"otvetat": ["verb", "to respond"],
	"otveto yadro": ["noun", "reactor, generator (formal)"],
	"otveto": ["noun", "a response, a reaction"],
	"ov": ["noun", "ear"],
	"ovig": ["noun", "bird"],
	"padat": ["verb", "to poke, to tap"],
	"pakosel": ["noun", "appearance, looks"],
	"pakyab": ["noun", "bucket, can"],
	"pan": ["conjunction", "but, yet, still (conjunction)"],
	"panovka": ["noun", "rifle (gun)"],
	"paskenteyl": ["noun", "cylinder"],
	"pastakriy": ["noun", "baldric, sling"],
	"pelik": ["noun", "emotion, expression"],
	"pelnorom": ["noun", "weight"],
	"peltivenyat": ["verb", "to study, to research"],
	"peshkediya": ["noun", "crime"],
	"peshkediyo": ["noun", "a criminal"],
	"petika": ["noun", "chicken"],
	"pil": ["noun", "a gram, 1 gram"],
	"pivol": ["noun", "beer, ale"],
	"plachatun": ["noun", "century, 100 years"],
	"pliznat": ["verb", "to spark, to stir"],
	"plobskat": ["verb", "to bore, to be bored"],
	"plomeysel": ["noun", "necklace, amulet"],
	"ploviyatsol": ["noun", "prototype, an invented thing that is still in testing/being tested"],
	"plyenk": ["noun", "makeup, make-up, beauty products"],
	"plūmatyat": ["verb", "to fall"],
	"pochka": ["adjective", "dear (noun, adjective)"],
	"pod": ["preposition", "under (preposition)"],
	"poden": ["noun", "noon"],
	"pogladat": ["verb", "to pet, to caress, to soothe"],
	"pojalūsta": ["interjection", "please (interjection)"],
	"pojamits": ["noun", "chemise, frock, undergarment"],
	"pojiy": ["adjective", "cute, sweet, pretty (adjective)"],
	"pojno": ["adjective", "late (noun, adjective)"],
	"poka": ["adjective", "rough, hard (adjective)"],
	"pokaniy": ["adverb", "roughly, recklessly (adverb)"],
	"pold-gofal": ["noun", "scanner"],
	"poldat": ["verb", "to scan"],
	"poleym": ["noun", "cloak"],
	"polom": ["adjective", "slow (adjective)"],
	"pomelov": ["noun", "tower"],
	"pomit": ["noun", "west"],
	"porsk": ["noun", "suit, full body suit"],
	"posim": ["noun", "gas"],
	"poslin": ["adjective", "middle (noun, adjective)"],
	"posnek": ["noun", "solid"],
	"pot": ["noun", "sweat"],
	"pranat": ["verb", "to repeat"],
	"priskat": ["verb", "to practice, to train"],
	"priygat": ["verb", "to jump"],
	"provikat": ["verb", "to punch"],
	"prozat": ["verb", "to come"],
	"psakar": ["noun", "gun, rifle, pistol"],
	"pyeklo": ["noun", "chair"],
	"pyestat": ["verb", "to annoy, to bother, to irritate"],
	"pyetsyo": ["noun", "a pet, a domesticated animal"],
	"pyotsa": ["noun", "hip"],
	"pyotskiy": ["noun", "buttocks"],
	"pūkat": ["verb", "to scare"],
	"rabotat": ["verb", "to work (with labor), to run, to execute"],
	"ralinefeyv": ["noun", "hospital"],
	"redojan": ["noun", "reedian (furry)"],
	"remo": ["noun", "relief"],
	"remohilm": ["noun", "bathroom, restroom, public bathroom"],
	"reviyetat": ["verb", "to have sex"],
	"reya": ["pronoun", "you (accusative)"],
	"reyn": ["pronoun", "your (genitive, possessive)"],
	"reynk": ["noun", "class, rank, role"],
	"rimar": ["noun", "window, visor"],
	"rinol": ["noun", "ghost, spirit"],
	"rish": ["adjective", "previous, last"],
	"rishdyu": ["noun", "yesterday"],
	"riy": ["pronoun", "you (nominative)"],
	"riyschat": ["verb", "to ride"],
	"riyscho": ["noun", "knight"],
	"rlem": ["noun", "tongue"],
	"rleyka": ["noun", "car"],
	"rleykon": ["noun", "vehicle"],
	"rleyton": ["noun", "crew"],
	"rliykor": ["noun", "faction"],
	"rlobovat": ["verb", "to free"],
	"rlort": ["adjective", "poor (adjective)"],
	"rlotiva": ["adjective", "right (noun, adjective)"],
	"rlova": ["noun", "kin, kinship, kind, race, species"],
	"rlovaniy": ["adjective", "native, of an origin, or kind (adjective)"],
	"rlovano": ["noun", "native, aboriginal"],
	"rlūmik": ["noun", "medicine"],
	"rogevik": ["noun", "robot"],
	"roka": ["noun", "structure, frame"],
	"roltat": ["verb", "to tilt, to become lopsided"],
	"romat": ["verb", "to walk"],
	"ronk": ["noun", "boot"],
	"roskyat": ["verb", "to find, to search"],
	"roteyn": ["noun", "rule, law"],
	"rovat": ["verb", "to check, to inspect"],
	"rovinlosik": ["noun", "checkpoint"],
	"rozkūdat": ["verb", "to rape, to sexually assault"],
	"rūkan": ["noun", "debris, rubble, crumbled pieces"],
	"rūkivta": ["noun", "description"],
	"rūvek": ["noun", "spell, rune"],
	"saf": ["noun", "leaf"],
	"sag": ["noun", "knife, dagger, dirk"],
	"salf": ["noun", "health"],
	"salfniy": ["adjective", "healthy (adjective)"],
	"sanva": ["noun", "character, avatar, person"],
	"sart": ["noun", "grass"],
	"savadorn": ["noun", "dictionary"],
	"saveykat": ["verb", "to scream"],
	"savlat": ["verb", "to analyze, to experiment, to test"],
	"sayron": ["noun", "flag"],
	"sbyaska": ["noun", "beach, strand, coast, shore"],
	"sbyejat": ["verb", "to escape"],
	"sdama": ["noun", "fork"],
	"sdemat": ["verb", "to should"],
	"sdivat": ["verb", "to aim"],
	"sdoba": ["noun", "pants"],
	"sdojagiy": ["adjective", "muscular (adjective)"],
	"sdovalat": ["verb", "to send"],
	"sefat": ["verb", "to thank"],
	"sejrem": ["noun", "meadows, grasslands"],
	"seleyk": ["adjective", "gray, grey (adjective)"],
	"selin ahorstniy": ["adjective", "erotic, sexually pleasing (adjective)"],
	"selin": ["adjective", "same, like, equal (adjective)"],
	"selkat": ["verb", "to rot"],
	"sen": ["pronoun", "he, him (nominative)"],
	"seniy": ["pronoun", "he, him, his (genitive, possessive)"],
	"senjakat": ["verb", "to injure, to hurt, to wound, to maim"],
	"senva": ["noun", "man, male"],
	"sert": ["noun", "shirt"],
	"sevel": ["noun", "water"],
	"sevenak": ["noun", "sea, ocean"],
	"seviyntikor": ["noun", "setting, configuration"],
	"seyna": ["pronoun", "he, him (accusative)"],
	"seyrin": ["noun", "spacecraft, spaceship, ship"],
	"seyshim": ["noun", "terrain, land"],
	"seyta": ["adjective", "exotic, otherworldly (adjective)"],
	"shanokat": ["verb", "to spy, to pry, to watch without being known"],
	"shara": ["noun", "metal"],
	"sharaniy": ["noun", "metallic"],
	"sharn": ["noun", "iron"],
	"shast": ["preposition", "through (preposition)"],
	"shelm": ["noun", "mask"],
	"shelnat": ["verb", "to sleep"],
	"shem": ["conjunction", "how"],
	"shemo": ["conjunction", "who"],
	"sheynata": ["noun", "rainy weather"],
	"sheynatahilm": ["noun", "bathroom, shower room"],
	"sheyvat": ["verb", "to care"],
	"shoglyo": ["noun", "shark"],
	"sholosmat": ["verb", "to clean, to wash"],
	"shovikin": ["noun", "future"],
	"sidat": ["verb", "to sit"],
	"sifmūjat": ["verb", "to surrender, to give up"],
	"sikol": ["noun", "cycle"],
	"silarkish": ["noun", "silartite"],
	"sinya": ["noun", "moon"],
	"sisak": ["adjective", "stupid, idiotic (adjective)"],
	"siskaka": ["noun", "idiot, stupid person (insult)"],
	"siyma": ["noun", "sister"],
	"skafniy": ["noun", "scabbard, sheath"],
	"skahem": ["noun", "the sky"],
	"skan": ["preposition", "over (preposition)"],
	"skaton": ["noun", "wound"],
	"skazosat": ["verb", "to concentrate, to focus"],
	"skojyat": ["verb", "to push"],
	"skomyat": ["verb", "to shoot, to fire weapon"],
	"skorozat": ["verb", "to crawl"],
	"slava": ["noun", "glory"],
	"slavinaskiy": ["noun", "slavic"],
	"sliykyat": ["verb", "to lie down"],
	"slyak": ["noun", "snake, serpent"],
	"slyenyat": ["verb", "to cut, to slice, to slit"],
	"smegat": ["verb", "to bet, to gamble"],
	"smidat": ["verb", "to take off, to doff"],
	"smoterat": ["verb", "to stare, to gaze at, to look intensely"],
	"snova": ["adverb", "again (adverb)"],
	"sojiy": ["noun", "sauce"],
	"sokovat": ["verb", "to sell"],
	"soldat": ["verb", "to tell someone"],
	"soler-seyrin": ["noun", "traveler, traveling ship (not a battleship)"],
	"solerat": ["verb", "to travel, to go, to move to"],
	"solmun": ["adjective", "empty, nothing there (adjective)"],
	"solun": ["noun", "sun"],
	"somrol": ["noun", "night"],
	"somt": ["noun", "something, object"],
	"somyenat": ["verb", "to manufacture, to mechanically create/make"],
	"sonin": ["noun", "sand"],
	"soreym": ["adjective", "white"],
	"sorkul": ["noun", "sorkuls (monster)"],
	"sorn": ["adverb", "down (adverb)"],
	"spaykat": ["verb", "to anger"],
	"spaykol": ["noun", "anger, rage"],
	"sperkat": ["verb", "to stalk"],
	"spistat": ["verb", "to save"],
	"spoklam": ["noun", "message"],
	"sproskat": ["verb", "to ask"],
	"srim": ["noun", "green"],
	"sriyk": ["noun", "claw, talon"],
	"srokor": ["noun", "prison, jail"],
	"sroviriy": ["noun", "ritual, casting a spell action"],
	"stachevat": ["verb", "to tow, to drag"],
	"stamiy": ["noun", "belt"],
	"statach": ["noun", "speech"],
	"stivol": ["noun", "hat, headwear"],
	"stodon": ["noun", "hundred"],
	"stolm": ["noun", "ground, the ground, land"],
	"stonat": ["verb", "to groan"],
	"stoyat": ["verb", "to stand"],
	"strakat": ["verb", "to fear, to be afraid of"],
	"strakol": ["noun", "fear of"],
	"styoza": ["preposition", "between (preposition)"],
	"sveyzachoy": ["adjective", "stuck (adjective)"],
	"sveyzat": ["verb", "to stick onto"],
	"svinyak": ["noun", "pervert, creep"],
	"svinyakniy": ["adjective", "perverted (adjective)"],
	"svoloch": ["noun", "bastard (insult)"],
	"svūsat": ["verb", "to write"],
	"syero": ["adverb", "here (adverb)"],
	"ta": ["preposition", "to, towards, for, at, till"],
	"talgat": ["verb", "to change something"],
	"tam": ["conjunction", "if, in case (conjunction)"],
	"tamok": ["noun", "desert"],
	"tanakin": ["noun", "square"],
	"tanzavat": ["verb", "to dance"],
	"tasmot": ["adjective", "fast, quick (adjective)"],
	"tasnakin": ["noun", "kilometer"],
	"taspil": ["noun", "kilogram, 1000 grams"],
	"tastanak": ["numeral", "thousand"],
	"tatsyat": ["verb", "to tie a knot, to secure"],
	"temen": ["adjective", "rich (adjective)"],
	"terolmat": ["verb", "to attack"],
	"teshem": ["noun", "skin"],
	"teviysat": ["verb", "to watch"],
	"teviysla": ["adjective", "careful (adjective)"],
	"teviyslaniy": ["adverb", "carefully (adverb)"],
	"teyn": ["noun", "a second"],
	"teynkat": ["verb", "to protect, to defend"],
	"teysol": ["noun", "peak, top, highest point, maximum"],
	"tiglom": ["noun", "lizard"],
	"tinsha": ["numeral", "three"],
	"tirt": ["noun", "cake"],
	"tiv": ["adjective", "short (adjective)"],
	"tivesel": ["noun", "clothing, garment, apparel"],
	"to": ["adjective", "so, very (adjective)"],
	"tof": ["pronoun", "they, them, their, group pronoun"],
	"tokin": ["noun", "cube"],
	"tolos": ["numeral", "four"],
	"ton": ["noun", "salt"],
	"tona": ["numeral", "two"],
	"tonasikol": ["noun", "bicycle, bike"],
	"tovat": ["verb", "to try"],
	"treyvost": ["noun", "forest"],
	"trovakat": ["verb", "to execute, to put to death"],
	"tsajyo": ["noun", "a thousand fluid ounces, 1000 fl oz"],
	"tsakiyn": ["noun", "the rest, the remaining"],
	"tsembiy": ["noun", "flower, bloom"],
	"tsiyja": ["noun", "an inch"],
	"tsogniy": ["adjective", "rude, mean, unfriendly (adjective)"],
	"tsūk": ["noun", "door"],
	"tumron": ["adjective", "orange"],
	"tyeja": ["noun", "honey"],
	"tyevelm": ["noun", "game, sport"],
	"tyevesat": ["verb", "to sail, to row a boat"],
	"tūshemol": ["noun", "stew"],
	"tūvigen": ["noun", "system"],
	"ulsinan": ["noun", "ulsinan"],
	"uu": ["interjection", "uhh (interjection)"],
	"va joklun joglod": ["interjection", "surprise interjection, meaning \"great god\", \"holy shit\", \"holy cow\", \"holy moly\", etc"],
	"va": ["pronoun", "it, the, that"],
	"vakaj": ["noun", "tank"],
	"vampir": ["noun", "vampire"],
	"vanav": ["numeral", "eight"],
	"variyn": ["noun", "smoke"],
	"vark": ["noun", "wolf"],
	"vark-senva": ["noun", "werewolf, wolfman"],
	"vashem": ["noun", "sword"],
	"vat": ["pronoun", "that"],
	"vatas": ["pronoun", "those"],
	"vatsavat": ["verb", "to summon, to conjure"],
	"vedon": ["noun", "camoflague"],
	"vekin": ["noun", "disease, sickness"],
	"velin": ["numeral", "nine"],
	"vemejat": ["verb", "to invent"],
	"venkel": ["numeral", "seven"],
	"verat": ["verb", "to start"],
	"vereta": ["noun", "festival"],
	"vernzat": ["verb", "to return"],
	"vidniy": ["adjective", "bold, prominent, sticking out, different (adjective)"],
	"viltav": ["noun", "alarm"],
	"vinov": ["noun", "purple, violet"],
	"virikojan": ["noun", "conquest, invasion"],
	"viskol": ["noun", "military, army"],
	"vit": ["pronoun", "this"],
	"vitas": ["pronoun", "these"],
	"vlachya": ["noun", "witch, hag"],
	"vladat": ["verb", "to own"],
	"vladetiyo": ["noun", "master"],
	"vlan": ["conjunction", "why"],
	"vlebiyn": ["adjective", "together (adjective)"],
	"vleyshat": ["verb", "to fly"],
	"vleysho": ["noun", "flight"],
	"vlik": ["adjective", "wet (adjective)"],
	"vlind": ["noun", "wine"],
	"vliyn": ["conjunction", "when (conjunction)"],
	"vlo va fyadkaziy": ["phrase", "what the hell, wtf (cuss)"],
	"vlo": ["conjunction", "what"],
	"vlom": ["adjective", "more (adjective)"],
	"vlonorik": ["noun", "technology"],
	"vlorniy": ["adjective", "warm (adjective)"],
	"vlot": ["verb", "would"],
	"vlunst": ["noun", "motor"],
	"vlunstsikol": ["noun", "motorcycle, motorbike, dirt bike"],
	"vlyevlir": ["noun", "elevator, lift"],
	"vnyertiyak": ["noun", "hell"],
	"vodrin": ["noun", "week"],
	"voldat": ["verb", "to think"],
	"volfak": ["noun", "danger"],
	"volfakniy": ["adjective", "dangerous (adjective)"],
	"volikor": ["noun", "potion"],
	"voljun": ["noun", "demon"],
	"volnok": ["noun", "volstone (monster, golem)"],
	"vomeygerat": ["verb", "to disappear"],
	"vorgatsyat": ["verb", "to invade"],
	"vosha": ["noun", "evening"],
	"vost": ["adjective", "big (adjective)"],
	"votyokat": ["verb", "to lose"],
	"votyoko": ["noun", "defeat"],
	"vovik": ["noun", "bottle"],
	"vralat": ["verb", "to follow, to go with"],
	"vriynat": ["verb", "to take, to grab"],
	"vrolo": ["conjunction", "where"],
	"vtir": ["conjunction", "after"],
	"vtyesh": ["conjunction", "before (conjunction)"],
	"vtūsh": ["conjunction", "while, whilst (conjunction)"],
	"vyela": ["noun", "hair, fur"],
	"vyen": ["adverb", "in, inside, at (adverb)"],
	"vyo": ["interjection", "no"],
	"vūk": ["adjective", "angry, mad (adjective)"],
	"vūtat": ["verb", "to know, to understand"],
	"yad": ["interjection", "yes"],
	"yadro": ["noun", "core, heart, center"],
	"yaglunt": ["noun", "gear, cogwheel"],
	"yameyga": ["noun", "gymnastics"],
	"yanom": ["noun", "sound, noise"],
	"yasha": ["noun", "gift, present"],
	"yeda": ["noun", "food, meal"],
	"yegol": ["noun", "clay"],
	"yegtan": ["adjective", "salty (adjective)"],
	"yej": ["adjective", "sweet (taste) (adjective)"],
	"yekya": ["noun", "candy"],
	"yela": ["adjective", "true (adjective)"],
	"yelen": ["adjective", "young, new (adjective)"],
	"yeletyoz": ["adjective", "sticky (adjective)"],
	"yendam": ["noun", "a dress, a gown"],
	"yerikomat": ["verb", "to remember"],
	"yetol": ["adjective", "superior, greater, better (adjective)"],
	"yetosat": ["verb", "to eat"],
	"yev": ["noun", "son"],
	"yibik": ["noun", "coin"],
	"yigala": ["noun", "noodles"],
	"yikin": ["noun", "sugar"],
	"yin": ["noun", "time"],
	"yinforn": ["noun", "verb tense"],
	"yirk": ["noun", "worm"],
	"yisiy-gofal": ["noun", "computer"],
	"yiska": ["noun", "maiden, a young unmarried woman, can also refer to a woman who is betrothed but not yet married"],
	"yiskeva": ["noun", "girl"],
	"yiterator": ["noun", "iterator"],
	"yiv": ["noun", "river, stream"],
	"yofeln": ["noun", "cargo"],
	"yolen": ["noun", "computer chip, microchip, circuit board"],
	"yom": ["noun", "celsius (temperature)"],
	"yonom": ["noun", "temperature, heat"],
	"yotat": ["verb", "to want, to wish"],
	"zamorozat": ["verb", "to freeze"],
	"zamsel": ["noun", "plan, strategy, intent"],
	"zast": ["noun", "steel"],
	"zikren": ["noun", "screen"],
	"zima": ["noun", "winter"],
	"zin": ["noun", "ginger"],
	"ziynak": ["noun", "bomb, explosive"],
	"zlamkat": ["verb", "to stab, to stick in"],
	"zlobra": ["noun", "monster, unknown creature"],
	"zlomat": ["verb", "to slash, to cut, to hew"],
	"zloy": ["adjective", "evil, dark, grim (adjective)"],
	"zlyatold": ["noun", "trap"],
	"znagevyat": ["verb", "to capture, to take over"],
	"znomo": ["noun", "janitor"],
	"zoloto": ["adjective", "gold, blond (adjective)"],
	"zombiy": ["noun", "zombie"],
	"zyej": ["noun", "life"],
	"zyejat": ["verb", "to live"],
	"zyejniy": ["adjective", "alive (adjective)"],
	"zyetoda": ["noun", "a lute"],
	"zyob": ["noun", "bump, bulb, protruding extension"],
	"zyovola": ["noun", "a lyre"],
	"zūl": ["adjective", "low (adjective)"],
	"zūlat": ["verb", "to lower, to decrease"],
	"ūkdunat": ["verb", "to transform, to turn into"],
	"ūkelin": ["noun", "violin"],
	"ūmerat": ["verb", "to die"],
	"ūnū-": ["prefix", "negator prefix"],
	"ūnū-mrotiysniy": ["adjective", "uncomfortable (adjective)"],
	"ūskeyd": ["noun", "dog"],
	"ūtro": ["noun", "morning"],
	"ūvimachat": ["verb", "to activate, to turn on, to switch on"],
	"ūvimachniy": ["adjective", "active (adjective)"],
};

const special_declensions = {};
