const word_type_short_form = {
	"noun": "n.",
	"adjective": "adj.",
	"adverb": "adv.",
	"verb": "v.",
	"conjunction": "c.",
	"phrase": "phr.",
	"onomatopeia": "on.",
	"expression": "exp.",
	"expression adverb": "expadv.",
	"interjection": "int.",
	"suffix": "suff.",
	"preposition": "pre.",
	"prefix": "pref.",
	"pronoun": "pron.",
	"auxiliary": "aux.",
	"numeral": "num."
};

const entry_words = [
	"-arvil",
	"-dar",
	"-elov",
	"-lalg",
	"-niy",
	"-o",
	"agelovor",
	"agent",
	"agentelov",
	"aglen",
	"agralamk",
	"ahakat",
	"ahandat",
	"ahekerol",
	"ahorst",
	"ahorstat",
	"ahorstniy",
	"akiv-stolm",
	"akivat",
	"akivelov",
	"akūla",
	"alan",
	"aleyva",
	"alkor",
	"alskeym",
	"an-yitevat",
	"Anglesdar",
	"anglokish",
	"antul",
	"arda",
	"ariyka",
	"armank",
	"arsenk",
	"arta",
	"avtita",
	"azadar",
	"azar",
	"azham",
	"azleza",
	"azlezaniy",
	"azorik",
	"bakov",
	"balbag",
	"balfat",
	"bamat",
	"barat",
	"bast",
	"bazand",
	"beldat",
	"belekiyvadar",
	"belekiyvat",
	"belekiyvelov",
	"belok",
	"belor",
	"biy obasna",
	"biy vlebta volfak",
	"biy",
	"biyzhem",
	"bizagat",
	"blavonat",
	"blavonon",
	"bleniy",
	"bleyshon",
	"blomeysel",
	"blova",
	"blovat",
	"blovon",
	"bloza",
	"blūshor",
	"bolon",
	"boreyv",
	"borogniy",
	"borot",
	"borots-orfak",
	"borots-vlaych",
	"borotsat",
	"bosenk",
	"boshat",
	"bosko",
	"boslat",
	"boslon",
	"bramat",
	"branzak",
	"brasliyvat",
	"brasliyvelov",
	"brasliyvon",
	"bratsa",
	"braykat",
	"brega",
	"brelen",
	"bresh",
	"breshat",
	"breyk",
	"breytat",
	"briyn",
	"brogadaskat",
	"brogadaskelov",
	"brolev",
	"brolev-seyrin",
	"bromin",
	"brost",
	"brosyat",
	"byezhat",
	"byolm",
	"byortomat",
	"būkat",
	"būkta-general",
	"būkta-markavo",
	"būnat",
	"chag",
	"chakat",
	"chamrat",
	"chamrelov",
	"chana",
	"chanenk",
	"chanenk-rlova",
	"chanta",
	"chasta",
	"chatat",
	"chats",
	"chazha",
	"cheklid",
	"chemikol",
	"chemikolniy porsk",
	"chemikolniy",
	"chenk",
	"chenkat",
	"chenskat",
	"chesk",
	"chevakat",
	"chobe",
	"choch",
	"choloskos",
	"chozniyka",
	"chyendat",
	"chūmo",
	"daga",
	"dagat",
	"dagon",
	"dakast",
	"dame",
	"damerat",
	"damero",
	"dan",
	"dan-neygen",
	"darga",
	"dasha",
	"daskon",
	"dast",
	"davekta",
	"davkat",
	"dekat",
	"delat",
	"delon",
	"dergat",
	"disk",
	"distinkish",
	"dob",
	"dom",
	"donar",
	"dorn",
	"dorolm",
	"dorolmatsol",
	"dosk",
	"dovat",
	"dovinat",
	"dozhaposka",
	"drak",
	"drasa",
	"drasat",
	"draselov",
	"drason",
	"drekenka",
	"drin",
	"drosel",
	"durst",
	"durst-linya",
	"durst-seyrin",
	"dursto",
	"dyatsat",
	"dyatson",
	"dyonomat",
	"dyonomelov",
	"dyot",
	"dyu",
	"dūtska",
	"dūzh",
	"egin",
	"ekemiv",
	"eksat",
	"ele",
	"ele-nov",
	"ele-yin",
	"eleytav",
	"elinar",
	"elmezh",
	"emertat",
	"enkankat",
	"enkar",
	"enkar-stolm",
	"enlūtar",
	"enlūtarat",
	"erat",
	"erentekat",
	"eron",
	"eskat",
	"etsa",
	"ev (1)",
	"ev (2)",
	"ev feydat",
	"evnen",
	"eykaz-vlaych",
	"eykazat",
	"eykazelov",
	"eyrin",
	"eysh",
	"ezhe",
	"fach",
	"fach-korust",
	"fadafiy nevesk",
	"fadat",
	"faralskat",
	"faralskelov",
	"farsk",
	"fazo",
	"fedat",
	"felgniy",
	"felpat ... ots stolyon",
	"felpat",
	"felpelov",
	"felpezhiy ots stolyon",
	"femel",
	"fenkat",
	"fernuska",
	"fetra",
	"feydon",
	"feykat",
	"feykon",
	"firtat",
	"fishat",
	"fistiyn",
	"flaba",
	"flezat",
	"flust",
	"fodin",
	"fogor",
	"fokat",
	"fokelov",
	"folpo",
	"fon",
	"for",
	"forda",
	"forkach",
	"formikat",
	"formikelov",
	"forn",
	"fornul",
	"forosh",
	"foroshat",
	"fortul",
	"fovta",
	"frastat",
	"frastelov",
	"fresenk",
	"freyna",
	"freynon",
	"freyshat",
	"freyshon",
	"frid",
	"fridat",
	"friyga",
	"friygat",
	"friygon",
	"fulga",
	"furkun",
	"furkunniy",
	"fushun",
	"fyadkaza",
	"fyerda (1)",
	"fyerda (2)",
	"fyeshon",
	"fyetsat",
	"fyezh",
	"fū",
	"fūmat",
	"fūmon",
	"fūshor",
	"fūskol",
	"galavat",
	"galavon",
	"galdar",
	"galon",
	"galv",
	"gardorn",
	"gazren",
	"gek",
	"geld",
	"gelenat",
	"gelenon",
	"general",
	"gim",
	"gitara",
	"giton",
	"gladat",
	"gladon",
	"glezat",
	"glezon",
	"glomat",
	"glunt",
	"gofal",
	"golfat",
	"golm",
	"golochas",
	"golpar",
	"gonom",
	"gor",
	"goreym",
	"gorin",
	"gorovolm",
	"gorst",
	"gosin",
	"goskon",
	"gosteyn",
	"goveyn",
	"goza",
	"gozhust",
	"gradanat",
	"gradandar",
	"gradanelov",
	"gralatin",
	"gram-seyrin",
	"gramat",
	"gramelov",
	"gredya",
	"grenk",
	"griyza",
	"griyzniy",
	"grold",
	"gunon",
	"gurk",
	"gyelat",
	"gyelon",
	"gyoch",
	"gūl",
	"gūnda",
	"gūndelov",
	"haln holova",
	"haln narin",
	"haln/halnas/halneys",
	"hamachat",
	"hamachelov",
	"hamachniy",
	"hamya",
	"hanakin",
	"harskat",
	"harskivolm",
	"harskivolmniy",
	"havandat",
	"hazak",
	"hazakniy porsk",
	"hazakniy",
	"heka",
	"hemreviyta",
	"heton",
	"hev",
	"heveskaniy",
	"heveskat",
	"heveskelov",
	"heviy",
	"hevya",
	"hezhok",
	"hilm",
	"hiska",
	"hiv",
	"hiynak",
	"hobrat",
	"holmat",
	"holmelov",
	"holova",
	"holvat",
	"horold",
	"horosha",
	"horoshat",
	"horoshe dom",
	"hos",
	"hosat",
	"hoselov",
	"hosor",
	"hot",
	"hotat",
	"hozha",
	"hurk",
	"hūgnavol",
	"hūva",
	"igezha",
	"ilgra",
	"illisin",
	"ireten",
	"isha-",
	"isha-gradano",
	"ishanosen seyrin",
	"isheym",
	"isik",
	"isobramezh",
	"istat yeltniy",
	"istat",
	"itan",
	"itevat",
	"itevon",
	"itevon-nosen",
	"izhek",
	"izhyat",
	"kachol-nakin",
	"Kagalar",
	"Kagalarlalg",
	"Kagalarniy",
	"Kagalaro",
	"kagra",
	"kamiy-gofal",
	"kanat",
	"kanelov",
	"kariyn",
	"karka",
	"karn",
	"kartira",
	"karzhen",
	"kastarkish",
	"katalizator",
	"katok",
	"katozh",
	"kavold",
	"kazar",
	"kechye",
	"kelink",
	"kelm",
	"keramik",
	"keravat",
	"keren",
	"ketsat",
	"kevlar",
	"kevmik-zhekal",
	"keyda",
	"keymor",
	"keynka",
	"keyrin",
	"kezhat",
	"khaf",
	"khafat",
	"khamat",
	"khamelov",
	"khan",
	"khanek",
	"khaton",
	"khenkat",
	"khenkelov",
	"kholta",
	"kiyna",
	"kiynat",
	"kiyta",
	"klabanat",
	"klan",
	"klan-zūsk",
	"klavon",
	"klest",
	"kliyzh",
	"kliyzhbosenk",
	"klobol",
	"kloda",
	"klodniy",
	"klodon",
	"kloma",
	"klosis",
	"klova",
	"klovat",
	"knab",
	"knaba",
	"kneska",
	"kniyga",
	"kniyga-dom",
	"kniza",
	"knopka",
	"knopka-dosk",
	"knorota",
	"knoto",
	"koda",
	"kodat",
	"kodosh",
	"kofregad",
	"kohel",
	"kol",
	"kolminar, kolm",
	"koloshem",
	"koltat",
	"komat",
	"komelov",
	"komnata",
	"korin",
	"korust",
	"koshan",
	"koshniy",
	"koslamat",
	"kosma",
	"kosoril",
	"kosvun",
	"kot",
	"kozhnok",
	"krasenk",
	"kraza",
	"krazat",
	"krelitsa",
	"krepniy",
	"krest",
	"krisnat",
	"kriysa",
	"kriysh",
	"krold",
	"krūch",
	"kulpa",
	"kūd",
	"kūdat",
	"kūdelov",
	"lagat",
	"lamk",
	"lanakelov",
	"lanakon",
	"lanikat",
	"latas",
	"lazoprak",
	"lemat",
	"lemeynat",
	"lemeynelov",
	"lenharsav",
	"leselat",
	"leszha",
	"leszhaniy",
	"leyrkat",
	"leyrkon",
	"lin",
	"linikav",
	"linya",
	"lis-nakin",
	"lisa",
	"liyda",
	"liydniy",
	"liynkun",
	"lizh",
	"lizhat",
	"lizhniy",
	"lodska",
	"logok",
	"lokat",
	"loko",
	"loloska",
	"loma",
	"lomisk",
	"lonk",
	"lonsa",
	"lopelat",
	"lorn",
	"lornul",
	"lorosil",
	"lorvet",
	"losik",
	"lot",
	"lovat",
	"lovmor",
	"lovo",
	"lozha",
	"lyakasin",
	"lyana",
	"lyon",
	"lyozh",
	"lūmenat",
	"lūmenelov",
	"lūnst",
	"lūsabat",
	"lūsabo",
	"lūsabon",
	"lūshat",
	"lūshelov",
	"lūsniy",
	"lūsomniy",
	"lūson",
	"lūtsat",
	"maglo-nakin",
	"maglonak",
	"maglopel",
	"makav-dast",
	"makta",
	"mamya",
	"manakon",
	"manaktaro",
	"mank",
	"manomovol",
	"manyerta",
	"mara",
	"marfreno",
	"markav",
	"markav-hot",
	"markav-kneska",
	"markavat",
	"markavo",
	"marnin",
	"maskara",
	"mazo",
	"medivala gūlus",
	"medivala",
	"melokara",
	"melskenat",
	"menak",
	"mert",
	"metonreyk",
	"mevol",
	"mevol-",
	"mevron",
	"meynat",
	"meyrn",
	"meyrn-hos",
	"mezhela",
	"miln narin",
	"miln/milnas/milneys",
	"milneys ta",
	"mina",
	"mishanat",
	"miy zhoglod",
	"miy",
	"miyka",
	"miyneyn",
	"miysh",
	"mlada",
	"mliyr",
	"mloko",
	"mlonor ordelg",
	"mlonor",
	"mlonor-nok",
	"mlordat",
	"mol",
	"moldat",
	"moldon",
	"molomba",
	"molosin",
	"moltun",
	"moltunniy pakfelpelov",
	"molzhat",
	"monot",
	"morigot",
	"morston",
	"mraka",
	"mrakelov",
	"mralat",
	"mrel",
	"mrel-antul",
	"mrelniy ravak",
	"mreynat",
	"mreynniy",
	"mrokek",
	"mroken",
	"mrolmat",
	"mrotiyn",
	"mrotiynniy",
	"myal",
	"myalkat",
	"myan",
	"myerosta",
	"myolomat",
	"myozhe",
	"myuta",
	"mūlenat",
	"mūva",
	"na",
	"nachkol",
	"nafrav",
	"nafrav-itan",
	"naganork",
	"naka",
	"nakin",
	"nalakish",
	"nalon",
	"nalva",
	"nalvat",
	"nalvelov",
	"nalvon",
	"napat",
	"napniy, napezhiy",
	"narin",
	"nasheta",
	"navek",
	"navekat",
	"nebin",
	"nebra",
	"nebradyu",
	"nevesk",
	"neya",
	"neygen",
	"nezat",
	"nezelov",
	"nina",
	"ninelov",
	"niska",
	"niska-",
	"niska-gramo",
	"niska-mazo",
	"niska-nova",
	"nogen",
	"nok",
	"nokar",
	"noklavin",
	"nolma",
	"nolskat",
	"nolskezhiy",
	"noltunniy",
	"noreyg",
	"noron",
	"nosen",
	"nosen-strakon",
	"nosenelov",
	"nosh",
	"nov ele",
	"nov eleyin",
	"nov",
	"noviy",
	"nyak",
	"nyakat",
	"nyakon",
	"nyeta",
	"nyezlat",
	"nūla",
	"obasna ahorstniy",
	"obasna",
	"oborsk",
	"odaka",
	"ofitsa",
	"oglaba",
	"oklenat",
	"oleym",
	"olezat",
	"olezelov",
	"olv-donar",
	"olv-mamya",
	"olva",
	"omenorst",
	"ona",
	"onayi",
	"onya",
	"ordelg",
	"ore",
	"oret",
	"orfak",
	"orgin",
	"ork",
	"orlak",
	"oroskiyna",
	"oroskiynon",
	"ot-",
	"ot-hamachat",
	"ot-hamachelov",
	"ot-lūshat",
	"otol",
	"ots",
	"ove",
	"ovetadar yadro",
	"ovetat",
	"ovetelov",
	"ovig",
	"ozhan",
	"ozhiy",
	"ozhoga",
	"padat",
	"pak",
	"pakosel",
	"pan",
	"partye",
	"paskenteyl",
	"pastak",
	"patya",
	"peltenat",
	"petika",
	"pil",
	"pivol",
	"plachatun",
	"pliystat",
	"pliznat",
	"plobskat",
	"plobskelov",
	"plomat",
	"plovatsol",
	"plumat",
	"plyenk",
	"pochka",
	"pod",
	"pod-svūsat",
	"pod-svūson",
	"poden",
	"pogladat",
	"poka",
	"pokniy",
	"pold-gofal",
	"poldat",
	"polem",
	"polma",
	"polmniy",
	"polmon",
	"polonye",
	"pomats",
	"pomol",
	"porin",
	"porsk",
	"posen",
	"posla",
	"posnek",
	"pot",
	"pozhamits",
	"pozhiy",
	"pozhno",
	"pramat",
	"pramon",
	"pranat",
	"print-gofal",
	"printat",
	"printso",
	"printsya",
	"priskat",
	"priygat",
	"promakat",
	"promakon",
	"provikat",
	"prozat",
	"pyekol",
	"pyestat",
	"pyestelov",
	"pyete",
	"pyotsa",
	"pūkat",
	"pūsk",
	"rach",
	"randa",
	"ravak",
	"redozhan",
	"refa",
	"rekonelov",
	"remor",
	"remor-hilm",
	"revetat",
	"reveton",
	"reya",
	"reydat",
	"reynk",
	"reynk-zhūkat",
	"reynk-zhūkon",
	"rimar",
	"rinol",
	"rish",
	"rishdyu",
	"riy",
	"riyminat",
	"riyschat",
	"riyscho",
	"rlem",
	"rleyka",
	"rleykon",
	"rleyton",
	"rliykor",
	"rlobat",
	"rlobelov",
	"rlorta",
	"rlotin",
	"rlova",
	"rlovaniy",
	"rlovano",
	"rlūmik",
	"ro",
	"rogevik",
	"rogo",
	"roka",
	"roltat",
	"romat",
	"ronk",
	"rosa",
	"roska",
	"roskat",
	"roteyn",
	"rov-losik",
	"rovat",
	"rovelov",
	"ruskūdat",
	"ruskūdon",
	"rūkan",
	"rūkat",
	"rūkelov",
	"rūvek",
	"saf",
	"sag",
	"salf",
	"salfniy",
	"saman",
	"sanva",
	"sarka",
	"sart",
	"saskar",
	"savadorn",
	"saveykat",
	"savlat",
	"savlelov",
	"sayron",
	"sbyaska",
	"sbyezhat",
	"sda",
	"sdama",
	"sden",
	"sdivat",
	"sdivon",
	"sdoba",
	"sdovalat",
	"sdūn",
	"sefat",
	"seleyka",
	"selkat",
	"semat",
	"sen",
	"seniy",
	"senya",
	"senzhakat",
	"sesk",
	"sevel",
	"sevenak",
	"seviyntikor",
	"seyrin",
	"seyshin",
	"seyta",
	"sezhren",
	"shablon",
	"shanokat",
	"shara",
	"sharaniy",
	"sharn",
	"shast",
	"shelm",
	"shelnat",
	"shem",
	"shemo",
	"sheynata",
	"sheynatahilm",
	"sheyvat",
	"sholosmat",
	"shorog",
	"shovikin",
	"sidat",
	"sifmūzhat",
	"sifmūzhelov",
	"sikol",
	"silarkish",
	"sinak",
	"sisaka",
	"sisako",
	"siymya",
	"siyn",
	"skacha",
	"skafan",
	"skakna",
	"skan",
	"skaton",
	"skazosat",
	"skazoselov",
	"skomat",
	"skorozat",
	"skozhyat",
	"slapa",
	"slapat",
	"slask ozhan neveskus",
	"slask",
	"slava",
	"slavniy",
	"slavon",
	"sliykat",
	"slyak",
	"slyenat",
	"smegat",
	"smidat",
	"smoterat",
	"snova",
	"sokovat",
	"soldat",
	"soler-seyrin",
	"solerat",
	"solerelov",
	"solma",
	"solmat",
	"solpar",
	"somrol",
	"somt",
	"somyenat",
	"soreyma",
	"sorkul",
	"sorn",
	"sozhe",
	"spaykat",
	"spaykon",
	"sperkat",
	"spistat",
	"spoklan",
	"sproskadar",
	"sproskat",
	"srakat",
	"srakelov-zona",
	"srakon",
	"srima",
	"sriyk",
	"srokor",
	"srokor-flust",
	"srovin",
	"stachevat",
	"stalm",
	"statach",
	"stivol",
	"stodon",
	"stolchat",
	"stolm",
	"stolyat",
	"stolyon",
	"stonat",
	"storkan",
	"stoza",
	"stozhagniy",
	"strakat",
	"strakon",
	"sveyzat",
	"sveyzezhiy",
	"svinakniy",
	"svinyak",
	"svoloch",
	"svūkat",
	"svūko",
	"svūsat",
	"syar",
	"syer",
	"ta",
	"tab",
	"talgat",
	"tamok",
	"tamok-vedon",
	"tanakin",
	"tankat",
	"tankon",
	"tasen",
	"tasen-krūch",
	"tasin",
	"tasin-gūl",
	"tasnakin",
	"taspil",
	"tastanak",
	"tatsat",
	"tefrat",
	"tefron",
	"teleportat",
	"teleportelov",
	"temena",
	"terolm",
	"terolm-stolm",
	"terolmat",
	"teshen",
	"teviysat",
	"teviysla",
	"teviysniy",
	"teviyso",
	"teyn",
	"teynkat",
	"teynkelov",
	"teynkelov",
	"teynkelov-stolm",
	"teysol",
	"tiglon",
	"tirsk",
	"tirt",
	"tiv-ronk",
	"tiva",
	"tivesel",
	"to",
	"token",
	"topor",
	"tor",
	"tor-sikol",
	"tov",
	"toviy",
	"tovya",
	"treyvost",
	"treyvost-vedon",
	"trovakat",
	"trovakon",
	"tsakiyn",
	"tsazhyo",
	"tsema",
	"tsiyzha",
	"tsogniy",
	"tsūk",
	"tumrona",
	"tyevelm",
	"tyevesat",
	"tyezha",
	"tūshemol",
	"tūvigen",
	"uldelov",
	"uldo",
	"ulsinan",
	"uu",
	"va zhokle zhoglod",
	"va",
	"vakazh",
	"vam",
	"vampir",
	"vanar",
	"vanko",
	"variyn",
	"vark",
	"vark-mazo",
	"vas",
	"vatsavat",
	"vatsavelov",
	"vedon",
	"vemezhat",
	"vemezho",
	"venat",
	"vendar",
	"venya",
	"venya-tivesel",
	"verat",
	"vereta",
	"vernzat",
	"vidniy",
	"viltav",
	"vinova",
	"virikozhan",
	"viskat",
	"viskon",
	"vlachya",
	"vladat",
	"vladelov",
	"vlado",
	"vlan",
	"vlaych",
	"vlebin",
	"vlebta",
	"vleyshat ta stolm",
	"vleyshat",
	"vleyshon",
	"vlika",
	"vlind",
	"vlo va fyadkaza",
	"vlo",
	"vlom",
	"vloma",
	"vlonorik",
	"vlorn",
	"vlorniy",
	"vlunst",
	"vlunstsikol",
	"vlyevlir",
	"vnyertiyak",
	"vodrin",
	"vok",
	"vok-gofal",
	"voldat",
	"voldon",
	"volfak",
	"volfakniy",
	"volikor",
	"volnok",
	"volt",
	"voltat",
	"volzhun",
	"vomeygerat",
	"vorgat",
	"vorgon",
	"vosha",
	"vosta",
	"vovik",
	"voyyakol",
	"vralat",
	"vrash",
	"vriynat",
	"vta",
	"vtir",
	"vtiyn",
	"vtyesh",
	"vtūn",
	"vya",
	"vyela",
	"vyen",
	"vyo",
	"vūka",
	"vūtat",
	"yad",
	"yadro",
	"yameyga",
	"yanon",
	"yasha",
	"yatsat",
	"yatsiy",
	"yav",
	"yav-etsa",
	"yeda",
	"yegol",
	"yegta",
	"yekya",
	"yela",
	"yelon",
	"yelta",
	"yenda",
	"yerikomat",
	"yerikomelov",
	"yetsat",
	"yev",
	"yezha",
	"yibik",
	"yigala",
	"yikin",
	"yin",
	"yinforn",
	"yirk",
	"yisiy-gofal",
	"yiska",
	"yisko",
	"yiterator",
	"yiv",
	"yofeln",
	"yolen",
	"yom",
	"yonon",
	"yotat",
	"yus-itevat",
	"yus-itevelov",
	"yusa",
	"yuselov korust",
	"yuselov",
	"zamorozat",
	"zamsel",
	"zast",
	"zava",
	"zavakon",
	"zavakonniy",
	"zhaken",
	"zhakot",
	"zhalat",
	"zhalgniy",
	"zhanholva",
	"zhanholvat",
	"zhayka",
	"zhaykat",
	"zhebat",
	"zhekal",
	"zhelb",
	"zhem",
	"zhem-prozas",
	"zhem-soleras",
	"zhemniy azadar",
	"zhenerev",
	"zhenrūk",
	"zhentorom",
	"zherat",
	"zheron",
	"zhesat",
	"zhevanat",
	"zhireyk",
	"zhiva",
	"zhiysniy",
	"zhogladya",
	"zhoglod",
	"zhokla",
	"zhokla-seyrin",
	"zholon",
	"zholvun, -mūt",
	"zholvun-vedon",
	"zhonosk",
	"zhonya",
	"zhorol",
	"zhovoma",
	"zhrenat",
	"zhrenelov",
	"zhromalar",
	"zhūkat",
	"zhūkon",
	"zikren",
	"zima",
	"zin",
	"ziynak",
	"ziynak-fushun",
	"zlamkat",
	"zlapat",
	"zlapelov",
	"zlapo",
	"zlobra",
	"zlomat",
	"zloy",
	"zlyatold",
	"znagat",
	"znomo",
	"zombye",
	"zona",
	"zoron",
	"zotol",
	"zotolniy",
	"zyetoda",
	"zyezh",
	"zyezhat",
	"zyezhniy",
	"zyob",
	"zyovola",
	"zūla",
	"zūlat",
	"zūlelov",
	"zūsk",
	"ūkdunat",
	"ūkdunelov",
	"ūkelin",
	"ūnū-",
	"ūnū-ariyka",
	"ūnū-mrotiynniy",
	"ūnū-ofitsa",
	"ūra",
	"ūsin",
	"ūsin-",
	"ūsin-tivesel",
	"ūskeyd",
];

const entries = {
	"-arvil": ["suffix", "suffix for worlds, universes, planets, etc"],
	"-dar": ["suffix", "forms gerund nouns from verbs; forms language names"],
	"-elov": ["suffix", "forms abstract nouns from verbs"],
	"-lalg": ["suffix", "forms language names"],
	"-niy": ["suffix", "forms adjectives from verbs, nouns"],
	"-o": ["suffix", "agent suffix; forms agent nouns from verbs"],
	"agelovor": ["noun", "factory"],
	"agent": ["noun", "agent"],
	"agentelov": ["noun", "agency"],
	"aglen": ["noun", "tree"],
	"agralamk": ["noun", "science"],
	"ahakat": ["verb", "to impale, to penetrate, to pierce"],
	"ahandat": ["verb", "to surprise"],
	"ahekerol": ["noun", "humanoid"],
	"ahorst": ["noun", "lust"],
	"ahorstat": ["verb", "to lust after, to have an intense sexual desire for"],
	"ahorstniy": ["adjective", "horny"],
	"akiv-stolm": ["noun", "bunker, safe house"],
	"akivat": ["verb", "to secure, to make safe; to clear an area of enemies"],
	"akivelov": ["noun", "security, defense"],
	"akūla": ["adjective", "aqua (color)"],
	"alan": ["adverb-preposition", "up, upwards"],
	"aleyva": ["adverb", "early"],
	"alkor": ["noun", "alchoholic drink; wine, beer, ale, mead, gin, vodka, whiskey, etc"],
	"alskeym": ["noun", "capsule"],
	"an-yitevat": ["verb", "to beware, to watch out, to raise guard, to be careful"],
	"Anglesdar": ["noun", "English, english"],
	"anglokish": ["noun", "anglothite"],
	"antul": ["noun", "armor"],
	"arda": ["adjective", "red"],
	"ariyka": ["adjective", "possible"],
	"armank": ["noun", "armanite"],
	"arsenk": ["noun", "arsenium"],
	"arta": ["noun", "bullet, bolt of energy/material"],
	"avtita": ["adjective", "automatic"],
	"azadar": ["noun", "morning"],
	"azar": ["noun", "sun"],
	"azham": ["noun", "age"],
	"azleza": ["noun", "fame, reputation, renown"],
	"azlezaniy": ["adjective", "popular, famous"],
	"azorik": ["noun", "asteroid"],
	"bakov": ["noun", "trunk of vehicle"],
	"balbag": ["noun", "fox"],
	"balfat": ["verb", "to die to, to succumb to (with \"ev\" + object)"],
	"bamat": ["verb", "to leave, to depart"],
	"barat": ["verb", "to bring, to take"],
	"bast": ["noun", "bow (weapon)"],
	"bazand": ["noun", "train"],
	"beldat": ["verb", "to relax, to rest"],
	"belekiyvadar": ["noun", "marriage, wedding"],
	"belekiyvat": ["verb", "to marry someone"],
	"belekiyvelov": ["noun", "marriage, wedlock"],
	"belok": ["noun", "rabbit"],
	"belor": ["noun", "thigh"],
	"biy obasna": ["verb", "to be the same"],
	"biy vlebta volfak": ["verb", "to be in danger"],
	"biy": ["verb", "to be; is, am, are, be (past tense: biyt)"],
	"biyzhem": ["interjection", "please (contraction of \"biy zhem\")"],
	"bizagat": ["verb", "to zap, to electrocute, to induce with lightning"],
	"blavonat": ["verb", "to behave well"],
	"blavonon": ["noun", "manners, etiquette"],
	"bleniy": ["adjective", "nice, kind, friendly"],
	"bleyshon": ["noun", "town"],
	"blomeysel": ["noun", "necklace, amulet"],
	"blova": ["adjective", "hot"],
	"blovat": ["verb", "to heat, to warm, to make hot"],
	"blovon": ["noun", "heat"],
	"bloza": ["noun", "shirt"],
	"blūshor": ["noun", "robe, robes"],
	"bolon": ["noun", "pain"],
	"boreyv": ["noun", "friend"],
	"borogniy": ["adjective", "bitter"],
	"borot": ["noun", "beard"],
	"borots-orfak": ["noun", "martial art"],
	"borots-vlaych": ["noun", "spacefighter, jet fighter, starfighter (ship)"],
	"borotsat": ["verb", "to fight"],
	"bosenk": ["noun", "ladder"],
	"boshat": ["verb", "to sneak, to creep, to lurk"],
	"bosko": ["noun", "boy"],
	"boslat": ["verb", "to let, to allow, to permit; to make someone do something (with object (who) + verb infinitive (to do what))"],
	"boslon": ["verb", "permit, license"],
	"bramat": ["verb", "to open"],
	"branzak": ["noun", "billion"],
	"brasliyvat": ["verb", "to curse, to put a curse on, to damn"],
	"brasliyvelov": ["verb", "damnation, curse"],
	"brasliyvon": ["noun", "curse"],
	"bratsa": ["noun", "bone"],
	"braykat": ["verb", "to control, to manipulate"],
	"brega": ["noun", "crow, raven"],
	"brelen": ["noun", "glass"],
	"bresh": ["noun", "smile, grin"],
	"breshat": ["verb", "to smile, to grin"],
	"breyk": ["noun", "gate"],
	"breytat": ["verb", "to pull"],
	"briyn": ["noun", "village"],
	"brogadaskat": ["verb", "to become fermented, to undergo fermentation, to ferment"],
	"brogadaskelov": ["verb", "fermentation"],
	"brolev": ["noun", "battle"],
	"brolev-seyrin": ["noun", "destroyer"],
	"bromin": ["noun", "bromine"],
	"brost": ["noun", "breast, bosom"],
	"brosyat": ["verb", "to help, to assist"],
	"byezhat": ["verb", "to run, to sprint"],
	"byolm": ["noun", "bottle, jar"],
	"byortomat": ["verb", "to barricade, to block a pathway"],
	"būkat": ["verb", "to make"],
	"būkta-general": ["noun", "high general"],
	"būkta-markavo": ["noun", "high commander"],
	"būnat": ["verb", "to complete, to finish"],
	"chag": ["noun", "shit, crap"],
	"chakat": ["verb", "to hurry, to quicken"],
	"chamrat": ["verb", "to experiment, to test"],
	"chamrelov": ["noun", "experiment, test"],
	"chana": ["noun", "wing"],
	"chanenk": ["noun", "human"],
	"chanenk-rlova": ["noun", "mankind, humans"],
	"chanta": ["noun", "battery, energy cell, energy weapon battery"],
	"chasta": ["adjective", "private, personal"],
	"chatat": ["verb", "to talk, to chat, to have a conversation with"],
	"chats": ["noun", "spice"],
	"chazha": ["noun", "hour"],
	"cheklid": ["noun", "chainmail, maille"],
	"chemikol": ["noun", "chemical mixture"],
	"chemikolniy porsk": ["noun", "chemsuit, chemical suit; a full-body suit designed to protect the wearer from chemicals"],
	"chemikolniy": ["adjective", "chemical"],
	"chenk": ["noun", "chain"],
	"chenkat": ["verb", "to bind with chains, to chain; to repeat one after another; to repeat after, to follow after"],
	"chenskat": ["verb", "to shake"],
	"chesk": ["noun", "ink"],
	"chevakat": ["verb", "to cleave, to sever, to cut, to chop"],
	"chobe": ["noun", "puppy, dog"],
	"choch": ["noun", "derogatory insult directed to women; slut, thot"],
	"choloskos": ["noun", "chlorine"],
	"chozniyka": ["noun", "school, academy"],
	"chyendat": ["verb", "to be really fond of, to crush on, to be infatuated with"],
	"chūmo": ["noun", "alien, extraterrestrial creature"],
	"daga": ["adjective", "strong"],
	"dagat": ["verb", "to strengthen"],
	"dagon": ["noun", "strength"],
	"dakast": ["noun", "dakasti, dakastus (monster, undead)"],
	"dame": ["noun", "lady"],
	"damerat": ["verb", "to cook"],
	"damero": ["noun", "a cook"],
	"dan": ["noun", "hand"],
	"dan-neygen": ["noun", "flashlight, torch"],
	"darga": ["adjective", "black"],
	"dasha": ["noun", "spear"],
	"daskon": ["noun", "harbor, docking bay"],
	"dast": ["noun", "reason, goal"],
	"davekta": ["adjective", "different"],
	"davkat": ["verb", "to happen"],
	"dekat": ["verb", "to wear, to don"],
	"delat": ["verb", "to do, to act"],
	"delon": ["verb", "deed, action"],
	"dergat": ["verb", "to masturbate"],
	"disk": ["noun", "piece, fragment, part"],
	"distinkish": ["noun", "distinite"],
	"dob": ["noun", "bar of metal"],
	"dom": ["noun", "house, home"],
	"donar": ["noun", "father"],
	"dorn": ["noun", "north"],
	"dorolm": ["noun", "radio"],
	"dorolmatsol": ["noun", "radiation"],
	"dosk": ["noun", "board"],
	"dovat": ["verb", "to stop, to halt; to stop someone (with \"mol\" + from what)"],
	"dovinat": ["verb", "to remove, to take off"],
	"dozhaposka": ["noun", "chart, diagram"],
	"drak": ["noun", "weather"],
	"drasa": ["adjective", "wide"],
	"drasat": ["verb", "to widen, to expand"],
	"draselov": ["noun", "width, expansion"],
	"drason": ["noun", "width"],
	"drekenka": ["adjective", "nasty, disgusting"],
	"drin": ["adjective", "left direction (indeclinable)"],
	"drosel": ["noun", "reactor, generator"],
	"durst": ["noun", "war"],
	"durst-linya": ["noun", "front lines, combat zone"],
	"durst-seyrin": ["noun", "warship, any ship used for war"],
	"dursto": ["noun", "warrior, fighter"],
	"dyatsat": ["verb", "to hope"],
	"dyatson": ["verb", "hope, wish, want"],
	"dyonomat": ["verb", "to disintegrate, to turn into dust"],
	"dyonomelov": ["noun", "disintegration"],
	"dyot": ["adjective", "bad"],
	"dyu": ["noun", "day, day cycle"],
	"dūtska": ["noun", "feces, poop"],
	"dūzh": ["noun", "word"],
	"egin": ["noun", "salt"],
	"ekemiv": ["noun", "grenade"],
	"eksat": ["verb", "to exite"],
	"ele": ["adjective", "all, every (indeclinable)"],
	"ele-nov": ["adverb", "never"],
	"ele-yin": ["adverb", "always"],
	"eleytav": ["noun", "amethyst"],
	"elinar": ["noun", "elinar"],
	"elmezh": ["noun", "ice"],
	"emertat": ["verb", "to like"],
	"enkankat": ["verb", "to reset, to refactor"],
	"enkar": ["noun", "disease, sickness"],
	"enkar-stolm": ["noun", "hospital"],
	"enlūtar": ["noun", "information"],
	"enlūtarat": ["verb", "to inform"],
	"erat": ["verb", "to hurt"],
	"erentekat": ["verb", "to enter, to go inside"],
	"eron": ["noun", "pipe"],
	"eskat": ["noun", "to carve, to etch"],
	"etsa": ["adjective", "other (indeclinable)"],
	"ev (1)": ["preposition", "caused by, because of, from; using a tool, with"],
	"ev (2)": ["article", "article to turn transitive verbs into intransitive verbs"],
	"ev feydat": ["verb", "to be born"],
	"evnen": ["interjection", "a greeting; hello, hi"],
	"eykaz-vlaych": ["noun", "interceptor"],
	"eykazat": ["verb", "to intercept, to interrupt"],
	"eykazelov": ["noun", "interception, interruption"],
	"eyrin": ["noun", "east"],
	"eysh": ["noun", "shield"],
	"ezhe": ["conjunction", "or"],
	"fach": ["noun", "data, info"],
	"fach-korust": ["noun", "document, file"],
	"fadafiy nevesk": ["noun", "nebula"],
	"fadat": ["verb", "to birth"],
	"faralskat": ["verb", "to deliver, to transport"],
	"faralskelov": ["noun", "deliverance, transportation"],
	"farsk": ["noun", "patrol"],
	"fazo": ["noun", "enemy, foe"],
	"fedat": ["verb", "to receive, to collect, to get, to gain"],
	"felgniy": ["adjective", "real"],
	"felpat ... ots stolyon": ["verb", "to incapacitate, to disable, to neutralise"],
	"felpat": ["verb", "to put, to place"],
	"felpelov": ["noun", "placement"],
	"felpezhiy ots stolyon": ["adjective", "incapacitated"],
	"femel": ["noun", "enchantom, elf"],
	"fenkat": ["verb", "to close"],
	"fernuska": ["noun", "energy, plasma"],
	"fetra": ["adjective", "pink"],
	"feydon": ["noun", "birth"],
	"feykat": ["verb", "to die"],
	"feykon": ["noun", "death"],
	"firtat": ["verb", "to tear, to rip apart"],
	"fishat": ["verb", "to feel, to touch"],
	"fistiyn": ["noun", "phystine"],
	"flaba": ["adverb", "away"],
	"flezat": ["verb", "to be fond of"],
	"flust": ["noun", "cell, ward, room"],
	"fodin": ["adverb", "now"],
	"fogor": ["noun", "base, root"],
	"fokat": ["verb", "to design, to model"],
	"fokelov": ["verb", "design, designation, model"],
	"folpo": ["noun", "hood"],
	"fon": ["noun", "phone"],
	"for": ["noun", "wire"],
	"forda": ["adjective", "blue"],
	"forkach": ["noun", "storm, tempest"],
	"formikat": ["verb", "to generate, to make from nothing"],
	"formikelov": ["verb", "generation, creation"],
	"forn": ["adverb", "forward, ahead"],
	"fornul": ["noun", "front (noun)"],
	"forosh": ["noun", "warp, fast travel, long distance jump"],
	"foroshat": ["verb", "to warp"],
	"fortul": ["noun", "finger"],
	"fovta": ["adjective", "dry"],
	"frastat": ["verb", "to prepare, to ready"],
	"frastelov": ["verb", "preparation"],
	"fresenk": ["noun", "fresenite"],
	"freyna": ["adjective", "long"],
	"freynon": ["noun", "length"],
	"freyshat": ["verb", "to kick"],
	"freyshon": ["noun", "kick"],
	"frid": ["adverb-preposition", "past"],
	"fridat": ["verb", "to pass"],
	"friyga": ["adjective", "cold"],
	"friygat": ["verb", "to cool, to chill, to make cold"],
	"friygon": ["noun", "cold (noun)"],
	"fulga": ["adjective", "evil, bad"],
	"furkun": ["noun", "symbol, icon, logo"],
	"furkunniy": ["adjective", "iconic, classic; legendary, renowned"],
	"fushun": ["noun", "powder"],
	"fyadkaza": ["noun", "bullshit"],
	"fyerda (1)": ["adverb", "first"],
	"fyerda (2)": ["adjective", "first (indeclinable)"],
	"fyeshon": ["noun", "peace, quiet, still, calm"],
	"fyetsat": ["verb", "to throw"],
	"fyezh": ["noun", "fish"],
	"fū": ["interjection", "ew, disgusted interjection (interjection)"],
	"fūmat": ["verb", "to smell"],
	"fūmon": ["noun", "smell, aroma, odor"],
	"fūshor": ["noun", "oven"],
	"fūskol": ["noun", "cheese"],
	"galavat": ["verb", "to sing"],
	"galavon": ["noun", "song"],
	"galdar": ["verb", "cauldron, pot"],
	"galon": ["noun", "rubber"],
	"galv": ["noun", "weight"],
	"gardorn": ["noun", "decoration, jewelry, jewellery, ornament, cosmetic, makeup"],
	"gazren": ["noun", "apple"],
	"gek": ["noun", "fletched arrow"],
	"geld": ["noun", "letter, rune, glyph"],
	"gelenat": ["verb", "to shout, to yell"],
	"gelenon": ["noun", "shout, yell"],
	"general": ["noun", "general"],
	"gim": ["numeral", "five"],
	"gitara": ["noun", "guitar"],
	"giton": ["noun", "shadow"],
	"gladat": ["verb", "to work (with labor), to run, to execute"],
	"gladon": ["noun", "job, occupication, work"],
	"glezat": ["verb", "to test, to examine, to evaluate; to test ability, intelligence, or skill"],
	"glezon": ["noun", "test, examination, quiz, questioning"],
	"glomat": ["verb", "to boil"],
	"glunt": ["noun", "gear, cogwheel"],
	"gofal": ["noun", "machine"],
	"golfat": ["verb", "to glow"],
	"golm": ["noun", "cave"],
	"golochas": ["noun", "intestines, bowel"],
	"golpar": ["noun", "crowd, throng"],
	"gonom": ["noun", "cosmic void"],
	"gor": ["numeral", "four"],
	"goreym": ["noun", "engine"],
	"gorin": ["noun", "month"],
	"gorovolm": ["noun", "furnace"],
	"gorst": ["noun", "liquid"],
	"gosin": ["noun", "overcoat"],
	"goskon": ["noun", "soup"],
	"gosteyn": ["noun", "minute"],
	"goveyn": ["noun", "hill"],
	"goza": ["noun", "ball, sphere"],
	"gozhust": ["noun", "us fl oz, fluid ounce"],
	"gradanat": ["verb", "to govern"],
	"gradandar": ["adjective", "governmental, federal, imperial, sovereign (indeclinable)"],
	"gradanelov": ["noun", "government"],
	"gralatin": ["noun", "graltite"],
	"gram-seyrin": ["noun", "carrier ship"],
	"gramat": ["verb", "to move"],
	"gramelov": ["verb", "movement"],
	"gredya": ["noun", "daughter"],
	"grenk": ["noun", "stone, rock"],
	"griyza": ["noun", "mold, mould, mold fungus"],
	"griyzniy": ["adjective", "moldy"],
	"grold": ["noun", "mace, club"],
	"gunon": ["noun", "linen"],
	"gurk": ["noun", "natural oil"],
	"gyelat": ["verb", "to steal"],
	"gyelon": ["noun", "theft"],
	"gyoch": ["noun", "wood"],
	"gūl": ["noun", "year"],
	"gūnda": ["adjective", "weak, feeble, powerless; faint, slight"],
	"gūndelov": ["noun", "weakness"],
	"haln holova": ["noun", "deep space"],
	"haln narin": ["noun", "long range"],
	"haln/halnas/halneys": ["adverb", "far/farther/farthest"],
	"hamachat": ["verb", "to activate, to turn on, to switch on"],
	"hamachelov": ["noun", "activation"],
	"hamachniy": ["adjective", "active"],
	"hamya": ["noun", "music"],
	"hanakin": ["noun", "airlock"],
	"harskat": ["verb", "to explode"],
	"harskivolm": ["noun", "explosion"],
	"harskivolmniy": ["adjective", "explosive, exploding, combustive, volatile"],
	"havandat": ["verb", "to cover"],
	"hazak": ["noun", "hazard"],
	"hazakniy porsk": ["noun", "hazmat suit, hazardous materials suit; a full-body suit designed to protect the wearer from chemicals, biohazards, radiation, and other things"],
	"hazakniy": ["adjective", "hazardous"],
	"heka": ["adjective", "dirty, unclean, not clean"],
	"hemreviyta": ["adjective", "attractive, sexy"],
	"heton": ["noun", "group, type, kind, sort"],
	"hev": ["pronoun", "1st person plural nominative"],
	"heveskaniy": ["adjective", "effective, good, influencial"],
	"heveskat": ["verb", "to affect, to change, to influence"],
	"heveskelov": ["noun", "affection"],
	"heviy": ["pronoun", "1st person plural genitive"],
	"hevya": ["pronoun", "1st person plural accusative"],
	"hezhok": ["noun", "cannon"],
	"hilm": ["noun", "room"],
	"hiska": ["noun", "wall"],
	"hiv": ["noun", "light"],
	"hiynak": ["noun", "heart"],
	"hobrat": ["verb", "to hug, to embrace"],
	"holmat": ["verb", "to support, to assist"],
	"holmelov": ["noun", "assistance"],
	"holova": ["noun", "outer space, cosmic space"],
	"holvat": ["verb", "to shake, to shudder, to shiver"],
	"horold": ["noun", "mage, wizard, sorcerer, magic user"],
	"horosha": ["adjective", "safe, secure, okay"],
	"horoshat": ["verb", "to make safe; to relieve, to sooth"],
	"horoshe dom": ["noun", "safe house, hidden outpost"],
	"hos": ["noun", "grip, handle"],
	"hosat": ["verb", "to hold, to have"],
	"hoselov": ["noun", "grip, holding"],
	"hosor": ["noun", "glove"],
	"hot": ["noun", "side"],
	"hotat": ["verb", "to lift"],
	"hozha": ["noun", "pig, boar, hog"],
	"hurk": ["noun", "arm"],
	"hūgnavol": ["noun", "lava, magma"],
	"hūva": ["adjective", "visible"],
	"igezha": ["adjective", "immune, unaffected"],
	"ilgra": ["adjective", "yellow"],
	"illisin": ["noun", "illisinion"],
	"ireten": ["noun", "tundra, snowy plains"],
	"isha-": ["prefix", "anti, against, versus"],
	"isha-gradano": ["noun", "insurgent, rebel"],
	"ishanosen seyrin": ["noun", "anti-infantry warship"],
	"isheym": ["noun", "mean, meaning of"],
	"isik": ["noun", "smart, intelligent"],
	"isobramezh": ["noun", "image, picture"],
	"istat yeltniy": ["verb", "to be gullible, to be easily fooled (\"Istafna yeltniy?\" = \"Do you think I'm stupid?\")"],
	"istat": ["verb", "to seem like, to look like (with \"ozhan\" + object)"],
	"itan": ["noun", "tip, top, ending"],
	"itevat": ["verb", "to see; to look (with \"ta\" + object)"],
	"itevon": ["noun", "scenery, sight"],
	"itevon-nosen": ["noun", "guard, guardian, protector, defender"],
	"izhek": ["noun", "skill"],
	"izhyat": ["verb", "to turn on"],
	"kachol-nakin": ["noun", "a trillion meters, 1,000,000 kilometers"],
	"Kagalar": ["noun", "Kagalar"],
	"Kagalarlalg": ["noun", "Kagalarian language"],
	"Kagalarniy": ["adjective", "Kagalarian, relating to Kagalar"],
	"Kagalaro": ["noun", "Kagalarian, citizen of Kagalar"],
	"kagra": ["adjective", "spicy"],
	"kamiy-gofal": ["noun", "detector"],
	"kanat": ["verb", "to explore, to venture"],
	"kanelov": ["noun", "exploration"],
	"kariyn": ["noun", "ship, vessel"],
	"karka": ["noun", "hull, shell"],
	"karn": ["noun", "edge"],
	"kartira": ["noun", "an apartment"],
	"karzhen": ["noun", "gadget, trinket, unknown thing"],
	"kastarkish": ["noun", "quastarine"],
	"katalizator": ["noun", "potion base, brewing base, catalyst"],
	"katok": ["noun", "staff, stick, pole"],
	"katozh": ["noun", "turret, mounted gun"],
	"kavold": ["noun", "honor, honour"],
	"kazar": ["noun", "emperor"],
	"kechye": ["noun", "penis, male reproductive organs"],
	"kelink": ["noun", "container"],
	"kelm": ["noun", "crown, helmet"],
	"keramik": ["noun", "ceramic"],
	"keravat": ["verb", "to kiss"],
	"keren": ["noun", "surcoat, tabard"],
	"ketsat": ["verb", "to wait"],
	"kevlar": ["noun", "kevlar"],
	"kevmik-zhekal": ["noun", "kevlar-ceramic vest"],
	"keyda": ["adjective", "being fat"],
	"keymor": ["noun", "king, emperor"],
	"keynka": ["noun", "excuse"],
	"keyrin": ["noun", "galaxy"],
	"kezhat": ["verb", "to crouch, to sneak"],
	"khaf": ["noun", "woof, bark (interjection)"],
	"khafat": ["verb", "to bark"],
	"khamat": ["verb", "to detect"],
	"khamelov": ["noun", "detection"],
	"khan": ["noun", "student, apprentice, learner"],
	"khanek": ["noun", "virus"],
	"khaton": ["noun", "solar system"],
	"khenkat": ["verb", "to contain, to have"],
	"khenkelov": ["noun", "containment"],
	"kholta": ["adjective", "freezing cold"],
	"kiyna": ["adjective", "brave, bold, courageous"],
	"kiynat": ["verb", "to add, to join"],
	"kiyta": ["adjective", "light in weight"],
	"klabanat": ["verb", "to call, to summon"],
	"klan": ["noun", "clan"],
	"klan-zūsk": ["noun", "tribe"],
	"klavon": ["noun", "concrete"],
	"klest": ["noun", "fang"],
	"kliyzh": ["noun", "cell (biology)"],
	"kliyzhbosenk": ["noun", "dna"],
	"klobol": ["noun", "table"],
	"kloda": ["adjective", "fast, quick"],
	"klodniy": ["adverb", "quickly, hastily"],
	"klodon": ["noun", "speed"],
	"kloma": ["adjective", "weird"],
	"klosis": ["noun", "golem"],
	"klova": ["adjective", "hard"],
	"klovat": ["verb", "to harden"],
	"knab": ["noun", "bread"],
	"knaba": ["noun", "sandwich, burger"],
	"kneska": ["noun", "mission, assignment"],
	"kniyga": ["noun", "book"],
	"kniyga-dom": ["noun", "library"],
	"kniza": ["adjective", "sharp"],
	"knopka": ["noun", "button; key (on a keyboard)"],
	"knopka-dosk": ["noun", "keyboard"],
	"knorota": ["noun", "corporation, company"],
	"knoto": ["noun", "someone"],
	"koda": ["adjective", "some, unknown amount"],
	"kodat": ["verb", "to turn off"],
	"kodosh": ["noun", "bug, insect"],
	"kofregad": ["noun", "an elemental"],
	"kohel": ["noun", "kohl (black makeup thing)"],
	"kol": ["noun", "coal"],
	"kolminar, kolm": ["noun", "hand radio, walkie talkie, handheld transceiver"],
	"koloshem": ["noun", "lightning"],
	"koltat": ["verb", "to save, to rescue"],
	"komat": ["verb", "to use"],
	"komelov": ["noun", "purpose, usage, use"],
	"komnata": ["noun", "room, chamber, lodgings, dwelling, apartment"],
	"korin": ["noun", "korin"],
	"korust": ["noun", "paper"],
	"koshan": ["noun", "horse"],
	"koshniy": ["adjective", "interesting"],
	"koslamat": ["verb", "to cuss, to swear"],
	"kosma": ["noun", "neshozic orc"],
	"kosoril": ["noun", "world"],
	"kosvun": ["noun", "fight, combat"],
	"kot": ["noun", "cat"],
	"kozhnok": ["noun", "bettle"],
	"krasenk": ["noun", "thunder, sound of lightning"],
	"kraza": ["noun", "fire"],
	"krazat": ["verb", "to set fire to (with \"pan\" + object); to fire a weapon, to shoot (intransitive)"],
	"krelitsa": ["noun", "the cyrillic script"],
	"krepniy": ["adjective", "sturdy, strong, durable; defended, impervious"],
	"krest": ["noun", "chest, breast"],
	"krisnat": ["verb", "to blush, to fluster"],
	"kriysa": ["noun", "rat"],
	"kriysh": ["noun", "crystal, gem"],
	"krold": ["noun", "lawn, garden"],
	"krūch": ["noun", "chest, box, kist"],
	"kulpa": ["noun", "sick"],
	"kūd": ["noun", "mud, dirt, grime, slop"],
	"kūdat": ["verb", "to defile, to make dirty, to violate"],
	"kūdelov": ["noun", "defilement, violation"],
	"lagat": ["verb", "to speak, to talk; to say, to tell (with \"ta\" + clause)"],
	"lamk": ["noun", "reason, cause of"],
	"lanakelov": ["noun", "alliance, allegiance"],
	"lanakon": ["noun", "ally, allied side, helping side"],
	"lanikat": ["verb", "to shine, to direct a light towards"],
	"latas": ["noun", "beam, bolt of lightning, laser (general term)"],
	"lazoprak": ["noun", "laboratory, room where scientific experiments are performed"],
	"lemat": ["verb", "to read"],
	"lemeynat": ["verb", "to build"],
	"lemeynelov": ["noun", "building, establishment, place, stead"],
	"lenharsav": ["noun", "fortification"],
	"leselat": ["verb", "to cry, to weep"],
	"leszha": ["adjective", "soft"],
	"leszhaniy": ["adverb", "softly"],
	"leyrkat": ["verb", "to connect, to link, to attach (with \"vlebta\" + object)"],
	"leyrkon": ["noun", "physical link, connection, or bond"],
	"lin": ["noun", "rice"],
	"linikav": ["noun", "shop, store"],
	"linya": ["noun", "line"],
	"lis-nakin": ["noun", "centimetre, centimeter"],
	"lisa": ["adjective", "small"],
	"liyda": ["adjective", "easy"],
	"liydniy": ["adverb", "easily"],
	"liynkun": ["noun", "portal, wormhole"],
	"lizh": ["noun", "lie, deceit"],
	"lizhat": ["verb", "to lie"],
	"lizhniy": ["adjective", "false, deceitful, ingenuine, lying"],
	"lodska": ["noun", "boat, rowboat, dinghy"],
	"logok": ["noun", "drink, beverage"],
	"lokat": ["verb", "to drink"],
	"loko": ["noun", "ally, teammate"],
	"loloska": ["noun", "breast, bosom, boob, tit (slang)"],
	"loma": ["noun", "bed"],
	"lomisk": ["noun", "air tank, gas tank"],
	"lonk": ["noun", "hall, hallway"],
	"lonsa": ["adjective", "sour"],
	"lopelat": ["verb", "to circle, to surround, to go around, to loop"],
	"lorn": ["adverb", "backward"],
	"lornul": ["noun", "back (noun)"],
	"lorosil": ["noun", "circlet, crown"],
	"lorvet": ["noun", "land, ground"],
	"losik": ["noun", "station, outpost"],
	"lot": ["adverb", "just, only, merely"],
	"lovat": ["verb", "to operate, to handle, to use, to drive"],
	"lovmor": ["noun", "leader"],
	"lovo": ["noun", "operator, driver, crewmember"],
	"lozha": ["adjective", "false, incorrect, wrong"],
	"lyakasin": ["noun", "language"],
	"lyana": ["adjective", "bright, shining"],
	"lyon": ["noun", "snow"],
	"lyozh": ["noun", "0.1 fluid ounces, 0.1 fl oz"],
	"lūmenat": ["verb", "to learn"],
	"lūmenelov": ["noun", "knowledge"],
	"lūnst": ["noun", "garbage, trash"],
	"lūsabat": ["verb", "to love"],
	"lūsabo": ["noun", "lover, significant other"],
	"lūsabon": ["noun", "love"],
	"lūshat": ["verb", "to obey"],
	"lūshelov": ["noun", "obedience"],
	"lūsniy": ["adjective", "sad"],
	"lūsomniy": ["adjective", "sorry"],
	"lūson": ["noun", "sorrow"],
	"lūtsat": ["verb", "to speak a language; to talk about (with \"ozhan\" + object)"],
	"maglo-nakin": ["noun", "a million meters, 1000 kilometers, standard unit of mesurement in space, especially with warships"],
	"maglonak": ["noun", "million"],
	"maglopel": ["noun", "ton, 1000 kilograms, 1000000 grams"],
	"makav-dast": ["noun", "task, objective, goal"],
	"makta": ["adjective", "magenta"],
	"mamya": ["noun", "mother"],
	"manakon": ["noun", "enemy, foe, adversary, opposing side"],
	"manaktaro": ["noun", "villain"],
	"mank": ["noun", "gear, equipment"],
	"manomovol": ["noun", "hotel, inn"],
	"manyerta": ["noun", "manners, behaviour"],
	"mara": ["adjective", "brown"],
	"marfreno": ["noun", "marfrenic people"],
	"markav": ["noun", "command"],
	"markav-hot": ["noun", "team, side"],
	"markav-kneska": ["noun", "given mission, military operation"],
	"markavat": ["verb", "to command, to order"],
	"markavo": ["noun", "commander"],
	"marnin": ["noun", "marnine"],
	"maskara": ["noun", "mascara"],
	"mazo": ["noun", "man, male"],
	"medivala gūlus": ["noun", "medieval ages, middle ages"],
	"medivala": ["adjective", "medieval (indeclinable)"],
	"melokara": ["adjective", "gorgeous, beautiful"],
	"melskenat": ["verb", "to approach, to arrive, to enter location"],
	"menak": ["noun", "cloned human, clone"],
	"mert": ["noun", "meat, flesh"],
	"metonreyk": ["noun", "poison"],
	"mevol": ["noun", "head"],
	"mevol-": ["adjective", "main, primary, central"],
	"mevron": ["noun", "module, addon, extension"],
	"meynat": ["verb", "to be able to"],
	"meyrn": ["noun", "weapon"],
	"meyrn-hos": ["noun", "weapon grip, weapon handle"],
	"mezhela": ["noun", "female reproductive organ"],
	"miln narin": ["noun", "short/close range"],
	"miln/milnas/milneys": ["adverb", "near/nearer/nearest"],
	"milneys ta": ["preposition", "next to, beside, by"],
	"mina": ["noun", "lamp"],
	"mishanat": ["verb", "to appear"],
	"miy zhoglod": ["interjection", "surprise interjection, meaning \"oh my god\", \"my god\", and other variants"],
	"miy": ["pronoun", "1st person singular genitive"],
	"miyka": ["adjective", "many, much, a lot"],
	"miyneyn": ["noun", "story, tale"],
	"miysh": ["noun", "mouse"],
	"mlada": ["noun", "blood"],
	"mliyr": ["noun", "glue"],
	"mloko": ["noun", "milk"],
	"mlonor ordelg": ["noun", "meteoroid; a small piece of space rock from the original asteroid/meteor; space debris"],
	"mlonor": ["noun", "meteor; the visible streak when an asteroid/meteoroid falls"],
	"mlonor-nok": ["noun", "meteorite; space rock that landed"],
	"mlordat": ["verb", "to destroy, to crumble"],
	"mol": ["preposition", "from"],
	"moldat": ["verb", "to form, to mold"],
	"moldon": ["noun", "form, shape"],
	"molomba": ["noun", "nanopus (monster)"],
	"molosin": ["noun", "cow, cattle"],
	"moltun": ["noun", "power, strength, might"],
	"moltunniy pakfelpelov": ["noun", "emplacement, machine gun placement"],
	"molzhat": ["verb", "to carry"],
	"monot": ["noun", "floor"],
	"morigot": ["noun", "morigalt"],
	"morston": ["noun", "planet"],
	"mraka": ["adjective", "dark, murk, gloom"],
	"mrakelov": ["noun", "darkness, murkiness, blackness"],
	"mralat": ["verb", "to give, to grant"],
	"mrel": ["noun", "energy, power"],
	"mrel-antul": ["noun", "power armor"],
	"mrelniy ravak": ["noun", "plasma rifle"],
	"mreynat": ["verb", "to burn"],
	"mreynniy": ["adjective", "damned, cursed"],
	"mrokek": ["noun", "mrokek"],
	"mroken": ["noun", "mroken"],
	"mrolmat": ["verb", "to rub"],
	"mrotiyn": ["noun", "comfort"],
	"mrotiynniy": ["adjective", "comfortable"],
	"myal": ["noun", "meow (noun, interjection)"],
	"myalkat": ["verb", "to meow"],
	"myan": ["adverb", "very, really (used for the verb itself)"],
	"myerosta": ["adjective", "common"],
	"myolomat": ["verb", "to moan"],
	"myozhe": ["adverb", "might, maybe"],
	"myuta": ["adjective", "shy, timid"],
	"mūlenat": ["verb", "to teach"],
	"mūva": ["noun", "leg"],
	"na": ["pronoun", "1st person singular nominative"],
	"nachkol": ["noun", "evil (noun)"],
	"nafrav": ["noun", "missile"],
	"nafrav-itan": ["noun", "warhead"],
	"naganork": ["noun", "dragon, wyvern"],
	"naka": ["noun", "foot, feet"],
	"nakin": ["noun", "meter"],
	"nalakish": ["noun", "nalastite"],
	"nalon": ["noun", "animal"],
	"nalva": ["adjective", "high"],
	"nalvat": ["verb", "to raise, to increase"],
	"nalvelov": ["noun", "increment"],
	"nalvon": ["noun", "height"],
	"napat": ["verb", "to fill"],
	"napniy, napezhiy": ["adjective", "filled, full"],
	"narin": ["noun", "distance, range"],
	"nasheta": ["noun", "cloth"],
	"navek": ["noun", "name"],
	"navekat": ["verb", "to name, to call, to make known as; to be called (with \"ta\" + object)"],
	"nebin": ["noun", "belly, stomach, bowel"],
	"nebra": ["adjective", "next"],
	"nebradyu": ["adverb", "tomorrow"],
	"nevesk": ["noun", "star"],
	"neya": ["pronoun", "1st person singular accusative"],
	"neygen": ["noun", "lightbulb, led, light"],
	"nezat": ["verb", "to need, to require"],
	"nezelov": ["noun", "requirement"],
	"nina": ["adjective", "dark, dim"],
	"ninelov": ["noun", "darkness, shadow"],
	"niska": ["noun", "magic, superhuman power"],
	"niska-": ["prefix", "super-"],
	"niska-gramo": ["noun", "telekinesis"],
	"niska-mazo": ["noun", "magician"],
	"niska-nova": ["noun", "supernova"],
	"nogen": ["noun", "pistol (gun)"],
	"nok": ["numeral", "zero"],
	"nokar": ["noun", "controller, driving wheel, joystick"],
	"noklavin": ["noun", "fortress, castle, military base"],
	"nolma": ["noun", "mineral, metal, crystal"],
	"nolskat": ["verb", "to lose, to lack"],
	"nolskezhiy": ["adjective", "lost, missing"],
	"noltunniy": ["adjective", "powerful, mighty, strong"],
	"noreyg": ["noun", "mountain"],
	"noron": ["noun", "number, count, amount"],
	"nosen": ["noun", "soldier, troop, infantry"],
	"nosen-strakon": ["noun", "ptsd, post-traumatic stress disorder"],
	"nosenelov": ["noun", "army, ground force"],
	"nosh": ["noun", "nose"],
	"nov ele": ["adverb", "not always, not every one"],
	"nov eleyin": ["adverb", "not always, not all the time"],
	"nov": ["adverb", "not, negator"],
	"noviy": ["adjective", "modern, new age"],
	"nyak": ["interjection", "a cuss word"],
	"nyakat": ["verb", "to hate"],
	"nyakon": ["noun", "hate"],
	"nyeta": ["adjective", "empty, desolate, deserted"],
	"nyezlat": ["verb", "to lick"],
	"nūla": ["adjective", "beautiful, pretty"],
	"obasna ahorstniy": ["adjective", "erotic, sexually pleasing"],
	"obasna": ["adjective", "same, equal"],
	"oborsk": ["noun", "potato"],
	"odaka": ["adjective", "blunt, not sharp"],
	"ofitsa": ["adjective", "official, formal"],
	"oglaba": ["noun", "trouble, problem"],
	"oklenat": ["verb", "to fix, to repair"],
	"oleym": ["noun", "circle"],
	"olezat": ["verb", "to enjoy, to take pleasure in"],
	"olezelov": ["noun", "enjoyment"],
	"olv-donar": ["noun", "grandfather, grandpa"],
	"olv-mamya": ["noun", "grandmother, grandma"],
	"olva": ["adjective", "old"],
	"omenorst": ["noun", "divination, future sight"],
	"ona": ["pronoun", "3rd person feminine nominative"],
	"onayi": ["pronoun", "3rd person feminine genitive"],
	"onya": ["pronoun", "3rd person feminine accusative"],
	"ordelg": ["noun", "pebble, small rock"],
	"ore": ["noun", "cooking oil"],
	"oret": ["adverb-preposition", "out, outside"],
	"orfak": ["noun", "art"],
	"orgin": ["noun", "mouth"],
	"ork": ["noun", "ogre, orc, monster (monster)"],
	"orlak": ["noun", "money, dollar, orlak, imperial kagalarian currency"],
	"oroskiyna": ["verb", "to warn"],
	"oroskiynon": ["noun", "warning"],
	"ot-": ["prefix", "opposite for verbs"],
	"ot-hamachat": ["verb", "to deactivate, to turn off, to switch off"],
	"ot-hamachelov": ["noun", "deactivation"],
	"ot-lūshat": ["verb", "to disobey, to defy"],
	"otol": ["noun", "opposite"],
	"ots": ["adverb-preposition", "off"],
	"ove": ["noun", "ear"],
	"ovetadar yadro": ["noun", "reactor, generator (formal)"],
	"ovetat": ["verb", "to respond"],
	"ovetelov": ["noun", "response, reaction"],
	"ovig": ["noun", "bird"],
	"ozhan": ["preposition", "of; about, around, somewhere near"],
	"ozhiy": ["conjunction", "and"],
	"ozhoga": ["adjective", "ugly"],
	"padat": ["verb", "to poke, to tap"],
	"pak": ["noun", "gun, rifle, pistol"],
	"pakosel": ["noun", "appearance, looks"],
	"pan": ["adverb-preposition", "on"],
	"partye": ["noun", "party, feast, social gathering"],
	"paskenteyl": ["noun", "cylinder"],
	"pastak": ["noun", "baldric, sling"],
	"patya": ["noun", "bucket, can"],
	"peltenat": ["verb", "to study, to research"],
	"petika": ["noun", "chicken"],
	"pil": ["noun", "a gram, 1 gram"],
	"pivol": ["noun", "beer, ale"],
	"plachatun": ["noun", "century, 100 years"],
	"pliystat": ["verb", "to pick, to pluck"],
	"pliznat": ["verb", "to spark, to stir"],
	"plobskat": ["verb", "to bore, to be bored"],
	"plobskelov": ["noun", "boredom"],
	"plomat": ["verb", "to fall"],
	"plovatsol": ["noun", "prototype, an invented thing that is still in testing/being tested"],
	"plumat": ["verb", "to soak, to drench (with \"vyen\" + object (in what))"],
	"plyenk": ["noun", "makeup, make-up, beauty products"],
	"pochka": ["adjective", "dear"],
	"pod": ["adverb-preposition", "under"],
	"pod-svūsat": ["verb", "to sign"],
	"pod-svūson": ["noun", "signature"],
	"poden": ["noun", "noon"],
	"pogladat": ["verb", "to pet, to caress, to soothe"],
	"poka": ["adjective", "rough, hard"],
	"pokniy": ["adverb", "roughly, recklessly (adverb)"],
	"pold-gofal": ["noun", "scanner"],
	"poldat": ["verb", "to scan"],
	"polem": ["noun", "cloak"],
	"polma": ["adjective", "slow"],
	"polmniy": ["adverb", "slowly, sluggishly"],
	"polmon": ["adjective", "slowness"],
	"polonye": ["noun", "emotion, expression"],
	"pomats": ["noun", "west"],
	"pomol": ["noun", "tower"],
	"porin": ["noun", "past (time)"],
	"porsk": ["noun", "suit, full body suit"],
	"posen": ["noun", "gas"],
	"posla": ["adjective", "middle"],
	"posnek": ["noun", "solid"],
	"pot": ["noun", "sweat"],
	"pozhamits": ["noun", "chemise, frock, undergarment"],
	"pozhiy": ["adjective", "cute, sweet, pretty"],
	"pozhno": ["adverb", "late"],
	"pramat": ["verb", "to prove"],
	"pramon": ["noun", "proof"],
	"pranat": ["verb", "to repeat"],
	"print-gofal": ["noun", "printer"],
	"printat": ["verb", "to print, to write (with a printer)"],
	"printso": ["noun", "prince"],
	"printsya": ["noun", "princess"],
	"priskat": ["verb", "to practice, to train"],
	"priygat": ["verb", "to jump"],
	"promakat": ["verb", "to assume, to suppose, to guess"],
	"promakon": ["noun", "assumption, guess"],
	"provikat": ["verb", "to punch"],
	"prozat": ["verb", "to come"],
	"pyekol": ["noun", "chair"],
	"pyestat": ["verb", "to annoy, to bother, to irritate"],
	"pyestelov": ["noun", "irritation"],
	"pyete": ["noun", "pet, domesticated animal"],
	"pyotsa": ["noun", "hip"],
	"pūkat": ["verb", "to scare"],
	"pūsk": ["noun", "buttocks, butt, bum, ass"],
	"rach": ["noun", "lever, switch"],
	"randa": ["noun", "moon"],
	"ravak": ["noun", "rifle (gun)"],
	"redozhan": ["noun", "reedian (furry)"],
	"refa": ["adjective", "difficult, hard"],
	"rekonelov": ["noun", "reconnaissance"],
	"remor": ["noun", "relief"],
	"remor-hilm": ["noun", "bathroom, restroom, public bathroom"],
	"revetat": ["verb", "to have sexual intercourse, to fuck"],
	"reveton": ["noun", "sexual intercourse"],
	"reya": ["pronoun", "2nd person singular accusative"],
	"reydat": ["verb", "to drop"],
	"reynk": ["noun", "class, rank, role"],
	"reynk-zhūkat": ["verb", "to roleplay, to act (intransitive or with \"ozhan\" + object (as what))"],
	"reynk-zhūkon": ["noun", "roleplay"],
	"rimar": ["noun", "window, visor"],
	"rinol": ["noun", "ghost, spirit"],
	"rish": ["adjective", "previous, last (indeclinable)"],
	"rishdyu": ["adverb", "yesterday"],
	"riy": ["pronoun", "2nd person singular genitive"],
	"riyminat": ["verb", "to realise"],
	"riyschat": ["verb", "to ride"],
	"riyscho": ["noun", "knight"],
	"rlem": ["noun", "tongue"],
	"rleyka": ["noun", "car"],
	"rleykon": ["noun", "vehicle"],
	"rleyton": ["noun", "crew"],
	"rliykor": ["noun", "faction"],
	"rlobat": ["verb", "to free"],
	"rlobelov": ["noun", "freedom, liberty"],
	"rlorta": ["adjective", "poor"],
	"rlotin": ["adjective", "right direction (indeclinable)"],
	"rlova": ["noun", "kin, kinship, kind, race, species"],
	"rlovaniy": ["adjective", "native, aboriginal, indigenous"],
	"rlovano": ["noun", "native, resident, inhabitant"],
	"rlūmik": ["noun", "medicine"],
	"ro": ["pronoun", "2nd person singular nominative"],
	"rogevik": ["noun", "robot"],
	"rogo": ["noun", "bandit, thug"],
	"roka": ["noun", "structure, frame"],
	"roltat": ["verb", "to tilt, to become lopsided"],
	"romat": ["verb", "to walk"],
	"ronk": ["noun", "boot"],
	"rosa": ["noun", "rose"],
	"roska": ["adjective", "heavy in weight"],
	"roskat": ["verb", "to find, to search"],
	"roteyn": ["noun", "rule, law"],
	"rov-losik": ["noun", "checkpoint"],
	"rovat": ["verb", "to check, to inspect"],
	"rovelov": ["noun", "inspection"],
	"ruskūdat": ["verb", "to rape, to sexually assault"],
	"ruskūdon": ["noun", "rape, sexual assault"],
	"rūkan": ["noun", "debris, rubble, crumbled pieces"],
	"rūkat": ["verb", "to describe"],
	"rūkelov": ["noun", "description"],
	"rūvek": ["noun", "spell, rune"],
	"saf": ["noun", "leaf"],
	"sag": ["noun", "knife, dagger, dirk"],
	"salf": ["noun", "health"],
	"salfniy": ["adjective", "healthy"],
	"saman": ["adverb", "enough"],
	"sanva": ["noun", "character, avatar, person"],
	"sarka": ["adjective", "rare, scarce"],
	"sart": ["noun", "grass"],
	"saskar": ["numeral", "seven"],
	"savadorn": ["noun", "dictionary"],
	"saveykat": ["verb", "to scream"],
	"savlat": ["verb", "to analyze (analyse), to examine, to inspect, to study; to analyse data or output"],
	"savlelov": ["noun", "analysis, examination, inspection"],
	"sayron": ["noun", "flag"],
	"sbyaska": ["noun", "beach, strand, coast, shore"],
	"sbyezhat": ["verb", "to escape"],
	"sda": ["conjunction", "if, whether, in case of"],
	"sdama": ["noun", "fork"],
	"sden": ["conjunction", "but, yet; still, after all"],
	"sdivat": ["verb", "to aim"],
	"sdivon": ["noun", "target"],
	"sdoba": ["noun", "pants"],
	"sdovalat": ["verb", "to send, to launch (with object (what) + \"ta\" + object (where))"],
	"sdūn": ["conjunction", "which (question word); who, whom, that"],
	"sefat": ["verb", "to thank"],
	"seleyka": ["adjective", "gray, grey"],
	"selkat": ["verb", "to rot"],
	"semat": ["verb", "to ought to be, to suppose to be (subjunctive = should be)"],
	"sen": ["pronoun", "3rd person masculine nominative"],
	"seniy": ["pronoun", "3rd person masculine genitive"],
	"senya": ["pronoun", "3rd person masculine accusative"],
	"senzhakat": ["verb", "to injure, to hurt, to wound, to maim"],
	"sesk": ["numeral", "six"],
	"sevel": ["noun", "water"],
	"sevenak": ["noun", "sea, ocean"],
	"seviyntikor": ["noun", "setting, configuration"],
	"seyrin": ["noun", "spacecraft, spaceship, ship"],
	"seyshin": ["noun", "terrain, land"],
	"seyta": ["adjective", "exotic, otherworldly"],
	"sezhren": ["noun", "meadows, grasslands"],
	"shablon": ["noun", "pattern, design"],
	"shanokat": ["verb", "to spy, to pry, to watch without being known"],
	"shara": ["noun", "metal"],
	"sharaniy": ["adjective", "metallic"],
	"sharn": ["noun", "iron"],
	"shast": ["adverb", "through"],
	"shelm": ["noun", "mask"],
	"shelnat": ["verb", "to sleep"],
	"shem": ["conjunction", "how"],
	"shemo": ["conjunction", "who"],
	"sheynata": ["noun", "rainy weather"],
	"sheynatahilm": ["noun", "bathroom, shower room"],
	"sheyvat": ["verb", "to care for, to nurture"],
	"sholosmat": ["verb", "to clean, to wash"],
	"shorog": ["noun", "shark"],
	"shovikin": ["noun", "future"],
	"sidat": ["verb", "to sit"],
	"sifmūzhat": ["verb", "to surrender, to give up"],
	"sifmūzhelov": ["noun", "surrender"],
	"sikol": ["noun", "cycle"],
	"silarkish": ["noun", "silartite"],
	"sinak": ["noun", "sign, signboard, mark, symbol"],
	"sisaka": ["adjective", "stupid, idiotic"],
	"sisako": ["noun", "idiot, stupid person (insult)"],
	"siymya": ["noun", "sister"],
	"siyn": ["conjunction", "then"],
	"skacha": ["noun", "brush"],
	"skafan": ["noun", "scabbard, sheath"],
	"skakna": ["noun", "sky"],
	"skan": ["adverb-preposition", "over"],
	"skaton": ["noun", "wound"],
	"skazosat": ["verb", "to concentrate, to focus"],
	"skazoselov": ["noun", "concentration, focus"],
	"skomat": ["verb", "to shoot a weapon; to shoot at (with \"ta\" + object)"],
	"skorozat": ["verb", "to crawl"],
	"skozhyat": ["verb", "to push"],
	"slapa": ["adjective", "weak, fragile, flabby"],
	"slapat": ["verb", "to weaken"],
	"slask ozhan neveskus": ["noun", "star cluster"],
	"slask": ["noun", "cluster, bunch"],
	"slava": ["adjective", "glorious"],
	"slavniy": ["adjective", "slavic"],
	"slavon": ["noun", "glory"],
	"sliykat": ["verb", "to lie down"],
	"slyak": ["noun", "snake, serpent"],
	"slyenat": ["verb", "to cut, to slice, to slit"],
	"smegat": ["verb", "to bet, to gamble"],
	"smidat": ["verb", "to take off, to doff"],
	"smoterat": ["verb", "to stare, to gaze at, to look intensely"],
	"snova": ["adverb", "again"],
	"sokovat": ["verb", "to sell"],
	"soldat": ["verb", "to tell someone"],
	"soler-seyrin": ["noun", "traveler, traveling ship (not a battleship)"],
	"solerat": ["verb", "to travel, to go (with \"ta\" + object)"],
	"solerelov": ["noun", "travelling, trip, trek"],
	"solma": ["adjective", "empty, vacant"],
	"solmat": ["verb", "to empty, to clear"],
	"solpar": ["noun", "sulfur, sulphur"],
	"somrol": ["noun", "night"],
	"somt": ["noun", "something, object"],
	"somyenat": ["verb", "to manufacture, to mechanically create/make"],
	"soreyma": ["adjective", "white"],
	"sorkul": ["noun", "sorkuls (monster)"],
	"sorn": ["adverb-preposition", "down, downwards"],
	"sozhe": ["noun", "sauce"],
	"spaykat": ["verb", "to anger"],
	"spaykon": ["noun", "anger, rage"],
	"sperkat": ["verb", "to stalk"],
	"spistat": ["verb", "to save, to spare"],
	"spoklan": ["noun", "message"],
	"sproskadar": ["noun", "question, query, asking"],
	"sproskat": ["verb", "to ask"],
	"srakat": ["verb", "to kill, to slay"],
	"srakelov-zona": ["noun", "kill zone"],
	"srakon": ["noun", "murder, killing"],
	"srima": ["adjective", "green"],
	"sriyk": ["noun", "claw, talon"],
	"srokor": ["noun", "prison, jail"],
	"srokor-flust": ["noun", "prison cell, jail cell"],
	"srovin": ["noun", "ritual, spellcasting"],
	"stachevat": ["verb", "to tow, to drag"],
	"stalm": ["noun", "belt"],
	"statach": ["noun", "speech"],
	"stivol": ["noun", "hat, headwear"],
	"stodon": ["noun", "hundred"],
	"stolchat": ["verb", "to combine, to add together"],
	"stolm": ["noun", "ground, the ground, land; place, location"],
	"stolyat": ["verb", "to stand"],
	"stolyon": ["noun", "stance, pose"],
	"stonat": ["verb", "to groan"],
	"storkan": ["noun", "building"],
	"stoza": ["adverb-preposition", "between"],
	"stozhagniy": ["adjective", "muscular"],
	"strakat": ["verb", "to fear, to be afraid of"],
	"strakon": ["noun", "fear of"],
	"sveyzat": ["verb", "to stick onto"],
	"sveyzezhiy": ["adjective", "stuck"],
	"svinakniy": ["adjective", "perverted"],
	"svinyak": ["noun", "pervert, creep"],
	"svoloch": ["noun", "bastard (insult)"],
	"svūkat": ["verb", "to serve"],
	"svūko": ["noun", "servant, server, maid, waiter"],
	"svūsat": ["verb", "to write"],
	"syar": ["adverb-preposition", "there"],
	"syer": ["adverb-preposition", "here"],
	"ta": ["adverb-preposition", "to, towards, at, till"],
	"tab": ["noun", "step (of a stair); a step of walking"],
	"talgat": ["verb", "to change, to alter, to modify"],
	"tamok": ["noun", "desert"],
	"tamok-vedon": ["noun", "desert camouflage"],
	"tanakin": ["noun", "square"],
	"tankat": ["verb", "to dance"],
	"tankon": ["noun", "dance"],
	"tasen": ["noun", "tool"],
	"tasen-krūch": ["noun", "toolbox, utility box"],
	"tasin": ["numeral", "ten"],
	"tasin-gūl": ["noun", "decade, 10 years"],
	"tasnakin": ["noun", "kilometer"],
	"taspil": ["noun", "kilogram, 1000 grams"],
	"tastanak": ["numeral", "thousand"],
	"tatsat": ["verb", "to tie a knot, to secure"],
	"tefrat": ["verb", "to try, to attempt"],
	"tefron": ["noun", "try, attempt"],
	"teleportat": ["verb", "to teleport"],
	"teleportelov": ["noun", "teleportation"],
	"temena": ["adjective", "rich"],
	"terolm": ["noun", "attack, assault"],
	"terolm-stolm": ["noun", "assault position, attack position, front line"],
	"terolmat": ["verb", "to attack, to assault"],
	"teshen": ["noun", "skin"],
	"teviysat": ["verb", "to watch"],
	"teviysla": ["adjective", "careful"],
	"teviysniy": ["adverb", "carefully"],
	"teviyso": ["noun", "spectator, watcher"],
	"teyn": ["noun", "second"],
	"teynkat": ["verb", "to protect, to defend"],
	"teynkelov": ["noun", "defense"],
	"teynkelov": ["noun", "protection, defense"],
	"teynkelov-stolm": ["noun", "defensive position, strongpoint, fallback position"],
	"teysol": ["noun", "peak, top, highest point, maximum"],
	"tiglon": ["noun", "lizard"],
	"tirsk": ["numeral", "three"],
	"tirt": ["noun", "cake"],
	"tiv-ronk": ["noun", "shoe"],
	"tiva": ["adjective", "short"],
	"tivesel": ["noun", "clothing, garment, apparel"],
	"to": ["adverb", "so, very (used with adjectives)"],
	"token": ["noun", "cube"],
	"topor": ["noun", "axe"],
	"tor": ["numeral", "two"],
	"tor-sikol": ["noun", "bicycle, bike"],
	"tov": ["pronoun", "3st person plural nominative"],
	"toviy": ["pronoun", "3st person plural genitive"],
	"tovya": ["pronoun", "3st person plural accusative"],
	"treyvost": ["noun", "forest"],
	"treyvost-vedon": ["noun", "forest camouflage"],
	"trovakat": ["verb", "to execute, to put to death"],
	"trovakon": ["noun", "execution, death sentence"],
	"tsakiyn": ["noun", "rest, remaining"],
	"tsazhyo": ["noun", "a thousand fluid ounces, 1000 fl oz"],
	"tsema": ["noun", "flower, bloom"],
	"tsiyzha": ["noun", "an inch"],
	"tsogniy": ["adjective", "rude, mean, unfriendly"],
	"tsūk": ["noun", "door"],
	"tumrona": ["adjective", "orange"],
	"tyevelm": ["noun", "game, sport"],
	"tyevesat": ["verb", "to sail, to row a boat"],
	"tyezha": ["noun", "honey"],
	"tūshemol": ["noun", "stew"],
	"tūvigen": ["noun", "system"],
	"uldelov": ["noun", "slavery"],
	"uldo": ["noun", "slave"],
	"ulsinan": ["noun", "ulsinan"],
	"uu": ["interjection", "uhh (interjection)"],
	"va zhokle zhoglod": ["interjection", "surprise interjection, meaning \"great god\", \"holy shit\", \"holy cow\", \"holy moly\", etc"],
	"va": ["article", "definite singular article"],
	"vakazh": ["noun", "tank"],
	"vam": ["conjunction", "than, compared to"],
	"vampir": ["noun", "vampire"],
	"vanar": ["numeral", "eight"],
	"vanko": ["noun", "brother"],
	"variyn": ["noun", "smoke"],
	"vark": ["noun", "wolf"],
	"vark-mazo": ["noun", "werewolf, wolfman"],
	"vas": ["article", "definite plural article"],
	"vatsavat": ["verb", "to summon, to conjure"],
	"vatsavelov": ["noun", "conjuration"],
	"vedon": ["noun", "camouflage"],
	"vemezhat": ["verb", "to invent"],
	"vemezho": ["noun", "inventor"],
	"venat": ["verb", "to wish"],
	"vendar": ["numeral", "nine"],
	"venya": ["adjective", "standard, default, common, uniform"],
	"venya-tivesel": ["noun", "uniform clothing"],
	"verat": ["verb", "to start"],
	"vereta": ["noun", "festival"],
	"vernzat": ["verb", "to return"],
	"vidniy": ["adjective", "bold, prominent, sticking out, different "],
	"viltav": ["noun", "alarm"],
	"vinova": ["adjective", "purple, violet"],
	"virikozhan": ["noun", "conquest, invasion"],
	"viskat": ["verb", "to militarise, to establish military force"],
	"viskon": ["noun", "military, force"],
	"vlachya": ["noun", "witch, hag"],
	"vladat": ["verb", "to own, to have"],
	"vladelov": ["noun", "ownage"],
	"vlado": ["noun", "master"],
	"vlan": ["conjunction", "why"],
	"vlaych": ["noun", "fighter, interceptor"],
	"vlebin": ["adverb", "together"],
	"vlebta": ["preposition", "together with (contraction of \"vlebin ta\")"],
	"vleyshat ta stolm": ["verb", "to land a spacecraft"],
	"vleyshat": ["verb", "to fly"],
	"vleyshon": ["noun", "flight"],
	"vlika": ["adjective", "wet"],
	"vlind": ["noun", "wine"],
	"vlo va fyadkaza": ["phrase", "what the hell, wtf (cuss)"],
	"vlo": ["conjunction", "what, which; to what extent"],
	"vlom": ["conjunction", "where"],
	"vloma": ["adjective", "more"],
	"vlonorik": ["noun", "technology"],
	"vlorn": ["noun", "warmth, heat"],
	"vlorniy": ["adjective", "warm"],
	"vlunst": ["noun", "motor"],
	"vlunstsikol": ["noun", "motorcycle, motorbike, dirt bike"],
	"vlyevlir": ["noun", "elevator, lift"],
	"vnyertiyak": ["noun", "hell"],
	"vodrin": ["noun", "week"],
	"vok": ["noun", "eye"],
	"vok-gofal": ["noun", "camera"],
	"voldat": ["verb", "to think"],
	"voldon": ["noun", "thought, opinion, impression, mind"],
	"volfak": ["noun", "danger"],
	"volfakniy": ["adjective", "dangerous"],
	"volikor": ["noun", "potion"],
	"volnok": ["noun", "volstone (monster, golem)"],
	"volt": ["noun", "defeat"],
	"voltat": ["verb", "to lose, to be defeated"],
	"volzhun": ["noun", "demon"],
	"vomeygerat": ["verb", "to disappear"],
	"vorgat": ["verb", "to invade"],
	"vorgon": ["noun", "invasion"],
	"vosha": ["noun", "evening"],
	"vosta": ["adjective", "big"],
	"vovik": ["noun", "bottle"],
	"voyyakol": ["noun", "navy, air force, space force"],
	"vralat": ["verb", "to follow, to go with"],
	"vrash": ["noun", "sword"],
	"vriynat": ["verb", "to take, to grab"],
	"vta": ["preposition", "for (with object); for the purpose of, to (with verb infinitive)"],
	"vtir": ["preposition", "after"],
	"vtiyn": ["conjunction", "when"],
	"vtyesh": ["preposition", "before"],
	"vtūn": ["conjunction", "while, whilst"],
	"vya": ["pronoun", "that, they, such"],
	"vyela": ["noun", "hair, fur"],
	"vyen": ["adverb-preposition", "in, inside, into; in a way"],
	"vyo": ["interjection", "no"],
	"vūka": ["adjective", "angry, mad"],
	"vūtat": ["verb", "to know, to understand"],
	"yad": ["interjection", "yes"],
	"yadro": ["noun", "core, heart, center"],
	"yameyga": ["noun", "gymnastics"],
	"yanon": ["noun", "sound, noise"],
	"yasha": ["noun", "gift, present"],
	"yatsat": ["verb", "to stick to"],
	"yatsiy": ["adjective", "sticky"],
	"yav": ["numeral", "one"],
	"yav-etsa": ["adjective", "another"],
	"yeda": ["noun", "food, meal"],
	"yegol": ["noun", "clay"],
	"yegta": ["adjective", "salty"],
	"yekya": ["noun", "candy"],
	"yela": ["adjective", "true, correct, right, truthful, legitimate, genuine"],
	"yelon": ["noun", "truth"],
	"yelta": ["adjective", "young"],
	"yenda": ["noun", "dress, gown"],
	"yerikomat": ["verb", "to remember"],
	"yerikomelov": ["noun", "remembrance"],
	"yetsat": ["verb", "to eat"],
	"yev": ["noun", "son"],
	"yezha": ["adjective", "sweet (taste)"],
	"yibik": ["noun", "coin"],
	"yigala": ["noun", "noodles"],
	"yikin": ["noun", "sugar"],
	"yin": ["noun", "time"],
	"yinforn": ["noun", "verb tense"],
	"yirk": ["noun", "worm"],
	"yisiy-gofal": ["noun", "computer"],
	"yiska": ["noun", "girl"],
	"yisko": ["noun", "maiden, a young unmarried woman, can also refer to a woman who is betrothed but not yet married"],
	"yiterator": ["noun", "iterator"],
	"yiv": ["noun", "river, stream"],
	"yofeln": ["noun", "cargo"],
	"yolen": ["noun", "computer chip, microchip, circuit board"],
	"yom": ["noun", "celsius (temperature)"],
	"yonon": ["noun", "temperature, heat"],
	"yotat": ["verb", "to want"],
	"yus-itevat": ["verb", "to discover"],
	"yus-itevelov": ["noun", "discovery"],
	"yusa": ["adjective", "new"],
	"yuselov korust": ["noun", "newspaper"],
	"yuselov": ["noun", "news, tidings, report"],
	"zamorozat": ["verb", "to freeze"],
	"zamsel": ["noun", "plan, strategy, intent"],
	"zast": ["noun", "sand"],
	"zava": ["adjective", "funny, hilarious"],
	"zavakon": ["noun", "empire, kingdom, nation, country, realm, reign"],
	"zavakonniy": ["adjective", "national, imperial"],
	"zhaken": ["noun", "taiga, snowy forest"],
	"zhakot": ["noun", "electricity"],
	"zhalat": ["verb", "to hail, to bow"],
	"zhalgniy": ["adjective", "important, critical"],
	"zhanholva": ["noun", "victory; also shouted as a kagalarian warcry"],
	"zhanholvat": ["verb", "to win"],
	"zhayka": ["noun", "pie, pastry"],
	"zhaykat": ["verb", "to bake"],
	"zhebat": ["verb", "to wait, to stay, to remain"],
	"zhekal": ["noun", "vest"],
	"zhelb": ["noun", "dirt"],
	"zhem": ["adjective", "good"],
	"zhem-prozas": ["phrase", "welcome"],
	"zhem-soleras": ["phrase", "goodbye"],
	"zhemniy azadar": ["phrase", "good morning"],
	"zhenerev": ["noun", "money, currency"],
	"zhenrūk": ["noun", "truck"],
	"zhentorom": ["noun", "assignment, essay, article"],
	"zherat": ["verb", "to listen, to hear"],
	"zheron": ["noun", "hearing"],
	"zhesat": ["verb", "to clean"],
	"zhevanat": ["verb", "to drive"],
	"zhireyk": ["noun", "laser (weapon), thin hot beam of light"],
	"zhiva": ["adjective", "tall"],
	"zhiysniy": ["adjective", "happy"],
	"zhogladya": ["noun", "goddess"],
	"zhoglod": ["noun", "god, deity"],
	"zhokla": ["adjective", "great, mighty"],
	"zhokla-seyrin": ["noun", "battleship, capital ship"],
	"zholon": ["noun", "territory"],
	"zholvun, -mūt": ["noun", "city"],
	"zholvun-vedon": ["noun", "urban camouflage"],
	"zhonosk": ["noun", "road, street"],
	"zhonya": ["noun", "woman, female"],
	"zhorol": ["noun", "wheel"],
	"zhovoma": ["adjective", "south"],
	"zhrenat": ["verb", "to buy, to purchase"],
	"zhrenelov": ["noun", "purchase"],
	"zhromalar": ["noun", "earth, exoplanet"],
	"zhūkat": ["verb", "to play"],
	"zhūkon": ["noun", "play (the act of playing); a play, opera, or performance"],
	"zikren": ["noun", "screen"],
	"zima": ["noun", "winter"],
	"zin": ["noun", "ginger"],
	"ziynak": ["noun", "bomb, explosive"],
	"ziynak-fushun": ["noun", "gunpowder, black powder"],
	"zlamkat": ["verb", "to stab, to stick in"],
	"zlapat": ["verb", "to commit a crime"],
	"zlapelov": ["noun", "crime"],
	"zlapo": ["noun", "criminal"],
	"zlobra": ["noun", "monster, unknown creature"],
	"zlomat": ["verb", "to slash, to cut, to hew"],
	"zloy": ["adjective", "evil, dark, grim (indeclinable)"],
	"zlyatold": ["noun", "trap"],
	"znagat": ["verb", "to capture, to take over"],
	"znomo": ["noun", "janitor"],
	"zombye": ["noun", "zombie"],
	"zona": ["noun", "place, area, zone"],
	"zoron": ["noun", "steel"],
	"zotol": ["noun", "gold"],
	"zotolniy": ["adjective", "gold, blond"],
	"zyetoda": ["noun", "lute"],
	"zyezh": ["noun", "life"],
	"zyezhat": ["verb", "to live"],
	"zyezhniy": ["adjective", "alive"],
	"zyob": ["noun", "bump, bulb, protruding extension"],
	"zyovola": ["noun", "lyre"],
	"zūla": ["adjective", "low"],
	"zūlat": ["verb", "to lower, to decrease"],
	"zūlelov": ["noun", "decrement"],
	"zūsk": ["noun", "group of people, party, company, throng, crowd"],
	"ūkdunat": ["verb", "to transform, to turn into, to change (with \"ta\" + object)"],
	"ūkdunelov": ["noun", "transformation"],
	"ūkelin": ["noun", "violin"],
	"ūnū-": ["prefix", "negator prefix"],
	"ūnū-ariyka": ["adjective", "impossible"],
	"ūnū-mrotiynniy": ["adjective", "uncomfortable"],
	"ūnū-ofitsa": ["adjective", "unofficial, informal"],
	"ūra": ["noun", "fire, ember, spark"],
	"ūsin": ["adverb", "often, frequently, many times; casually"],
	"ūsin-": ["prefix", "informal, casual"],
	"ūsin-tivesel": ["noun", "casual clothing, everyday clothing"],
	"ūskeyd": ["noun", "dog"],
};

const special_declensions = {};
