const word_type_short_form = {
	"noun": "n.",
	"adjective": "adj.",
	"adverb": "adv.",
	"verb": "v.",
	"conjunction": "c.",
	"phrase": "phr.",
	"onomatopeia": "on.",
	"expression": "exp.",
	"expression adverb": "expadv.",
	"interjection": "int.",
	"suffix": "suff.",
	"preposition": "pre.",
	"prefix": "pref.",
	"pronoun": "pron.",
	"auxiliary": "aux.",
	"numeral": "num."
};

const entry_words = [
	"-arvil",
	"-dar",
	"-elov",
	"-lalg",
	"-niy",
	"-o",
	"agelovor",
	"agent",
	"agentelov",
	"aglen",
	"agralamk",
	"ahakat",
	"ahandat",
	"ahekerol",
	"ahorst",
	"ahorstat",
	"ahorstniy",
	"ajam",
	"akiv-stolm",
	"akivat",
	"akivelov",
	"akūla",
	"alan",
	"aleyva",
	"alkor",
	"alskeym",
	"an-yitevat",
	"Anglesdar",
	"anglokish",
	"antul",
	"arda",
	"ariyka",
	"armank",
	"arsenk",
	"arta",
	"avtita",
	"azadar",
	"azar",
	"azleza",
	"azlezaniy",
	"azorik",
	"babūshka",
	"baka",
	"bakov",
	"balbag",
	"balfat",
	"bamat",
	"barat",
	"bast",
	"bazand",
	"beldat",
	"belekiyvadar",
	"belekiyvat",
	"belekiyvelov",
	"belok",
	"belor",
	"biy vlebta volfak",
	"biy",
	"bizagat",
	"blavonat",
	"bleniy",
	"bleyshon",
	"blomeysel",
	"blova",
	"blovat",
	"blovon",
	"blūshor",
	"bolon",
	"boreyv",
	"borod",
	"borogniy",
	"borotsa-vlaych",
	"borotsat",
	"borotsorfak",
	"bosenk",
	"boshat",
	"bosko",
	"boslat",
	"boslon",
	"bramat",
	"branzak",
	"brasliyvat",
	"brasliyvelov",
	"brasliyvon",
	"bratsa",
	"braykat",
	"brega",
	"brelen",
	"bresh",
	"breshat",
	"breyk",
	"breytat",
	"briyn",
	"brogadaskat",
	"brogadaskelov",
	"brolev",
	"brolev-seyrin",
	"bromin",
	"brost",
	"brosyat",
	"byejat",
	"byolm",
	"byortomat",
	"būkat",
	"būkta-general",
	"būkta-markavo",
	"būnat",
	"chag",
	"chaja",
	"chakat",
	"chamrat",
	"chamrelov",
	"chana",
	"chanenk",
	"chanenk-rlova",
	"chantol",
	"chasta",
	"chatat",
	"chats",
	"cheklid",
	"chemikol",
	"chemikolniy porsk",
	"chemikolniy",
	"chenk",
	"chenkat",
	"chenskat",
	"chesk",
	"chevakat",
	"chevelda",
	"chobe",
	"choch",
	"choloskos",
	"chozniyka",
	"chyendat",
	"chūmo",
	"daga",
	"dagat",
	"dagon",
	"dakast",
	"dame",
	"damerat",
	"damero",
	"dan",
	"dan-neygen",
	"darga",
	"dasha",
	"daskon",
	"dast",
	"davekta",
	"dedūshka",
	"dekat",
	"delat",
	"delon",
	"dergat",
	"disk",
	"distinkish",
	"dob",
	"dojaposka",
	"dom",
	"donar",
	"dorn",
	"dorolm",
	"dorolmatsol",
	"dosk",
	"dovat",
	"dovinat",
	"drak",
	"drasa",
	"drasat",
	"draselov",
	"drason",
	"drekenka",
	"drin",
	"drosel",
	"durst",
	"durst-linya",
	"durst-seyrin",
	"dursto",
	"dyatsat",
	"dyatson",
	"dyonomat",
	"dyonomelov",
	"dyot",
	"dyu",
	"dūj",
	"dūtska",
	"egin",
	"eje",
	"ekemiv",
	"eksat",
	"ele",
	"ele-yin",
	"eleytav",
	"elinar",
	"elmej",
	"emertat",
	"enkankat",
	"enkar",
	"enlūtar",
	"enlūtarat",
	"erat",
	"erentekat",
	"eron",
	"eskat",
	"etsa",
	"ev (1)",
	"ev (2)",
	"ev feydat",
	"evnen",
	"eykaza-vlaych",
	"eykazat",
	"eykazelov",
	"eyrin",
	"eysh",
	"fach",
	"fach-korust",
	"fadafiy nevesk",
	"fadat",
	"faralskat",
	"faralskelov",
	"farsk",
	"fedat",
	"felgniy",
	"felpat ... ots stoyi",
	"felpat",
	"felpejiy ots stoyi",
	"felpelov",
	"femel",
	"fenkat",
	"fernuska",
	"fetra",
	"feydon",
	"feykat",
	"feykon",
	"firtat",
	"fishat",
	"fistiyn",
	"flaba",
	"flezat",
	"flust",
	"fodin",
	"fogor",
	"fokat",
	"fokelov",
	"folpo",
	"for",
	"forda",
	"forkach",
	"formikat",
	"formikelov",
	"forn",
	"fornul",
	"forosh",
	"foroshat",
	"fortul",
	"fovta",
	"frastat",
	"frastelov",
	"fresenk",
	"freyna",
	"freynon",
	"freyshat",
	"freyshon",
	"frid",
	"fridat",
	"friyga",
	"friygat",
	"friygon",
	"fulga",
	"furkun",
	"furkunniy",
	"fushun",
	"fyada",
	"fyadkaza",
	"fyej",
	"fyerda (1)",
	"fyerda (2)",
	"fyeshon",
	"fyetsat",
	"fū",
	"fūmat",
	"fūmon",
	"fūshor",
	"fūskol",
	"gadren",
	"galavat",
	"galavon",
	"galdar",
	"galon",
	"galv",
	"gardorn",
	"gek",
	"geld",
	"gelenat",
	"gelenon",
	"general",
	"gim",
	"gitara",
	"giton",
	"gladat",
	"gladon",
	"glezat",
	"glezon",
	"glomat",
	"gofal",
	"gojest",
	"golfat",
	"golochas",
	"golpar",
	"gonom",
	"gor",
	"goreym",
	"gorin",
	"gorovolm",
	"gorst",
	"gosin",
	"goskon",
	"gosteyn",
	"goveyn",
	"goza",
	"gradanat",
	"gradandar",
	"gradanelov",
	"gralatin",
	"gramat",
	"gramdar-seyrin",
	"gramelov",
	"gredya",
	"grenk",
	"griyza",
	"griyzniy",
	"grold",
	"gulva",
	"gunon",
	"gurk",
	"gyelat",
	"gyelon",
	"gyoch",
	"gūl",
	"gūnda",
	"gūndelov",
	"haln holova",
	"haln narin",
	"haln/halnas/halneys",
	"hamachat",
	"hamachelov",
	"hamachniy",
	"hamya",
	"hanakin",
	"harskat",
	"harskivolm",
	"harskivolmniy",
	"havandat",
	"hazak",
	"hazakniy porsk",
	"hazakniy",
	"heka",
	"hemreviyta",
	"heton",
	"hev",
	"heveskaniy",
	"heveskat",
	"heveskelov",
	"heviy",
	"hevya",
	"heyjok",
	"hilm",
	"hiska",
	"hiv",
	"hiynak",
	"hobrat",
	"hoja",
	"holmat",
	"holmelov",
	"holova",
	"holvat",
	"horold",
	"horosha",
	"horoshat",
	"horoshe dom",
	"hos",
	"hosat",
	"hoselov",
	"hosor",
	"hotat",
	"hurk",
	"hūgnavol",
	"hūva",
	"igeja",
	"ijek",
	"ijyat",
	"ilgra",
	"illisin",
	"inshanosen seyrin",
	"ireten",
	"isha-",
	"isha-gradano",
	"isheym",
	"isik",
	"isobramej",
	"istat yeltniy",
	"istat",
	"itan",
	"itevat",
	"itevon",
	"itevon-nosen",
	"jaken",
	"jakot",
	"jalat",
	"jalgniy",
	"janholva",
	"janholvat",
	"jebat",
	"jelb",
	"jem",
	"jem-prozas",
	"jem-soleras",
	"jemniy azadar",
	"jenerev",
	"jenrūk",
	"jentorom",
	"jerat",
	"jeron",
	"jesat",
	"jevanat",
	"jireyk",
	"jiva",
	"jiysniy",
	"jogladya",
	"joglod",
	"jokla",
	"jokla-seyrin",
	"jolon",
	"jolvun, -mūt",
	"jolvun-vedon",
	"jonosk",
	"jonya",
	"jorol",
	"jovoma",
	"jrenat",
	"jrenelov",
	"jromalar",
	"jūkat",
	"jūkon",
	"kachol-nakin",
	"Kagalar",
	"Kagalarlalg",
	"Kagalaro",
	"kagra",
	"kamiy-gofal",
	"kariyn",
	"karjen",
	"karka",
	"karn",
	"kartira",
	"kastarkish",
	"katalizator",
	"katoj",
	"katokol",
	"kazar",
	"kechye",
	"kejat",
	"kelink",
	"kelm",
	"keravat",
	"keren",
	"ketsat",
	"keyda",
	"keymor",
	"keynka",
	"keyrin",
	"khaf",
	"khafat",
	"khamat",
	"khamelov",
	"khan",
	"khanek",
	"khaton",
	"khenkat",
	"khenkelov",
	"kholta",
	"kiyna",
	"kiynat",
	"kiyta",
	"klabanat",
	"klan",
	"klan-zūsk",
	"klavon",
	"klest",
	"kliyj",
	"kliyjbosenk",
	"klobol",
	"klod",
	"kloma",
	"klosis",
	"klova",
	"klovat",
	"knab",
	"knaba",
	"kneska",
	"kniyga",
	"kniyga-dom",
	"kniza",
	"knopka",
	"knopka-dosk",
	"knorota",
	"knoto",
	"koda",
	"kodat",
	"kodosh",
	"kofregad",
	"kohel",
	"kojnok",
	"kol",
	"kolminar, kolm",
	"koloshem",
	"koltat",
	"komat",
	"komelov",
	"komnata",
	"korin",
	"korust",
	"koshan",
	"koshniy",
	"koslamat",
	"kosma",
	"kosoril",
	"kosvun",
	"kot",
	"krasenk",
	"krelitsa",
	"krepniy",
	"krest",
	"krisnat",
	"kriysa",
	"kriysh",
	"krold",
	"krūch",
	"kūd",
	"kūdat",
	"kūdelov",
	"lagat",
	"lamk",
	"lanakon",
	"lanikat",
	"latas",
	"lazoprak",
	"lemat",
	"lemeynat",
	"lemeynelov",
	"len",
	"lenharsav",
	"leselat",
	"lesja",
	"lesjiy",
	"leyrkat",
	"leyrkon",
	"lij",
	"lija",
	"lijniy",
	"lin",
	"linikav",
	"linya",
	"lis-nakin",
	"lisa",
	"liyda",
	"liydiy",
	"liynkun",
	"lodska",
	"logok",
	"loja",
	"lokat",
	"loloska",
	"loma",
	"lomisk",
	"lomiyn",
	"lonsa",
	"lopelat",
	"lorn",
	"lornul",
	"lorosil",
	"lorvet",
	"losik",
	"lot",
	"lovat",
	"lovmor",
	"lovo",
	"lyakasin",
	"lyana",
	"lyoj",
	"lyon",
	"lūmenat",
	"lūmenelov",
	"lūnst",
	"lūsabat",
	"lūsabo",
	"lūsabon",
	"lūsniy",
	"lūsomniy",
	"lūson",
	"lūtsat",
	"maglo-nakin",
	"maglonak",
	"maglopel",
	"makav-dast",
	"makta",
	"mamya",
	"manakon",
	"manaktaro",
	"mank",
	"manomovol",
	"manyerta",
	"mara",
	"marfreno",
	"markav",
	"markav-kneska",
	"markavat",
	"markavo",
	"marnin",
	"maskara",
	"mazo",
	"medivala gūlus",
	"medivala",
	"mejela",
	"melokara",
	"melskenat",
	"menak",
	"mert",
	"metonreyk",
	"mevol",
	"mevol-",
	"mevron",
	"meynat",
	"meyrn",
	"meyrn-hos",
	"miln narin",
	"miln/milnas/milneys",
	"milneys ta",
	"mina",
	"mishanat",
	"miy joglod",
	"miy",
	"miyka",
	"miyneyn",
	"miysh",
	"mlada",
	"mliyr",
	"mloko",
	"mlonor ordelg",
	"mlonor",
	"mlonor-nok",
	"mlordat",
	"mol",
	"moldat",
	"moldon",
	"moljat",
	"molosin",
	"moltun",
	"moltunniy pakfelpelov",
	"molumba",
	"monot",
	"morigot",
	"morston",
	"mraka",
	"mrakelov",
	"mralat",
	"mrel",
	"mreynat",
	"mreynniy",
	"mrokek",
	"mroken",
	"mrolmat",
	"mrotiys",
	"mrotiysniy",
	"myal",
	"myalkat",
	"myan",
	"myerosta",
	"myoje",
	"myolomat",
	"myuta",
	"mūlenat",
	"mūva",
	"na",
	"nachkol",
	"nafrav",
	"nafrav-itan",
	"naganork",
	"naka",
	"nakin",
	"nalakish",
	"nalon",
	"nalva",
	"nalvat",
	"nalvelov",
	"nalvon",
	"napat",
	"napniy, napejiy",
	"narin",
	"nasheta",
	"navek",
	"navekat",
	"nebin",
	"nebra",
	"nebradyu",
	"nevesk",
	"neya",
	"neygen",
	"nezat",
	"nezelov",
	"nina",
	"ninelov",
	"niska",
	"niska-",
	"niska-gramo",
	"niska-nova",
	"nogen",
	"nok",
	"nokarish",
	"noklavin",
	"nolma",
	"noltunniy",
	"noreyg",
	"noron",
	"nosen",
	"nosen-strakon",
	"nosenelov",
	"nosh",
	"nov ele",
	"nov eleyin",
	"nov",
	"noviy",
	"nyak",
	"nyakat",
	"nyakon",
	"nyeta",
	"nyezlat",
	"nyoskat",
	"nyoskejiy",
	"nūla",
	"oborsk",
	"odaka",
	"ofitsa",
	"oglaba",
	"ojan",
	"ojiy",
	"ojoga",
	"oklenat",
	"oleym",
	"olezat",
	"olezelov",
	"olva",
	"omenorst",
	"ona",
	"onayi",
	"onya",
	"ordelg",
	"ore",
	"oret",
	"orfak",
	"orgin",
	"ork",
	"orkel",
	"orlak",
	"oroskiyna",
	"oroskiynon",
	"ot-",
	"ot-hamachat",
	"ot-hamachelov",
	"otol",
	"ots",
	"ove",
	"ovetadar yadro",
	"ovetat",
	"ovetelov",
	"ovig",
	"padat",
	"pak",
	"pakosel",
	"pakyab",
	"pan",
	"partye",
	"paskenteyl",
	"pastak",
	"pelik",
	"peltenat",
	"petika",
	"pil",
	"pivol",
	"plachatun",
	"pliznat",
	"plobskat",
	"plobskelov",
	"plomat",
	"ploviyatsol",
	"plyenk",
	"pochka",
	"pod",
	"pod-svūsat",
	"pod-svūson",
	"poden",
	"pogladat",
	"pojalūsta",
	"pojamits",
	"pojiy",
	"pojno",
	"poka",
	"pokaniy",
	"pold-gofal",
	"poldat",
	"poleym",
	"polma",
	"pomit",
	"pomol",
	"porin",
	"porsk",
	"posen",
	"posla",
	"posnek",
	"pot",
	"pramat",
	"pramon",
	"pranat",
	"printso",
	"printsya",
	"priskat",
	"priygat",
	"provikat",
	"prozat",
	"pyekol",
	"pyestat",
	"pyestelov",
	"pyete",
	"pyotsa",
	"pūkat",
	"pūsk",
	"rach",
	"ralinefeyv",
	"randa",
	"ravak",
	"redojan",
	"refa",
	"rekonelov",
	"remohilm",
	"remor",
	"revetat",
	"reya",
	"reynk",
	"rimar",
	"rinol",
	"rish",
	"rishdyu",
	"riy",
	"riyschat",
	"riyscho",
	"rlem",
	"rleyka",
	"rleykon",
	"rleyton",
	"rliykor",
	"rlobat",
	"rlobelov",
	"rlorta",
	"rlotin",
	"rlova",
	"rlovaniy",
	"rlovano",
	"rlūmik",
	"ro",
	"rogevik",
	"rogo",
	"roka",
	"roltat",
	"romat",
	"ronk",
	"rosa",
	"roska",
	"roskat",
	"roteyn",
	"rovat",
	"rovelov",
	"rovinlosik",
	"rozkūdat",
	"rūkan",
	"rūkat",
	"rūkelov",
	"rūvek",
	"saf",
	"sag",
	"salf",
	"salfniy",
	"sanva",
	"sarka",
	"sart",
	"saskar",
	"savadorn",
	"saveykat",
	"savlat",
	"savlelov",
	"sayron",
	"sbyaska",
	"sbyejat",
	"sdama",
	"sdivat",
	"sdivon",
	"sdoba",
	"sdovalat",
	"sefat",
	"sejren",
	"seleyka",
	"selin ahorstniy",
	"selin",
	"selkat",
	"semat",
	"sen",
	"seniy",
	"senjakat",
	"senya",
	"sert",
	"sesk",
	"sevel",
	"sevenak",
	"seviyntikor",
	"seyrin",
	"seyshin",
	"seyta",
	"shablon",
	"shanokat",
	"shara",
	"sharaniy",
	"sharn",
	"shast",
	"shelm",
	"shelnat",
	"shem",
	"shemo",
	"sheynata",
	"sheynatahilm",
	"sheyvat",
	"sholosmat",
	"shorog",
	"shovikin",
	"sidat",
	"sifmūjat",
	"sifmūjelov",
	"sikol",
	"silarkish",
	"sinak",
	"sisaka",
	"siskaka",
	"siymya",
	"siyn",
	"skacha",
	"skafan",
	"skakna",
	"skan",
	"skaton",
	"skazosat",
	"skazoselov",
	"skojyat",
	"skomat",
	"skorozat",
	"slapa",
	"slapat",
	"slask ojan neveskus",
	"slask",
	"slava",
	"slavniy",
	"slavon",
	"sliykat",
	"slyak",
	"slyenat",
	"smegat",
	"smidat",
	"smoterat",
	"snova",
	"soje",
	"sokovat",
	"soldat",
	"soler-seyrin",
	"solerat",
	"solerelov",
	"solma",
	"solmat",
	"solpar",
	"somrol",
	"somt",
	"somyenat",
	"soreyma",
	"sorkul",
	"sorn",
	"spaykat",
	"spaykon",
	"sperkat",
	"spistat",
	"spoklan",
	"sproskadar",
	"sproskat",
	"srakat",
	"srakelov-zona",
	"srakon",
	"srima",
	"sriyk",
	"srokor",
	"srokor-flust",
	"srovin",
	"stachevat",
	"stam",
	"statach",
	"stivol",
	"stodon",
	"stojagniy",
	"stolm",
	"stonat",
	"storkan",
	"stoya",
	"stoyat",
	"stoza",
	"strakat",
	"strakon",
	"stūn",
	"sveyzat",
	"sveyzejiy",
	"svinakniy",
	"svinyak",
	"svoloch",
	"svūsat",
	"syar",
	"syer",
	"ta",
	"talgat",
	"tam",
	"tamok",
	"tamok-vedon",
	"tanakin",
	"tankat",
	"tankon",
	"tasen",
	"tasen-krūch",
	"tasin",
	"tasin-gūl",
	"tasma",
	"tasnakin",
	"taspil",
	"tastanak",
	"tatsat",
	"teleportat",
	"teleportelov",
	"temena",
	"terolm",
	"terolm-stolm",
	"terolmat",
	"teshen",
	"teviysat",
	"teviysla",
	"teviysniy",
	"teyn",
	"teynkat",
	"teynkelov",
	"teynkelov",
	"teynkelov-stolm",
	"teysol",
	"tiglon",
	"tirsk",
	"tirt",
	"tiva",
	"tivesel",
	"to",
	"token",
	"tor",
	"tor-sikol",
	"tov",
	"tovat",
	"toviy",
	"tovon",
	"tovya",
	"treyvost",
	"treyvost-vedon",
	"trovakat",
	"trovakon",
	"tsajyo",
	"tsakiyn",
	"tsema",
	"tsiyja",
	"tsogniy",
	"tsūk",
	"tumrona",
	"tyeja",
	"tyevelm",
	"tyevesat",
	"tūshemol",
	"tūvigen",
	"ulsinan",
	"usin",
	"usin-",
	"usin-tivesel",
	"uu",
	"va jokle joglod",
	"va",
	"vakaj",
	"vam",
	"vampir",
	"vanar",
	"vanko",
	"variyn",
	"vark",
	"vark-mazo",
	"vas",
	"vatsavat",
	"vatsavelov",
	"vedon",
	"vemejat",
	"vemejo",
	"venat",
	"vendar",
	"venya",
	"verat",
	"vereta",
	"vernzat",
	"vidniy",
	"viltav",
	"vinova",
	"virikojan",
	"viskat",
	"viskon",
	"vlachya",
	"vladat",
	"vladelov",
	"vlado",
	"vlan",
	"vlaych",
	"vlebin",
	"vlebta",
	"vleyshat ta stolm",
	"vleyshat",
	"vleyshon",
	"vlika",
	"vlind",
	"vlo va fyadkaza",
	"vlo",
	"vlom",
	"vloma",
	"vlonorik",
	"vlorn",
	"vlorniy",
	"vlunst",
	"vlunstsikol",
	"vlyevlir",
	"vnyertiyak",
	"vodrin",
	"vok",
	"vok-gofal",
	"voldat",
	"voldon",
	"volfak",
	"volfakniy",
	"volikor",
	"voljun",
	"volnok",
	"volt",
	"voltat",
	"vomeygerat",
	"vorgat",
	"vorgon",
	"vosha",
	"vosta",
	"vovik",
	"voyakol",
	"vralat",
	"vrash",
	"vriynat",
	"vta",
	"vtir",
	"vtiyn",
	"vtyesh",
	"vtūn",
	"vya",
	"vyela",
	"vyen",
	"vyo",
	"vūka",
	"vūtat",
	"yad",
	"yadro",
	"yaglunt",
	"yameyga",
	"yanon",
	"yasha",
	"yatsat",
	"yatsiy",
	"yav",
	"yav-etsa",
	"yeda",
	"yegol",
	"yegta",
	"yeja",
	"yekya",
	"yela",
	"yelon",
	"yelta",
	"yenda",
	"yerikomat",
	"yerikomelov",
	"yetsat",
	"yev",
	"yibik",
	"yigala",
	"yikin",
	"yin",
	"yinforn",
	"yirk",
	"yisiy-gofal",
	"yiska",
	"yisko",
	"yiterator",
	"yiv",
	"yofeln",
	"yolen",
	"yom",
	"yonon",
	"yotat",
	"yusa",
	"yuselov korust",
	"yuselov",
	"zamorozat",
	"zamsel",
	"zast",
	"zava",
	"zavakon",
	"zavakonniy",
	"zikren",
	"zima",
	"zin",
	"ziynak",
	"ziynak-fushun",
	"zlamkat",
	"zlapat",
	"zlapelov",
	"zlapo",
	"zlobra",
	"zlomat",
	"zloy",
	"zlyatold",
	"znagat",
	"znomo",
	"zombye",
	"zona",
	"zoron",
	"zotol",
	"zotolniy",
	"zyej",
	"zyejat",
	"zyejniy",
	"zyetoda",
	"zyob",
	"zyovola",
	"zūla",
	"zūlat",
	"zūlelov",
	"zūsk",
	"ūkdunat",
	"ūkdunelov",
	"ūkelin",
	"ūnū-",
	"ūnū-mrotiysniy",
	"ūnū-ofitsa",
	"ūra",
	"ūskeyd",
];

const entries = {
	"-arvil": ["suffix", "suffix for worlds, universes, planets, etc"],
	"-dar": ["suffix", "forms gerund nouns from verbs; forms language names"],
	"-elov": ["suffix", "forms abstract nouns from verbs"],
	"-lalg": ["suffix", "forms language names"],
	"-niy": ["suffix", "forms adjectives from verbs, nouns"],
	"-o": ["suffix", "agent suffix; forms agent nouns from verbs"],
	"agelovor": ["noun", "factory"],
	"agent": ["noun", "agent"],
	"agentelov": ["noun", "agency"],
	"aglen": ["noun", "tree"],
	"agralamk": ["noun", "science"],
	"ahakat": ["verb", "to impale, to penetrate, to pierce"],
	"ahandat": ["verb", "to surprise"],
	"ahekerol": ["noun", "humanoid"],
	"ahorst": ["noun", "lust"],
	"ahorstat": ["verb", "to lust after, to have an intense sexual desire for"],
	"ahorstniy": ["adjective", "horny"],
	"ajam": ["noun", "age"],
	"akiv-stolm": ["noun", "bunker, safe house"],
	"akivat": ["verb", "to secure, to make safe; to clear an area of enemies"],
	"akivelov": ["noun", "security, defense"],
	"akūla": ["adjective", "aqua (color)"],
	"alan": ["adverb-preposition", "up, upwards"],
	"aleyva": ["adverb", "early"],
	"alkor": ["noun", "alchoholic drink; wine, beer, ale, mead, gin, vodka, whiskey, etc"],
	"alskeym": ["noun", "capsule"],
	"an-yitevat": ["verb", "to beware, to watch out, to raise guard, to be careful"],
	"Anglesdar": ["noun", "English, english"],
	"anglokish": ["noun", "anglothite"],
	"antul": ["noun", "armor"],
	"arda": ["adjective", "red"],
	"ariyka": ["adjective", "possible"],
	"armank": ["noun", "armanite"],
	"arsenk": ["noun", "arsenium"],
	"arta": ["noun", "bullet, bolt of energy/material"],
	"avtita": ["adjective", "automatic"],
	"azadar": ["noun", "morning"],
	"azar": ["noun", "sun"],
	"azleza": ["noun", "fame, reputation, renown"],
	"azlezaniy": ["adjective", "popular, famous"],
	"azorik": ["noun", "asteroid"],
	"babūshka": ["noun", "grandmother, grandma"],
	"baka": ["noun", "pie, pastry"],
	"bakov": ["noun", "trunk of vehicle"],
	"balbag": ["noun", "fox"],
	"balfat": ["verb", "to die to, to succumb to (with \"ev\" + indirect object)"],
	"bamat": ["verb", "to leave, to depart"],
	"barat": ["verb", "to bring, to take"],
	"bast": ["noun", "bow (weapon)"],
	"bazand": ["noun", "train"],
	"beldat": ["verb", "to relax, to rest"],
	"belekiyvadar": ["noun", "marriage, wedding"],
	"belekiyvat": ["verb", "to marry someone"],
	"belekiyvelov": ["noun", "marriage, wedlock"],
	"belok": ["noun", "rabbit"],
	"belor": ["noun", "thigh"],
	"biy vlebta volfak": ["verb", "to be in danger"],
	"biy": ["verb", "to be; is, am, are, be (past tense: biyt)"],
	"bizagat": ["verb", "to zap, to electrocute, to induce with lightning"],
	"blavonat": ["verb", "to behave well"],
	"bleniy": ["adjective", "nice, kind, friendly"],
	"bleyshon": ["noun", "town"],
	"blomeysel": ["noun", "necklace, amulet"],
	"blova": ["adjective", "hot"],
	"blovat": ["verb", "to heat, to warm, to make hot"],
	"blovon": ["noun", "heat"],
	"blūshor": ["noun", "robe, robes"],
	"bolon": ["noun", "pain"],
	"boreyv": ["noun", "friend"],
	"borod": ["noun", "beard"],
	"borogniy": ["adjective", "bitter"],
	"borotsa-vlaych": ["noun", "spacefighter, jet fighter, starfighter (ship)"],
	"borotsat": ["verb", "to fight"],
	"borotsorfak": ["noun", "martial art"],
	"bosenk": ["noun", "ladder"],
	"boshat": ["verb", "to sneak, to creep, to lurk"],
	"bosko": ["noun", "boy"],
	"boslat": ["verb", "to let, to allow, to permit"],
	"boslon": ["verb", "permit, license"],
	"bramat": ["verb", "to open"],
	"branzak": ["noun", "billion"],
	"brasliyvat": ["verb", "to curse, to put a curse on, to damn"],
	"brasliyvelov": ["verb", "damnation, curse"],
	"brasliyvon": ["noun", "curse"],
	"bratsa": ["noun", "bone"],
	"braykat": ["verb", "to control, to manipulate"],
	"brega": ["noun", "crow, raven"],
	"brelen": ["noun", "glass"],
	"bresh": ["noun", "smile, grin"],
	"breshat": ["verb", "to smile, to grin"],
	"breyk": ["noun", "gate"],
	"breytat": ["verb", "to pull"],
	"briyn": ["noun", "village"],
	"brogadaskat": ["verb", "to become fermented, to undergo fermentation, to ferment"],
	"brogadaskelov": ["verb", "fermentation"],
	"brolev": ["noun", "battle"],
	"brolev-seyrin": ["noun", "destroyer"],
	"bromin": ["noun", "bromine"],
	"brost": ["noun", "breast, bosom"],
	"brosyat": ["verb", "to help, to assist"],
	"byejat": ["verb", "to run, to sprint"],
	"byolm": ["noun", "bottle, jar"],
	"byortomat": ["verb", "to barricade, to block a pathway"],
	"būkat": ["verb", "to make"],
	"būkta-general": ["noun", "high general"],
	"būkta-markavo": ["noun", "high commander"],
	"būnat": ["verb", "to complete, to finish"],
	"chag": ["noun", "shit, crap"],
	"chaja": ["noun", "hour"],
	"chakat": ["verb", "to hurry, to quicken"],
	"chamrat": ["verb", "to experiment, to test"],
	"chamrelov": ["noun", "experiment, test"],
	"chana": ["noun", "wing"],
	"chanenk": ["noun", "human"],
	"chanenk-rlova": ["noun", "mankind, humans"],
	"chantol": ["noun", "battery, energy cell, energy weapon battery"],
	"chasta": ["adjective", "private, personal"],
	"chatat": ["verb", "to talk, to chat, to have a conversation with"],
	"chats": ["noun", "spice"],
	"cheklid": ["noun", "chainmail, maille"],
	"chemikol": ["noun", "chemical mixture"],
	"chemikolniy porsk": ["noun", "chemsuit, chemical suit; a full-body suit designed to protect the wearer from chemicals"],
	"chemikolniy": ["adjective", "chemical"],
	"chenk": ["noun", "chain"],
	"chenkat": ["verb", "to bind with chains, to chain; to repeat one after another; to repeat after, to follow after"],
	"chenskat": ["verb", "to shake"],
	"chesk": ["noun", "ink"],
	"chevakat": ["verb", "to cleave, to sever, to cut, to chop"],
	"chevelda": ["noun", "honor, honour"],
	"chobe": ["noun", "puppy, dog"],
	"choch": ["noun", "derogatory insult directed to women; slut, thot"],
	"choloskos": ["noun", "chlorine"],
	"chozniyka": ["noun", "school, academy"],
	"chyendat": ["verb", "to be really fond of, to crush on, to be infatuated with"],
	"chūmo": ["noun", "alien, extraterrestrial creature"],
	"daga": ["adjective", "strong"],
	"dagat": ["verb", "to strengthen"],
	"dagon": ["noun", "strength"],
	"dakast": ["noun", "dakasti, dakastus (monster, undead)"],
	"dame": ["noun", "lady"],
	"damerat": ["verb", "to cook"],
	"damero": ["noun", "a cook"],
	"dan": ["noun", "hand"],
	"dan-neygen": ["noun", "flashlight, torch"],
	"darga": ["adjective", "black"],
	"dasha": ["noun", "spear"],
	"daskon": ["noun", "harbor, docking bay"],
	"dast": ["noun", "reason, goal"],
	"davekta": ["adjective", "different"],
	"dedūshka": ["noun", "grandfather, grandpa"],
	"dekat": ["verb", "to wear, to don"],
	"delat": ["verb", "to do, to act"],
	"delon": ["verb", "deed, action"],
	"dergat": ["verb", "to masturbate"],
	"disk": ["noun", "piece, fragment, part"],
	"distinkish": ["noun", "distinite"],
	"dob": ["noun", "bar of metal"],
	"dojaposka": ["noun", "chart, diagram"],
	"dom": ["noun", "house, home"],
	"donar": ["noun", "father"],
	"dorn": ["noun", "north"],
	"dorolm": ["noun", "radio"],
	"dorolmatsol": ["noun", "radiation"],
	"dosk": ["noun", "board"],
	"dovat": ["verb", "to stop, to halt; to stop someone (with \"mol\" + from what)"],
	"dovinat": ["verb", "to remove, to take off"],
	"drak": ["noun", "weather"],
	"drasa": ["adjective", "wide"],
	"drasat": ["verb", "to widen, to expand"],
	"draselov": ["noun", "width, expansion"],
	"drason": ["noun", "width"],
	"drekenka": ["adjective", "nasty, disgusting"],
	"drin": ["adjective", "left direction (indeclinable)"],
	"drosel": ["noun", "reactor, generator"],
	"durst": ["noun", "war"],
	"durst-linya": ["noun", "front lines, combat zone"],
	"durst-seyrin": ["noun", "warship, any ship used for war"],
	"dursto": ["noun", "warrior, fighter"],
	"dyatsat": ["verb", "to hope"],
	"dyatson": ["verb", "hope, wish, want"],
	"dyonomat": ["verb", "to disintegrate, to turn into dust"],
	"dyonomelov": ["noun", "disintegration"],
	"dyot": ["adjective", "bad"],
	"dyu": ["noun", "day, day cycle"],
	"dūj": ["noun", "word"],
	"dūtska": ["noun", "feces, poop"],
	"egin": ["noun", "salt"],
	"eje": ["conjunction", "or"],
	"ekemiv": ["noun", "grenade"],
	"eksat": ["verb", "to exite"],
	"ele": ["adjective", "all, every (indeclinable)"],
	"ele-yin": ["verb", "always"],
	"eleytav": ["noun", "amethyst"],
	"elinar": ["noun", "elinar"],
	"elmej": ["noun", "ice"],
	"emertat": ["verb", "to like"],
	"enkankat": ["verb", "to reset, to refactor"],
	"enkar": ["noun", "disease, sickness"],
	"enlūtar": ["noun", "information"],
	"enlūtarat": ["verb", "to inform"],
	"erat": ["verb", "to hurt"],
	"erentekat": ["verb", "to enter, to go inside"],
	"eron": ["noun", "pipe"],
	"eskat": ["noun", "to carve, to etch"],
	"etsa": ["adjective", "other (indeclinable)"],
	"ev (1)": ["preposition", "caused by, because of, from"],
	"ev (2)": ["article", "article to turn transitive verbs into intransitive verbs"],
	"ev feydat": ["verb", "to be born"],
	"evnen": ["interjection", "a greeting; hello, hi"],
	"eykaza-vlaych": ["noun", "interceptor"],
	"eykazat": ["verb", "to intercept, to interrupt"],
	"eykazelov": ["noun", "interception, interruption"],
	"eyrin": ["noun", "east"],
	"eysh": ["noun", "shield"],
	"fach": ["noun", "data, info"],
	"fach-korust": ["noun", "document, file"],
	"fadafiy nevesk": ["noun", "nebula"],
	"fadat": ["verb", "to birth"],
	"faralskat": ["verb", "to deliver, to transport"],
	"faralskelov": ["noun", "deliverance, transportation"],
	"farsk": ["noun", "patrol"],
	"fedat": ["verb", "to receive, to collect, to get, to gain"],
	"felgniy": ["adjective", "real"],
	"felpat ... ots stoyi": ["verb", "to incapacitate, to disable, to neutralise"],
	"felpat": ["verb", "to put, to place"],
	"felpejiy ots stoyi": ["adjective", "incapacitated"],
	"felpelov": ["noun", "placement"],
	"femel": ["noun", "enchantom, elf"],
	"fenkat": ["verb", "to close"],
	"fernuska": ["noun", "energy, plasma"],
	"fetra": ["adjective", "pink"],
	"feydon": ["noun", "birth"],
	"feykat": ["verb", "to die"],
	"feykon": ["noun", "death"],
	"firtat": ["verb", "to tear, to rip apart"],
	"fishat": ["verb", "to feel, to touch"],
	"fistiyn": ["noun", "phystine"],
	"flaba": ["adverb", "away"],
	"flezat": ["verb", "to be fond of"],
	"flust": ["noun", "cell, ward, room"],
	"fodin": ["adverb", "now"],
	"fogor": ["noun", "base, root"],
	"fokat": ["verb", "to design, to model"],
	"fokelov": ["verb", "design, designation, model"],
	"folpo": ["noun", "hood"],
	"for": ["noun", "wire"],
	"forda": ["adjective", "blue"],
	"forkach": ["noun", "storm, tempest"],
	"formikat": ["verb", "to generate, to make from nothing"],
	"formikelov": ["verb", "generation, creation"],
	"forn": ["adverb", "forward, ahead"],
	"fornul": ["noun", "front (noun)"],
	"forosh": ["noun", "warp, fast travel, long distance jump"],
	"foroshat": ["verb", "to warp"],
	"fortul": ["noun", "finger"],
	"fovta": ["adjective", "dry"],
	"frastat": ["verb", "to prepare, to ready"],
	"frastelov": ["verb", "preparation"],
	"fresenk": ["noun", "fresenite"],
	"freyna": ["adjective", "long"],
	"freynon": ["noun", "length"],
	"freyshat": ["verb", "to kick"],
	"freyshon": ["noun", "kick"],
	"frid": ["adverb-preposition", "past"],
	"fridat": ["verb", "to pass"],
	"friyga": ["adjective", "cold"],
	"friygat": ["verb", "to cool, to chill, to make cold"],
	"friygon": ["noun", "cold (noun)"],
	"fulga": ["adjective", "evil, bad"],
	"furkun": ["noun", "symbol, icon, logo"],
	"furkunniy": ["adjective", "iconic, classic; legendary, renowned"],
	"fushun": ["noun", "powder"],
	"fyada": ["noun", "fire"],
	"fyadkaza": ["noun", "bullshit"],
	"fyej": ["noun", "fish"],
	"fyerda (1)": ["adverb", "first"],
	"fyerda (2)": ["adjective", "first (indeclinable)"],
	"fyeshon": ["noun", "peace, quiet, still, calm"],
	"fyetsat": ["verb", "to throw"],
	"fū": ["interjection", "ew, disgusted interjection (interjection)"],
	"fūmat": ["verb", "to smell"],
	"fūmon": ["noun", "smell, aroma, odor"],
	"fūshor": ["noun", "oven"],
	"fūskol": ["noun", "cheese"],
	"gadren": ["noun", "apple"],
	"galavat": ["verb", "to sing"],
	"galavon": ["noun", "song"],
	"galdar": ["verb", "cauldron, pot"],
	"galon": ["noun", "rubber"],
	"galv": ["noun", "weight"],
	"gardorn": ["noun", "decoration, jewelry, jewellery, ornament, cosmetic, makeup"],
	"gek": ["noun", "fletched arrow"],
	"geld": ["noun", "letter, rune, glyph"],
	"gelenat": ["verb", "to shout, to yell"],
	"gelenon": ["noun", "shout, yell"],
	"general": ["noun", "general"],
	"gim": ["numeral", "five"],
	"gitara": ["noun", "guitar"],
	"giton": ["noun", "shadow"],
	"gladat": ["verb", "to work (with labor), to run, to execute"],
	"gladon": ["noun", "job, occupication, work"],
	"glezat": ["verb", "to test, to examine, to evaluate; to test ability, intelligence, or skill"],
	"glezon": ["noun", "test, examination, quiz, questioning"],
	"glomat": ["verb", "to boil"],
	"gofal": ["noun", "machine"],
	"gojest": ["noun", "us fl oz, fluid ounce"],
	"golfat": ["verb", "to glow"],
	"golochas": ["noun", "intestines, bowel"],
	"golpar": ["noun", "crowd, throng"],
	"gonom": ["noun", "cosmic void"],
	"gor": ["numeral", "four"],
	"goreym": ["noun", "engine"],
	"gorin": ["noun", "month"],
	"gorovolm": ["noun", "furnace"],
	"gorst": ["noun", "liquid"],
	"gosin": ["noun", "overcoat"],
	"goskon": ["noun", "soup"],
	"gosteyn": ["noun", "minute"],
	"goveyn": ["noun", "hill"],
	"goza": ["noun", "ball, sphere"],
	"gradanat": ["verb", "to govern"],
	"gradandar": ["adjective", "governmental, federal, imperial, sovereign (indeclinable)"],
	"gradanelov": ["noun", "government"],
	"gralatin": ["noun", "graltite"],
	"gramat": ["verb", "to move"],
	"gramdar-seyrin": ["noun", "carrier ship"],
	"gramelov": ["verb", "movement"],
	"gredya": ["noun", "daughter"],
	"grenk": ["noun", "stone, rock"],
	"griyza": ["noun", "mold, mould, mold fungus"],
	"griyzniy": ["adjective", "moldy"],
	"grold": ["noun", "mace, club"],
	"gulva": ["noun", "cave"],
	"gunon": ["noun", "linen"],
	"gurk": ["noun", "natural oil"],
	"gyelat": ["verb", "to steal"],
	"gyelon": ["noun", "theft"],
	"gyoch": ["noun", "wood"],
	"gūl": ["noun", "year"],
	"gūnda": ["adjective", "weak, feeble, powerless; faint, slight"],
	"gūndelov": ["noun", "weakness"],
	"haln holova": ["noun", "deep space"],
	"haln narin": ["noun", "long range"],
	"haln/halnas/halneys": ["adverb", "far/farther/farthest"],
	"hamachat": ["verb", "to activate, to turn on, to switch on"],
	"hamachelov": ["noun", "activation"],
	"hamachniy": ["adjective", "active"],
	"hamya": ["noun", "music"],
	"hanakin": ["noun", "airlock"],
	"harskat": ["verb", "to explode"],
	"harskivolm": ["noun", "explosion"],
	"harskivolmniy": ["adjective", "explosive, exploding, combustive, volatile"],
	"havandat": ["verb", "to cover"],
	"hazak": ["noun", "hazard"],
	"hazakniy porsk": ["noun", "hazmat suit, hazardous materials suit; a full-body suit designed to protect the wearer from chemicals, biohazards, radiation, and other things"],
	"hazakniy": ["adjective", "hazardous"],
	"heka": ["adjective", "dirty, unclean, not clean"],
	"hemreviyta": ["adjective", "attractive, sexy"],
	"heton": ["noun", "group, type, kind, sort"],
	"hev": ["pronoun", "1st person plural nominative"],
	"heveskaniy": ["adjective", "effective, good, influencial"],
	"heveskat": ["verb", "to affect, to change, to influence"],
	"heveskelov": ["noun", "affection"],
	"heviy": ["pronoun", "1st person plural genitive"],
	"hevya": ["pronoun", "1st person plural accusative"],
	"heyjok": ["noun", "cannon"],
	"hilm": ["noun", "room"],
	"hiska": ["noun", "wall"],
	"hiv": ["noun", "light"],
	"hiynak": ["noun", "heart"],
	"hobrat": ["verb", "to hug, to embrace"],
	"hoja": ["noun", "pig, boar, hog"],
	"holmat": ["verb", "to support, to assist"],
	"holmelov": ["noun", "assistance"],
	"holova": ["noun", "outer space, cosmic space"],
	"holvat": ["verb", "to shake, to shudder, to shiver"],
	"horold": ["noun", "mage, wizard, sorcerer, magic user"],
	"horosha": ["adjective", "safe, secure, okay"],
	"horoshat": ["verb", "to make safe; to relieve, to sooth"],
	"horoshe dom": ["noun", "safe house, hidden outpost"],
	"hos": ["noun", "grip, handle"],
	"hosat": ["verb", "to hold, to have"],
	"hoselov": ["noun", "grip, holding"],
	"hosor": ["noun", "glove"],
	"hotat": ["verb", "to lift"],
	"hurk": ["noun", "arm"],
	"hūgnavol": ["noun", "lava, magma"],
	"hūva": ["adjective", "visible"],
	"igeja": ["adjective", "immune, unaffected"],
	"ijek": ["noun", "skill"],
	"ijyat": ["verb", "to turn on"],
	"ilgra": ["adjective", "yellow"],
	"illisin": ["noun", "illisinion"],
	"inshanosen seyrin": ["noun", "anti-infantry warship"],
	"ireten": ["noun", "tundra, snowy plains"],
	"isha-": ["prefix", "anti, against, versus"],
	"isha-gradano": ["noun", "insurgent, rebel"],
	"isheym": ["noun", "mean, meaning of"],
	"isik": ["noun", "smart, intelligent"],
	"isobramej": ["noun", "image, picture"],
	"istat yeltniy": ["verb", "to be gullible, to be easily fooled (\"Istafna yeltniy?\" = \"Do you think I'm stupid?\")"],
	"istat": ["verb", "to seem like, to look like (with \"ojan\" + indirect object)"],
	"itan": ["noun", "tip, top, ending"],
	"itevat": ["verb", "to see; to look (with \"ta\" + direct object)"],
	"itevon": ["noun", "scenery, sight"],
	"itevon-nosen": ["noun", "guard, guardian, protector, defender"],
	"jaken": ["noun", "taiga, snowy forest"],
	"jakot": ["noun", "electricity"],
	"jalat": ["verb", "to hail, to bow"],
	"jalgniy": ["adjective", "important, critical"],
	"janholva": ["noun", "victory; also shouted as a kagalarian warcry"],
	"janholvat": ["verb", "to win"],
	"jebat": ["verb", "to wait, to stay, to remain"],
	"jelb": ["noun", "dirt"],
	"jem": ["adjective", "good"],
	"jem-prozas": ["phrase", "welcome"],
	"jem-soleras": ["phrase", "goodbye"],
	"jemniy azadar": ["phrase", "good morning"],
	"jenerev": ["noun", "money, currency"],
	"jenrūk": ["noun", "truck"],
	"jentorom": ["noun", "assignment, essay, article"],
	"jerat": ["verb", "to listen, to hear"],
	"jeron": ["noun", "hearing"],
	"jesat": ["verb", "to clean"],
	"jevanat": ["verb", "to drive"],
	"jireyk": ["noun", "laser (weapon), thin hot beam of light"],
	"jiva": ["adjective", "tall"],
	"jiysniy": ["adjective", "happy"],
	"jogladya": ["noun", "goddess"],
	"joglod": ["noun", "god, deity"],
	"jokla": ["adjective", "great, mighty"],
	"jokla-seyrin": ["noun", "battleship, capital ship"],
	"jolon": ["noun", "territory"],
	"jolvun, -mūt": ["noun", "city"],
	"jolvun-vedon": ["noun", "urban camouflage"],
	"jonosk": ["noun", "road, street"],
	"jonya": ["noun", "woman, female"],
	"jorol": ["noun", "wheel"],
	"jovoma": ["adjective", "south"],
	"jrenat": ["verb", "to buy, to purchase"],
	"jrenelov": ["noun", "purchase"],
	"jromalar": ["noun", "earth, exoplanet"],
	"jūkat": ["verb", "to play"],
	"jūkon": ["noun", "play (the act of playing); a play, opera, or performance"],
	"kachol-nakin": ["noun", "a trillion meters, 1,000,000 kilometers"],
	"Kagalar": ["noun", "Kagalar"],
	"Kagalarlalg": ["noun", "Kagalarian language, kagalarian language"],
	"Kagalaro": ["noun", "Kagalarian, citizen of Kagalar"],
	"kagra": ["adjective", "spicy"],
	"kamiy-gofal": ["noun", "detector"],
	"kariyn": ["noun", "ship, vessel"],
	"karjen": ["noun", "gadget, trinket, unknown thing"],
	"karka": ["noun", "hull, shell"],
	"karn": ["noun", "edge"],
	"kartira": ["noun", "an apartment"],
	"kastarkish": ["noun", "quastarine"],
	"katalizator": ["noun", "potion base, brewing base, catalyst"],
	"katoj": ["noun", "turret, mounted gun"],
	"katokol": ["noun", "staff, stick, pole"],
	"kazar": ["noun", "emperor"],
	"kechye": ["noun", "penis, male reproductive organs"],
	"kejat": ["verb", "to crouch, to sneak"],
	"kelink": ["noun", "container"],
	"kelm": ["noun", "crown, helmet"],
	"keravat": ["verb", "to kiss"],
	"keren": ["noun", "surcoat, tabard"],
	"ketsat": ["verb", "to wait"],
	"keyda": ["adjective", "being fat"],
	"keymor": ["noun", "king, emperor"],
	"keynka": ["noun", "excuse"],
	"keyrin": ["noun", "galaxy"],
	"khaf": ["noun", "woof, bark (interjection)"],
	"khafat": ["verb", "to bark"],
	"khamat": ["verb", "to detect"],
	"khamelov": ["noun", "detection"],
	"khan": ["noun", "student, apprentice, learner"],
	"khanek": ["noun", "virus"],
	"khaton": ["noun", "solar system"],
	"khenkat": ["verb", "to contain, to have"],
	"khenkelov": ["noun", "containment"],
	"kholta": ["adjective", "freezing cold"],
	"kiyna": ["adjective", "brave, bold, courageous"],
	"kiynat": ["verb", "to add, to join"],
	"kiyta": ["adjective", "light in weight"],
	"klabanat": ["verb", "to call, to summon"],
	"klan": ["noun", "clan"],
	"klan-zūsk": ["noun", "tribe"],
	"klavon": ["noun", "concrete"],
	"klest": ["noun", "fang"],
	"kliyj": ["noun", "cell (biology)"],
	"kliyjbosenk": ["noun", "dna"],
	"klobol": ["noun", "table"],
	"klod": ["noun", "speed"],
	"kloma": ["adjective", "weird"],
	"klosis": ["noun", "golem"],
	"klova": ["adjective", "hard"],
	"klovat": ["verb", "to harden"],
	"knab": ["noun", "bread"],
	"knaba": ["noun", "sandwich, burger"],
	"kneska": ["noun", "mission, assignment"],
	"kniyga": ["noun", "book"],
	"kniyga-dom": ["noun", "library"],
	"kniza": ["adjective", "sharp"],
	"knopka": ["noun", "button; key (on a keyboard)"],
	"knopka-dosk": ["noun", "keyboard"],
	"knorota": ["noun", "corporation, company"],
	"knoto": ["noun", "someone"],
	"koda": ["adjective", "some, unknown amount"],
	"kodat": ["verb", "to turn off"],
	"kodosh": ["noun", "bug, insect"],
	"kofregad": ["noun", "an elemental"],
	"kohel": ["noun", "kohl (black makeup thing)"],
	"kojnok": ["noun", "bettle"],
	"kol": ["noun", "coal"],
	"kolminar, kolm": ["noun", "hand radio, walkie talkie, handheld transceiver"],
	"koloshem": ["noun", "lightning"],
	"koltat": ["verb", "to save, to rescue"],
	"komat": ["verb", "to use"],
	"komelov": ["noun", "purpose, usage, use"],
	"komnata": ["noun", "room, chamber, lodgings, dwelling, apartment"],
	"korin": ["noun", "korin"],
	"korust": ["noun", "paper"],
	"koshan": ["noun", "horse"],
	"koshniy": ["adjective", "interesting"],
	"koslamat": ["verb", "to cuss, to swear"],
	"kosma": ["noun", "neshozic orc"],
	"kosoril": ["noun", "world"],
	"kosvun": ["noun", "fight, combat"],
	"kot": ["noun", "cat"],
	"krasenk": ["noun", "thunder, sound of lightning"],
	"krelitsa": ["noun", "the cyrillic script"],
	"krepniy": ["adjective", "sturdy, strong, durable; defended, impervious"],
	"krest": ["noun", "chest, breast"],
	"krisnat": ["verb", "to blush, to fluster"],
	"kriysa": ["noun", "rat"],
	"kriysh": ["noun", "crystal, gem"],
	"krold": ["noun", "lawn, garden"],
	"krūch": ["noun", "chest, box, kist"],
	"kūd": ["noun", "mud, dirt, grime, slop"],
	"kūdat": ["verb", "to defile, to make dirty, to violate"],
	"kūdelov": ["noun", "defilement, violation"],
	"lagat": ["verb", "to speak, to talk; to say, to tell (with \"ta\" + clause)"],
	"lamk": ["noun", "reason, cause of"],
	"lanakon": ["noun", "ally, teammate"],
	"lanikat": ["verb", "to shine, to direct a light towards"],
	"latas": ["noun", "beam, bolt of lightning, laser (general term)"],
	"lazoprak": ["noun", "laboratory, room where scientific experiments are performed"],
	"lemat": ["verb", "to read"],
	"lemeynat": ["verb", "to build"],
	"lemeynelov": ["noun", "building, establishment, place, stead"],
	"len": ["conjunction", "but, yet, still"],
	"lenharsav": ["noun", "fortification"],
	"leselat": ["verb", "to cry, to weep"],
	"lesja": ["adjective", "soft"],
	"lesjiy": ["adverb", "softly "],
	"leyrkat": ["verb", "to connect, to link, to attach (with \"vlebta\" + direct object)"],
	"leyrkon": ["noun", "physical link, connection, or bond"],
	"lij": ["noun", "lie, deceit"],
	"lija": ["verb", "to lie"],
	"lijniy": ["adjective", "false, deceitful, ingenuine, lying"],
	"lin": ["noun", "rice"],
	"linikav": ["noun", "shop, store"],
	"linya": ["noun", "line"],
	"lis-nakin": ["noun", "centimetre, centimeter"],
	"lisa": ["adjective", "small"],
	"liyda": ["adjective", "easy"],
	"liydiy": ["adverb", "easily"],
	"liynkun": ["noun", "portal, wormhole"],
	"lodska": ["noun", "boat, rowboat, dinghy"],
	"logok": ["noun", "drink, beverage"],
	"loja": ["adjective", "false, incorrect, wrong"],
	"lokat": ["verb", "to drink"],
	"loloska": ["noun", "breast, bosom, boob, tit (slang)"],
	"loma": ["noun", "bed"],
	"lomisk": ["noun", "air tank, gas tank"],
	"lomiyn": ["noun", "hall, hallway"],
	"lonsa": ["adjective", "sour"],
	"lopelat": ["verb", "to circle, to surround, to go around, to loop"],
	"lorn": ["adverb", "backward"],
	"lornul": ["noun", "back (noun)"],
	"lorosil": ["noun", "circlet, crown"],
	"lorvet": ["noun", "land, ground"],
	"losik": ["noun", "station, outpost"],
	"lot": ["adverb", "just, only, merely"],
	"lovat": ["verb", "to operate, to handle, to use, to drive"],
	"lovmor": ["noun", "leader"],
	"lovo": ["noun", "operator, driver, crewmember"],
	"lyakasin": ["noun", "language"],
	"lyana": ["adjective", "bright, shining"],
	"lyoj": ["noun", "0.1 fluid ounces, 0.1 fl oz"],
	"lyon": ["noun", "snow"],
	"lūmenat": ["verb", "to learn"],
	"lūmenelov": ["noun", "knowledge"],
	"lūnst": ["noun", "garbage, trash"],
	"lūsabat": ["verb", "to love"],
	"lūsabo": ["noun", "lover, significant other"],
	"lūsabon": ["noun", "love"],
	"lūsniy": ["adjective", "sad"],
	"lūsomniy": ["adjective", "sorry"],
	"lūson": ["noun", "sorrow"],
	"lūtsat": ["verb", "to speak a language; to talk about (with \"ojan\" + direct object)"],
	"maglo-nakin": ["noun", "a million meters, 1000 kilometers, standard unit of mesurement in space, especially with warships"],
	"maglonak": ["noun", "million"],
	"maglopel": ["noun", "ton, 1000 kilograms, 1000000 grams"],
	"makav-dast": ["noun", "task, objective, goal"],
	"makta": ["adjective", "magenta"],
	"mamya": ["noun", "mother"],
	"manakon": ["noun", "enemy"],
	"manaktaro": ["noun", "villain"],
	"mank": ["noun", "gear, equipment"],
	"manomovol": ["noun", "hotel, inn"],
	"manyerta": ["noun", "manners, behaviour"],
	"mara": ["adjective", "brown"],
	"marfreno": ["noun", "marfrenic people"],
	"markav": ["noun", "command"],
	"markav-kneska": ["noun", "given mission, military operation"],
	"markavat": ["verb", "to command, to order"],
	"markavo": ["noun", "commander"],
	"marnin": ["noun", "marnine"],
	"maskara": ["noun", "mascara"],
	"mazo": ["noun", "man, male"],
	"medivala gūlus": ["noun", "medieval ages, middle ages"],
	"medivala": ["adjective", "medieval (indeclinable)"],
	"mejela": ["noun", "female reproductive organ"],
	"melokara": ["adjective", "gorgeous, beautiful"],
	"melskenat": ["verb", "to approach, to arrive, to enter location"],
	"menak": ["noun", "cloned human, clone"],
	"mert": ["noun", "meat, flesh"],
	"metonreyk": ["noun", "poison"],
	"mevol": ["noun", "head"],
	"mevol-": ["adjective", "main, primary, central"],
	"mevron": ["noun", "module, addon, extension"],
	"meynat": ["verb", "to be able to"],
	"meyrn": ["noun", "weapon"],
	"meyrn-hos": ["noun", "weapon grip, weapon handle"],
	"miln narin": ["noun", "short/close range"],
	"miln/milnas/milneys": ["adverb", "near/nearer/nearest"],
	"milneys ta": ["preposition", "next to, beside, by"],
	"mina": ["noun", "lamp"],
	"mishanat": ["verb", "to appear"],
	"miy joglod": ["interjection", "surprise interjection, meaning \"oh my god\", \"my god\", and other variants"],
	"miy": ["pronoun", "1st person singular genitive"],
	"miyka": ["adjective", "many, much, a lot"],
	"miyneyn": ["noun", "story, tale"],
	"miysh": ["noun", "mouse"],
	"mlada": ["noun", "blood"],
	"mliyr": ["noun", "glue"],
	"mloko": ["noun", "milk"],
	"mlonor ordelg": ["noun", "meteoroid; a small piece of space rock from the original asteroid/meteor; space debris"],
	"mlonor": ["noun", "meteor; the visible streak when an asteroid/meteoroid falls"],
	"mlonor-nok": ["noun", "meteorite; space rock that landed"],
	"mlordat": ["verb", "to destroy, to crumble"],
	"mol": ["preposition", "from"],
	"moldat": ["verb", "to form, to mold"],
	"moldon": ["noun", "form, shape"],
	"moljat": ["verb", "to carry"],
	"molosin": ["noun", "cow, cattle"],
	"moltun": ["noun", "power, strength, might"],
	"moltunniy pakfelpelov": ["noun", "emplacement, machine gun placement"],
	"molumba": ["noun", "nanopus (monster)"],
	"monot": ["noun", "floor"],
	"morigot": ["noun", "morigalt"],
	"morston": ["noun", "planet"],
	"mraka": ["adjective", "dark, murk, gloom"],
	"mrakelov": ["noun", "darkness, murkiness, blackness"],
	"mralat": ["verb", "to give, to grant"],
	"mrel": ["noun", "energy, power"],
	"mreynat": ["verb", "to burn"],
	"mreynniy": ["adjective", "damned, cursed"],
	"mrokek": ["noun", "mrokek"],
	"mroken": ["noun", "mroken"],
	"mrolmat": ["verb", "to rub"],
	"mrotiys": ["noun", "comfort"],
	"mrotiysniy": ["adjective", "comfortable"],
	"myal": ["noun", "meow (noun, interjection)"],
	"myalkat": ["verb", "to meow"],
	"myan": ["adverb", "very, really (used for the verb itself)"],
	"myerosta": ["adjective", "common"],
	"myoje": ["adverb", "might, maybe"],
	"myolomat": ["verb", "to moan"],
	"myuta": ["adjective", "shy, timid"],
	"mūlenat": ["verb", "to teach"],
	"mūva": ["noun", "leg"],
	"na": ["pronoun", "1st person singular nominative"],
	"nachkol": ["noun", "evil (noun)"],
	"nafrav": ["noun", "missile"],
	"nafrav-itan": ["noun", "warhead"],
	"naganork": ["noun", "dragon, wyvern"],
	"naka": ["noun", "foot, feet"],
	"nakin": ["noun", "meter"],
	"nalakish": ["noun", "nalastite"],
	"nalon": ["noun", "animal"],
	"nalva": ["adjective", "high"],
	"nalvat": ["verb", "to raise, to increase"],
	"nalvelov": ["noun", "increment"],
	"nalvon": ["noun", "height"],
	"napat": ["verb", "to fill"],
	"napniy, napejiy": ["adjective", "filled, full"],
	"narin": ["noun", "distance, range"],
	"nasheta": ["noun", "cloth"],
	"navek": ["noun", "name"],
	"navekat": ["verb", "to name, to call, to make known as; to be called (with \"ta\" + indirect object)"],
	"nebin": ["noun", "belly, stomach, bowel"],
	"nebra": ["adjective", "next"],
	"nebradyu": ["adverb", "tomorrow"],
	"nevesk": ["noun", "star"],
	"neya": ["pronoun", "1st person singular accusative"],
	"neygen": ["noun", "lightbulb, led, light"],
	"nezat": ["verb", "to need, to require"],
	"nezelov": ["noun", "requirement"],
	"nina": ["adjective", "dark, dim"],
	"ninelov": ["noun", "darkness, shadow"],
	"niska": ["noun", "magic, superhuman power"],
	"niska-": ["prefix", "super-"],
	"niska-gramo": ["noun", "telekinesis"],
	"niska-nova": ["noun", "supernova"],
	"nogen": ["noun", "pistol (gun)"],
	"nok": ["numeral", "zero"],
	"nokarish": ["noun", "controller, driving wheel, joystick"],
	"noklavin": ["noun", "fortress, castle, military base"],
	"nolma": ["noun", "mineral, metal, crystal"],
	"noltunniy": ["adjective", "powerful, mighty, strong"],
	"noreyg": ["noun", "mountain"],
	"noron": ["noun", "number, count, amount"],
	"nosen": ["noun", "soldier, troop, infantry"],
	"nosen-strakon": ["noun", "ptsd, post-traumatic stress disorder"],
	"nosenelov": ["noun", "army, ground force"],
	"nosh": ["noun", "nose"],
	"nov ele": ["adverb", "not always, not every one"],
	"nov eleyin": ["adverb", "not always, not all the time"],
	"nov": ["adverb", "not, negator"],
	"noviy": ["adjective", "modern, new age"],
	"nyak": ["interjection", "a cuss word"],
	"nyakat": ["verb", "to hate"],
	"nyakon": ["noun", "hate"],
	"nyeta": ["adjective", "empty, desolate, deserted"],
	"nyezlat": ["verb", "to lick"],
	"nyoskat": ["verb", "to lose, to lack"],
	"nyoskejiy": ["adjective", "lost, missing"],
	"nūla": ["adjective", "beautiful, pretty"],
	"oborsk": ["noun", "potato"],
	"odaka": ["adjective", "blunt, not sharp"],
	"ofitsa": ["adjective", "official, formal"],
	"oglaba": ["noun", "trouble, problem"],
	"ojan": ["preposition", "of; about, around, somewhere near"],
	"ojiy": ["conjunction", "and"],
	"ojoga": ["adjective", "ugly"],
	"oklenat": ["verb", "to fix, to repair"],
	"oleym": ["noun", "circle"],
	"olezat": ["verb", "to enjoy, to take pleasure in"],
	"olezelov": ["noun", "enjoyment"],
	"olva": ["adjective", "old"],
	"omenorst": ["noun", "divination, future sight"],
	"ona": ["pronoun", "3rd person feminine nominative"],
	"onayi": ["pronoun", "3rd person feminine genitive"],
	"onya": ["pronoun", "3rd person feminine accusative"],
	"ordelg": ["noun", "pebble, small rock"],
	"ore": ["noun", "cooking oil"],
	"oret": ["adverb-preposition", "out, outside"],
	"orfak": ["noun", "art"],
	"orgin": ["noun", "mouth"],
	"ork": ["noun", "ogre, orc, monster (monster)"],
	"orkel": ["noun", "axe"],
	"orlak": ["noun", "money, dollar, orlak, imperial kagalarian currency"],
	"oroskiyna": ["verb", "to warn"],
	"oroskiynon": ["noun", "warning"],
	"ot-": ["prefix", "opposite for verbs"],
	"ot-hamachat": ["verb", "to deactivate, to turn off, to switch off"],
	"ot-hamachelov": ["noun", "deactivation"],
	"otol": ["noun", "opposite"],
	"ots": ["adverb-preposition", "off"],
	"ove": ["noun", "ear"],
	"ovetadar yadro": ["noun", "reactor, generator (formal)"],
	"ovetat": ["verb", "to respond"],
	"ovetelov": ["noun", "response, reaction"],
	"ovig": ["noun", "bird"],
	"padat": ["verb", "to poke, to tap"],
	"pak": ["noun", "gun, rifle, pistol"],
	"pakosel": ["noun", "appearance, looks"],
	"pakyab": ["noun", "bucket, can"],
	"pan": ["adverb-preposition", "on"],
	"partye": ["noun", "party, feast, social gathering"],
	"paskenteyl": ["noun", "cylinder"],
	"pastak": ["noun", "baldric, sling"],
	"pelik": ["noun", "emotion, expression"],
	"peltenat": ["verb", "to study, to research"],
	"petika": ["noun", "chicken"],
	"pil": ["noun", "a gram, 1 gram"],
	"pivol": ["noun", "beer, ale"],
	"plachatun": ["noun", "century, 100 years"],
	"pliznat": ["verb", "to spark, to stir"],
	"plobskat": ["verb", "to bore, to be bored"],
	"plobskelov": ["noun", "boredom"],
	"plomat": ["verb", "to fall"],
	"ploviyatsol": ["noun", "prototype, an invented thing that is still in testing/being tested"],
	"plyenk": ["noun", "makeup, make-up, beauty products"],
	"pochka": ["adjective", "dear"],
	"pod": ["adverb-preposition", "under"],
	"pod-svūsat": ["verb", "to sign"],
	"pod-svūson": ["noun", "signature"],
	"poden": ["noun", "noon"],
	"pogladat": ["verb", "to pet, to caress, to soothe"],
	"pojalūsta": ["interjection", "please (interjection)"],
	"pojamits": ["noun", "chemise, frock, undergarment"],
	"pojiy": ["adjective", "cute, sweet, pretty"],
	"pojno": ["adverb", "late"],
	"poka": ["adjective", "rough, hard"],
	"pokaniy": ["adverb", "roughly, recklessly (adverb)"],
	"pold-gofal": ["noun", "scanner"],
	"poldat": ["verb", "to scan"],
	"poleym": ["noun", "cloak"],
	"polma": ["adjective", "slow"],
	"pomit": ["noun", "west"],
	"pomol": ["noun", "tower"],
	"porin": ["noun", "past (time)"],
	"porsk": ["noun", "suit, full body suit"],
	"posen": ["noun", "gas"],
	"posla": ["adjective", "middle"],
	"posnek": ["noun", "solid"],
	"pot": ["noun", "sweat"],
	"pramat": ["verb", "to prove"],
	"pramon": ["noun", "proof"],
	"pranat": ["verb", "to repeat"],
	"printso": ["noun", "prince"],
	"printsya": ["noun", "princess"],
	"priskat": ["verb", "to practice, to train"],
	"priygat": ["verb", "to jump"],
	"provikat": ["verb", "to punch"],
	"prozat": ["verb", "to come"],
	"pyekol": ["noun", "chair"],
	"pyestat": ["verb", "to annoy, to bother, to irritate"],
	"pyestelov": ["noun", "irritation"],
	"pyete": ["noun", "pet, domesticated animal"],
	"pyotsa": ["noun", "hip"],
	"pūkat": ["verb", "to scare"],
	"pūsk": ["noun", "buttocks, butt, bum, ass"],
	"rach": ["noun", "lever, switch"],
	"ralinefeyv": ["noun", "hospital"],
	"randa": ["noun", "moon"],
	"ravak": ["noun", "rifle (gun)"],
	"redojan": ["noun", "reedian (furry)"],
	"refa": ["adjective", "difficult, hard"],
	"rekonelov": ["noun", "reconnaissance"],
	"remohilm": ["noun", "bathroom, restroom, public bathroom"],
	"remor": ["noun", "relief"],
	"revetat": ["verb", "to have sex"],
	"reya": ["pronoun", "2nd person singular accusative"],
	"reynk": ["noun", "class, rank, role"],
	"rimar": ["noun", "window, visor"],
	"rinol": ["noun", "ghost, spirit"],
	"rish": ["adjective", "previous, last (indeclinable)"],
	"rishdyu": ["adverb", "yesterday"],
	"riy": ["pronoun", "2nd person singular genitive"],
	"riyschat": ["verb", "to ride"],
	"riyscho": ["noun", "knight"],
	"rlem": ["noun", "tongue"],
	"rleyka": ["noun", "car"],
	"rleykon": ["noun", "vehicle"],
	"rleyton": ["noun", "crew"],
	"rliykor": ["noun", "faction"],
	"rlobat": ["verb", "to free"],
	"rlobelov": ["noun", "freedom, liberty"],
	"rlorta": ["adjective", "poor"],
	"rlotin": ["adjective", "right direction (indeclinable)"],
	"rlova": ["noun", "kin, kinship, kind, race, species"],
	"rlovaniy": ["adjective", "native, aboriginal, indigenous"],
	"rlovano": ["noun", "native, resident, inhabitant"],
	"rlūmik": ["noun", "medicine"],
	"ro": ["pronoun", "2nd person singular nominative"],
	"rogevik": ["noun", "robot"],
	"rogo": ["noun", "bandit, thug"],
	"roka": ["noun", "structure, frame"],
	"roltat": ["verb", "to tilt, to become lopsided"],
	"romat": ["verb", "to walk"],
	"ronk": ["noun", "boot"],
	"rosa": ["noun", "rose"],
	"roska": ["adjective", "heavy in weight"],
	"roskat": ["verb", "to find, to search"],
	"roteyn": ["noun", "rule, law"],
	"rovat": ["verb", "to check, to inspect"],
	"rovelov": ["noun", "inspection"],
	"rovinlosik": ["noun", "checkpoint"],
	"rozkūdat": ["verb", "to rape, to sexually assault"],
	"rūkan": ["noun", "debris, rubble, crumbled pieces"],
	"rūkat": ["verb", "to describe"],
	"rūkelov": ["noun", "description"],
	"rūvek": ["noun", "spell, rune"],
	"saf": ["noun", "leaf"],
	"sag": ["noun", "knife, dagger, dirk"],
	"salf": ["noun", "health"],
	"salfniy": ["adjective", "healthy"],
	"sanva": ["noun", "character, avatar, person"],
	"sarka": ["adjective", "rare, scarce"],
	"sart": ["noun", "grass"],
	"saskar": ["numeral", "seven"],
	"savadorn": ["noun", "dictionary"],
	"saveykat": ["verb", "to scream"],
	"savlat": ["verb", "to analyze (analyse), to examine, to inspect, to study; to analyse data or output"],
	"savlelov": ["noun", "analysis, examination, inspection"],
	"sayron": ["noun", "flag"],
	"sbyaska": ["noun", "beach, strand, coast, shore"],
	"sbyejat": ["verb", "to escape"],
	"sdama": ["noun", "fork"],
	"sdivat": ["verb", "to aim"],
	"sdivon": ["noun", "target"],
	"sdoba": ["noun", "pants"],
	"sdovalat": ["verb", "to send"],
	"sefat": ["verb", "to thank"],
	"sejren": ["noun", "meadows, grasslands"],
	"seleyka": ["adjective", "gray, grey"],
	"selin ahorstniy": ["adjective", "erotic, sexually pleasing"],
	"selin": ["adjective", "same, like, equal"],
	"selkat": ["verb", "to rot"],
	"semat": ["verb", "to ought to be, to suppose to be (subjunctive = should be)"],
	"sen": ["pronoun", "3rd person masculine nominative"],
	"seniy": ["pronoun", "3rd person masculine genitive"],
	"senjakat": ["verb", "to injure, to hurt, to wound, to maim"],
	"senya": ["pronoun", "3rd person masculine accusative"],
	"sert": ["noun", "shirt"],
	"sesk": ["numeral", "six"],
	"sevel": ["noun", "water"],
	"sevenak": ["noun", "sea, ocean"],
	"seviyntikor": ["noun", "setting, configuration"],
	"seyrin": ["noun", "spacecraft, spaceship, ship"],
	"seyshin": ["noun", "terrain, land"],
	"seyta": ["adjective", "exotic, otherworldly"],
	"shablon": ["noun", "pattern, design"],
	"shanokat": ["verb", "to spy, to pry, to watch without being known"],
	"shara": ["noun", "metal"],
	"sharaniy": ["adjective", "metallic"],
	"sharn": ["noun", "iron"],
	"shast": ["adverb", "through"],
	"shelm": ["noun", "mask"],
	"shelnat": ["verb", "to sleep"],
	"shem": ["conjunction", "how"],
	"shemo": ["conjunction", "who"],
	"sheynata": ["noun", "rainy weather"],
	"sheynatahilm": ["noun", "bathroom, shower room"],
	"sheyvat": ["verb", "to care for, to nurture"],
	"sholosmat": ["verb", "to clean, to wash"],
	"shorog": ["noun", "shark"],
	"shovikin": ["noun", "future"],
	"sidat": ["verb", "to sit"],
	"sifmūjat": ["verb", "to surrender, to give up"],
	"sifmūjelov": ["noun", "surrender"],
	"sikol": ["noun", "cycle"],
	"silarkish": ["noun", "silartite"],
	"sinak": ["noun", "sign, signboard, mark, symbol"],
	"sisaka": ["adjective", "stupid, idiotic"],
	"siskaka": ["noun", "idiot, stupid person (insult)"],
	"siymya": ["noun", "sister"],
	"siyn": ["conjunction", "then"],
	"skacha": ["noun", "brush"],
	"skafan": ["noun", "scabbard, sheath"],
	"skakna": ["noun", "sky"],
	"skan": ["adverb-preposition", "over"],
	"skaton": ["noun", "wound"],
	"skazosat": ["verb", "to concentrate, to focus"],
	"skazoselov": ["noun", "concentration, focus"],
	"skojyat": ["verb", "to push"],
	"skomat": ["verb", "to shoot a weapon; to shoot at (with \"ta\" + direct object)"],
	"skorozat": ["verb", "to crawl"],
	"slapa": ["adjective", "weak, fragile, flabby"],
	"slapat": ["verb", "to weaken"],
	"slask ojan neveskus": ["noun", "star cluster"],
	"slask": ["noun", "cluster, bunch"],
	"slava": ["adjective", "glorious"],
	"slavniy": ["adjective", "slavic"],
	"slavon": ["noun", "glory"],
	"sliykat": ["verb", "to lie down"],
	"slyak": ["noun", "snake, serpent"],
	"slyenat": ["verb", "to cut, to slice, to slit"],
	"smegat": ["verb", "to bet, to gamble"],
	"smidat": ["verb", "to take off, to doff"],
	"smoterat": ["verb", "to stare, to gaze at, to look intensely"],
	"snova": ["adverb", "again"],
	"soje": ["noun", "sauce"],
	"sokovat": ["verb", "to sell"],
	"soldat": ["verb", "to tell someone"],
	"soler-seyrin": ["noun", "traveler, traveling ship (not a battleship)"],
	"solerat": ["verb", "to travel, to go (with \"ta\" + direct object)"],
	"solerelov": ["noun", "travelling, trip, trek"],
	"solma": ["adjective", "empty, vacant"],
	"solmat": ["verb", "to empty, to clear"],
	"solpar": ["noun", "sulfur, sulphur"],
	"somrol": ["noun", "night"],
	"somt": ["noun", "something, object"],
	"somyenat": ["verb", "to manufacture, to mechanically create/make"],
	"soreyma": ["adjective", "white"],
	"sorkul": ["noun", "sorkuls (monster)"],
	"sorn": ["adverb-preposition", "down, downwards"],
	"spaykat": ["verb", "to anger"],
	"spaykon": ["noun", "anger, rage"],
	"sperkat": ["verb", "to stalk"],
	"spistat": ["verb", "to save, to spare"],
	"spoklan": ["noun", "message"],
	"sproskadar": ["noun", "question, query, asking"],
	"sproskat": ["verb", "to ask"],
	"srakat": ["verb", "to kill, to slay"],
	"srakelov-zona": ["noun", "kill zone"],
	"srakon": ["noun", "murder, killing"],
	"srima": ["adjective", "green"],
	"sriyk": ["noun", "claw, talon"],
	"srokor": ["noun", "prison, jail"],
	"srokor-flust": ["noun", "prison cell, jail cell"],
	"srovin": ["noun", "ritual, spellcasting"],
	"stachevat": ["verb", "to tow, to drag"],
	"stam": ["noun", "belt"],
	"statach": ["noun", "speech"],
	"stivol": ["noun", "hat, headwear"],
	"stodon": ["noun", "hundred"],
	"stojagniy": ["adjective", "muscular"],
	"stolm": ["noun", "ground, the ground, land; place, location"],
	"stonat": ["verb", "to groan"],
	"storkan": ["noun", "building"],
	"stoya": ["noun", "stance, pose"],
	"stoyat": ["verb", "to stand"],
	"stoza": ["adverb-preposition", "between"],
	"strakat": ["verb", "to fear, to be afraid of"],
	"strakon": ["noun", "fear of"],
	"stūn": ["conjunction", "which, whom, that"],
	"sveyzat": ["verb", "to stick onto"],
	"sveyzejiy": ["adjective", "stuck"],
	"svinakniy": ["adjective", "perverted"],
	"svinyak": ["noun", "pervert, creep"],
	"svoloch": ["noun", "bastard (insult)"],
	"svūsat": ["verb", "to write"],
	"syar": ["adverb-preposition", "there"],
	"syer": ["adverb-preposition", "here"],
	"ta": ["adverb-preposition", "to, towards, at, till"],
	"talgat": ["verb", "to change, to alter, to modify"],
	"tam": ["conjunction", "if, in case"],
	"tamok": ["noun", "desert"],
	"tamok-vedon": ["noun", "desert camouflage"],
	"tanakin": ["noun", "square"],
	"tankat": ["verb", "to dance"],
	"tankon": ["noun", "dance"],
	"tasen": ["noun", "tool"],
	"tasen-krūch": ["noun", "toolbox, utility box"],
	"tasin": ["numeral", "ten"],
	"tasin-gūl": ["noun", "decade, 10 years"],
	"tasma": ["adjective", "fast, quick"],
	"tasnakin": ["noun", "kilometer"],
	"taspil": ["noun", "kilogram, 1000 grams"],
	"tastanak": ["numeral", "thousand"],
	"tatsat": ["verb", "to tie a knot, to secure"],
	"teleportat": ["verb", "to teleport"],
	"teleportelov": ["noun", "teleportation"],
	"temena": ["adjective", "rich"],
	"terolm": ["noun", "attack, assault"],
	"terolm-stolm": ["noun", "assault position, attack position, front line"],
	"terolmat": ["verb", "to attack, to assault"],
	"teshen": ["noun", "skin"],
	"teviysat": ["verb", "to watch"],
	"teviysla": ["adjective", "careful"],
	"teviysniy": ["adverb", "carefully"],
	"teyn": ["noun", "second"],
	"teynkat": ["verb", "to protect, to defend"],
	"teynkelov": ["noun", "defense"],
	"teynkelov": ["noun", "protection, defense"],
	"teynkelov-stolm": ["noun", "defensive position, strongpoint, fallback position"],
	"teysol": ["noun", "peak, top, highest point, maximum"],
	"tiglon": ["noun", "lizard"],
	"tirsk": ["numeral", "three"],
	"tirt": ["noun", "cake"],
	"tiva": ["adjective", "short"],
	"tivesel": ["noun", "clothing, garment, apparel"],
	"to": ["adverb", "so, very (used with adjectives)"],
	"token": ["noun", "cube"],
	"tor": ["numeral", "two"],
	"tor-sikol": ["noun", "bicycle, bike"],
	"tov": ["pronoun", "3st person plural nominative"],
	"tovat": ["verb", "to try, to attempt"],
	"toviy": ["pronoun", "3st person plural genitive"],
	"tovon": ["noun", "try, attempt"],
	"tovya": ["pronoun", "3st person plural accusative"],
	"treyvost": ["noun", "forest"],
	"treyvost-vedon": ["noun", "forest camouflage"],
	"trovakat": ["verb", "to execute, to put to death"],
	"trovakon": ["noun", "execution, death sentence"],
	"tsajyo": ["noun", "a thousand fluid ounces, 1000 fl oz"],
	"tsakiyn": ["noun", "rest, remaining"],
	"tsema": ["noun", "flower, bloom"],
	"tsiyja": ["noun", "an inch"],
	"tsogniy": ["adjective", "rude, mean, unfriendly"],
	"tsūk": ["noun", "door"],
	"tumrona": ["adjective", "orange"],
	"tyeja": ["noun", "honey"],
	"tyevelm": ["noun", "game, sport"],
	"tyevesat": ["verb", "to sail, to row a boat"],
	"tūshemol": ["noun", "stew"],
	"tūvigen": ["noun", "system"],
	"ulsinan": ["noun", "ulsinan"],
	"usin": ["adverb", "often, frequently, many times; casually"],
	"usin-": ["prefix", "informal, casual"],
	"usin-tivesel": ["noun", "casual clothing, everyday clothing"],
	"uu": ["interjection", "uhh (interjection)"],
	"va jokle joglod": ["interjection", "surprise interjection, meaning \"great god\", \"holy shit\", \"holy cow\", \"holy moly\", etc"],
	"va": ["article", "definite singular article"],
	"vakaj": ["noun", "tank"],
	"vam": ["conjunction", "than, compared to"],
	"vampir": ["noun", "vampire"],
	"vanar": ["numeral", "eight"],
	"vanko": ["noun", "brother"],
	"variyn": ["noun", "smoke"],
	"vark": ["noun", "wolf"],
	"vark-mazo": ["noun", "werewolf, wolfman"],
	"vas": ["article", "definite plural article"],
	"vatsavat": ["verb", "to summon, to conjure"],
	"vatsavelov": ["noun", "conjuration"],
	"vedon": ["noun", "camouflage"],
	"vemejat": ["verb", "to invent"],
	"vemejo": ["noun", "inventor"],
	"venat": ["verb", "to wish"],
	"vendar": ["numeral", "nine"],
	"venya": ["adjective", "standard, default, common, uniform"],
	"verat": ["verb", "to start"],
	"vereta": ["noun", "festival"],
	"vernzat": ["verb", "to return"],
	"vidniy": ["adjective", "bold, prominent, sticking out, different "],
	"viltav": ["noun", "alarm"],
	"vinova": ["adjective", "purple, violet"],
	"virikojan": ["noun", "conquest, invasion"],
	"viskat": ["verb", "to militarise, to establish military force"],
	"viskon": ["noun", "military, force"],
	"vlachya": ["noun", "witch, hag"],
	"vladat": ["verb", "to own, to have"],
	"vladelov": ["noun", "ownage"],
	"vlado": ["noun", "master"],
	"vlan": ["conjunction", "why"],
	"vlaych": ["noun", "fighter, interceptor"],
	"vlebin": ["adverb", "together"],
	"vlebta": ["preposition", "together with (contraction of \"vlebin ta\")"],
	"vleyshat ta stolm": ["verb", "to land a spacecraft"],
	"vleyshat": ["verb", "to fly"],
	"vleyshon": ["noun", "flight"],
	"vlika": ["adjective", "wet"],
	"vlind": ["noun", "wine"],
	"vlo va fyadkaza": ["phrase", "what the hell, wtf (cuss)"],
	"vlo": ["conjunction", "what, which; to what extent"],
	"vlom": ["conjunction", "where"],
	"vloma": ["adjective", "more"],
	"vlonorik": ["noun", "technology"],
	"vlorn": ["noun", "warmth, heat"],
	"vlorniy": ["adjective", "warm"],
	"vlunst": ["noun", "motor"],
	"vlunstsikol": ["noun", "motorcycle, motorbike, dirt bike"],
	"vlyevlir": ["noun", "elevator, lift"],
	"vnyertiyak": ["noun", "hell"],
	"vodrin": ["noun", "week"],
	"vok": ["noun", "eye"],
	"vok-gofal": ["noun", "camera"],
	"voldat": ["verb", "to think"],
	"voldon": ["noun", "thought, opinion, impression, mind"],
	"volfak": ["noun", "danger"],
	"volfakniy": ["adjective", "dangerous"],
	"volikor": ["noun", "potion"],
	"voljun": ["noun", "demon"],
	"volnok": ["noun", "volstone (monster, golem)"],
	"volt": ["noun", "defeat"],
	"voltat": ["verb", "to lose, to be defeated"],
	"vomeygerat": ["verb", "to disappear"],
	"vorgat": ["verb", "to invade"],
	"vorgon": ["noun", "invasion"],
	"vosha": ["noun", "evening"],
	"vosta": ["adjective", "big"],
	"vovik": ["noun", "bottle"],
	"voyakol": ["noun", "navy, air force, space force"],
	"vralat": ["verb", "to follow, to go with"],
	"vrash": ["noun", "sword"],
	"vriynat": ["verb", "to take, to grab"],
	"vta": ["preposition", "for (with indirect object); for the purpose of, to (with verb infinitive)"],
	"vtir": ["preposition", "after"],
	"vtiyn": ["conjunction", "when"],
	"vtyesh": ["preposition", "before"],
	"vtūn": ["conjunction", "while, whilst"],
	"vya": ["pronoun", "that, they, such"],
	"vyela": ["noun", "hair, fur"],
	"vyen": ["adverb-preposition", "in, inside, into; in a way"],
	"vyo": ["interjection", "no"],
	"vūka": ["adjective", "angry, mad"],
	"vūtat": ["verb", "to know, to understand"],
	"yad": ["interjection", "yes"],
	"yadro": ["noun", "core, heart, center"],
	"yaglunt": ["noun", "gear, cogwheel"],
	"yameyga": ["noun", "gymnastics"],
	"yanon": ["noun", "sound, noise"],
	"yasha": ["noun", "gift, present"],
	"yatsat": ["verb", "to stick to"],
	"yatsiy": ["adjective", "sticky"],
	"yav": ["numeral", "one"],
	"yav-etsa": ["adjective", "another"],
	"yeda": ["noun", "food, meal"],
	"yegol": ["noun", "clay"],
	"yegta": ["adjective", "salty"],
	"yeja": ["adjective", "sweet (taste)"],
	"yekya": ["noun", "candy"],
	"yela": ["adjective", "true, correct, right, truthful, legitimate, genuine"],
	"yelon": ["noun", "truth"],
	"yelta": ["adjective", "young"],
	"yenda": ["noun", "dress, gown"],
	"yerikomat": ["verb", "to remember"],
	"yerikomelov": ["noun", "remembrance"],
	"yetsat": ["verb", "to eat"],
	"yev": ["noun", "son"],
	"yibik": ["noun", "coin"],
	"yigala": ["noun", "noodles"],
	"yikin": ["noun", "sugar"],
	"yin": ["noun", "time"],
	"yinforn": ["noun", "verb tense"],
	"yirk": ["noun", "worm"],
	"yisiy-gofal": ["noun", "computer"],
	"yiska": ["noun", "girl"],
	"yisko": ["noun", "maiden, a young unmarried woman, can also refer to a woman who is betrothed but not yet married"],
	"yiterator": ["noun", "iterator"],
	"yiv": ["noun", "river, stream"],
	"yofeln": ["noun", "cargo"],
	"yolen": ["noun", "computer chip, microchip, circuit board"],
	"yom": ["noun", "celsius (temperature)"],
	"yonon": ["noun", "temperature, heat"],
	"yotat": ["verb", "to want"],
	"yusa": ["adjective", "new"],
	"yuselov korust": ["noun", "newspaper"],
	"yuselov": ["noun", "news, tidings, report"],
	"zamorozat": ["verb", "to freeze"],
	"zamsel": ["noun", "plan, strategy, intent"],
	"zast": ["noun", "sand"],
	"zava": ["adjective", "funny, hilarious"],
	"zavakon": ["noun", "empire, kingdom, nation, country, realm, reign"],
	"zavakonniy": ["adjective", "national, imperial"],
	"zikren": ["noun", "screen"],
	"zima": ["noun", "winter"],
	"zin": ["noun", "ginger"],
	"ziynak": ["noun", "bomb, explosive"],
	"ziynak-fushun": ["noun", "gunpowder, black powder"],
	"zlamkat": ["verb", "to stab, to stick in"],
	"zlapat": ["verb", "to commit a crime"],
	"zlapelov": ["noun", "crime"],
	"zlapo": ["noun", "criminal"],
	"zlobra": ["noun", "monster, unknown creature"],
	"zlomat": ["verb", "to slash, to cut, to hew"],
	"zloy": ["adjective", "evil, dark, grim (indeclinable)"],
	"zlyatold": ["noun", "trap"],
	"znagat": ["verb", "to capture, to take over"],
	"znomo": ["noun", "janitor"],
	"zombye": ["noun", "zombie"],
	"zona": ["noun", "place, area, zone"],
	"zoron": ["noun", "steel"],
	"zotol": ["noun", "gold"],
	"zotolniy": ["adjective", "gold, blond"],
	"zyej": ["noun", "life"],
	"zyejat": ["verb", "to live"],
	"zyejniy": ["adjective", "alive"],
	"zyetoda": ["noun", "lute"],
	"zyob": ["noun", "bump, bulb, protruding extension"],
	"zyovola": ["noun", "lyre"],
	"zūla": ["adjective", "low"],
	"zūlat": ["verb", "to lower, to decrease"],
	"zūlelov": ["noun", "decrement"],
	"zūsk": ["noun", "group of people, party, company, throng, crowd"],
	"ūkdunat": ["verb", "to transform, to turn into, to change"],
	"ūkdunelov": ["noun", "transformation"],
	"ūkelin": ["noun", "violin"],
	"ūnū-": ["prefix", "negator prefix"],
	"ūnū-mrotiysniy": ["adjective", "uncomfortable"],
	"ūnū-ofitsa": ["adjective", "unofficial, informal"],
	"ūra": ["noun", "fire, ember, spark"],
	"ūskeyd": ["noun", "dog"],
};

const special_declensions = {};
